### ISSUE TITLE
Redirect from Wikipedia enzyme pages broken

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#109]
E.g.:

https://en.wikipedia.org/wiki/Alkaline_phosphatase

Old style redirect, ends up at:

http://amigo.geneontology.org/amigo/term/GO:GO:0004035

Which is a 404.

Not sure far how upstream this should be fixed.

**Comment by kltm** [comment]
Just checked this, and it seems to work now...so all good?

**Comment by kltm** [comment]
The link is still horrible, but not the task here today.
