### ISSUE TITLE
Search directory page text clarification

### ISSUE THREAD

**Issue by rbalakri** [geneontology/amigo#130]
Hi Seth, all

I would like to suggest couple of changes for the Search Directory Page (the page that you arrive at after you search for a concept). This is the page that lists the hits in the Ontology, Gene/GP and Annotation categories. 
Change 
Ontology Ontology classes for GO is very jargony
 to
Gene Ontology Term or Synonym or Definition [tab] (# of hits)

Also for all three categories the # of hits is on the far right end of the row and my suggestion is to move it closer to the category name (just separated by a tab).

Thanks,
Rama

**Comment by kltm** [comment]
From the contexts that I've seen, changing to: 
```
description: Gene Ontology Term, Synonym, or Definition.
```
