### ISSUE TITLE
BFO terms in AmiGO are confusing

### ISSUE THREAD

**Issue by rbalakri** [geneontology/amigo#160]
Having BFO terms in AmiGO is confusing. Can we not load them?
http://amigo.geneontology.org/amigo/term/BFO:0000003
Thanks,
Rama

**Comment by kltm** [comment]
Unfortunately, I can't remember what additional steps are necessary beyond the above code and letting the loader naturally load after an update. I've done the update, and if the loader is successful, I'll consider this closed for 2.2.

**Comment by rbalakri** [comment]
Does this require us (stanford) to do a push?

R

**Comment by kltm** [comment]
When the time comes, this will be included in the 2.2 release.

**Comment by kltm** [comment]
Confirmed removal on last labs load.
