### ISSUE TITLE
Double check that multiple relations are handled correctly in visual context

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#161]
This means that the perl and JS widget correctly handle having multiple relations in the transitivity graph (e.g. when both is_a and regulates are available, regulates is chosen).

**Comment by kltm** [comment]
The JS seems to be fine. Upstream in bracket.js, the rel lists go through something like 				 
```
pred_id = anchor.dominant_relationship(trels);
```

**Comment by kltm** [comment]
The perl is a little more quirky, it seems to behave similarly: see ChewableGraph.pm.

**Comment by cmungall** [comment]
Some examples:
 
 * http://amigo2.berkeleybop.org/amigo/term/GO:2000305
    * Tests: property chain display is valid
    * Expects:
       * [P o R] GO:0072499 photoreceptor cell axon guidance (depth=1)
       * [P o R] GO:0007411 axon guidance (depth>1)
 * Passes: yes
 * http://amigo2.berkeleybop.org/amigo/term/GO:0061475
    * Tests: occurs_in glyph is present
    * Expects:
       * [O] cytosol (depth=1)
       * [O] cell (depth>1)
 * Passes: yes

**Comment by kltm** [comment]
Touched bases with @hdietze about the current product of the loader in this case. We are making use of a "fail" state here because of the current expression materializing reasoner. A more detailed explanation of what's going on right now can be found on the wiki.

https://github.com/kltm/bbop-js/wiki/TransitivityGraph#troubleshooting-caveats-and-fail-modes

**Comment by kltm** [comment]
Will use "related_to" for the time being as the fall through relation in graph handling.
