### ISSUE TITLE
Create a drill-down ontology browser widget

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#163]
A dead simpler widget for burrowing down into the ontologies from the top level, so we don't have to worry about multiple paths, etc.

Idea is to keep it flexible to extend into something to help create slims later on, etc.

**Comment by kltm** [comment]
Add the annotation counts and side filters.
Side filter adjustments cause reset (to root).
On drilldown open, all items without a count use the new promise sync pattern to get counts as they can.

**Comment by kltm** [comment]
This technically fulfils the requirements for this ticket. However, I'm going to see how easy the filters would be to bolt on, assuming an automatic reset action.

**Comment by cmungall** [comment]
I'm testing here: http://tomodachi.berkeleybop.org/amigo/dd_browse

I find the locations to click on for operations to be a bit confusing, but maybe I'm UI challenged. Others should weight in. Ideally 3 clearly visible icons for these options

 - expand this node (and a clear visual indicator if this is a leaf)
 - info on this term
 - clicking on the numbers should take you through to the numbers (entities or associations, see below)

Looks like this is annotation counts. Entity counts may be more intuitive (this currently limits the filters we can use, but that's OK, see below). Switching might be useful but not sure how essential, others should weight in. 

For filters, I think the most useful would be species. I don't know what's best for the UI. On the one hand, the normal filter panels may be overkill here. OTOH, it would be interesting to see how numbers for other filters change as we drill down, e.g. panther families.

But overall

**Comment by kltm** [comment]
There are main two issues you're butting up against here.

The first is that we are using a specific widget lib to create the tree. The tree widget can be variously overridden, but fighting its nature makes things buggy and slow to develop. Ideally, we would either write our own (not that hard to do) or find a better one; but for the time being, from what I've seen, this one seems to have the easiest set of features and function to work with to get something out the door yesterday.

The next bit is lookahead. Since we don't load what's a leaf and what's an internal node into the neighbourhood and graph info that we currently load, we don't have an easy way to display that without attempting to open--there is even a comment about this in the instructions. The fan-out is high enough that actually doing the lookahead would not be good, and doing it async like the counts would take even longer and cause more distracting shifts in the UI.

Currently, clicking takes you to term info which then has a new window link to the annotation search page filtered to that point. I guess that action depends on whether you're interested in browsing in general, or specifically just getting at annotation/bioentity searches. I saw the scope as the somewhat wider case.

Whether bioentity or annotation is a pretty easy change, with no consequences in the code, so either is fine, just give the word. We might even be able to have a toggle there. (Let's see what happens with the addition of filters.)

**Comment by kltm** [comment]
As well, I need to get this onto the front page as well. I'd like to make it an even six or eight, so could you comment on one to add or subtract from the pool in [tools & software]?

**Comment by kltm** [comment]
Reopen until done testing, feedback, etc.

**Comment by kltm** [comment]
Did some testing, and it seems to work pretty much as advertised now.

**Comment by cmungall** [comment]
Do you want feedback on this ticket?

I see you've added the facet filters. Others should weigh in on my point above:
> For filters, I think the most useful would be species. I don't know what's best for the UI. On the one hand, the normal filter panels may be overkill here.

It is really confusing having the ontology facets in there. Especially as faceting doesn't reduce the numbers as naively expected (in fact this is not surprising as annotations propagate over some kinds of inter-ontology links, so this is a potentially very powerful feature for looking at the impact of inter-ontology links, but VERY confusing for most folks)

Having the organism/species facet is AWESOME however.

Some of the others... they make logical sense but I'm not really seeing a use case for having them.

**Comment by kltm** [comment]
Well, not so much about want or not at this point--it's all of a package right now. There'd either have to be a new personality for a limited filter set (super easy but proliferates personalities), or the filter itself could have a filter list of what to draw. At the moment, the latter sounds easier/cleaner, as I'm about to climb in to #308, which has a similar pattern.

**Comment by kltm** [comment]
Ah, but a widget whitelist wouldn't prevent things from being requested over the wire, unless modifications were made to the gconf object before passing it in. And at that point, you may as well go for a different personality.
