### ISSUE TITLE
Upstream PANTHER term enrichment links are sometimes dead

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#172]
Taking a look at this example:

http://pantherdb.org/webservices/go/overrep.jsp?ontology=biological_process&input=P31946%0AP62258%0AQ04917%0AP61981%0AP31947%0Abaxter%0AP27348%0AP63104%0AQ96QU6%0AQ8NCW5%0AAKT1%0ACRIM1%0AEIF2AK3%0AGHR%0AGIGYF1%0AGIGYF2%0AGRB10&species=HUMAN&correction=bonferroni&format=html

Items linked out such as:

http://pantherdb.org/panther/category.do?categoryAcc=GO:0009967
http://pantherdb.org/panther/category.do?categoryAcc=GO:0009966
http://pantherdb.org/panther/category.do?categoryAcc=GO:0045859

etc., just give an uninformative error.

**Comment by kltm** [comment]
Pinging on @mugitty.

**Comment by kltm** [comment]
@mugitty is currently working on it; the fix will roll out tonight.

**Comment by mugitty** [comment]
Fixed.

**Comment by kltm** [comment]
@mugitty Is there any way you can correct the AmiGO URLs that are being output (thank you!) from the page from the form:

 http://amigo.geneontology.org/cgi-bin/amigo/term_details?term=GO:0051128

to the correct form:

 http://amigo.geneontology.org/amigo/term/GO:0051128

**Comment by kltm** [comment]
@mugitty if you're using the db-xref.legacy file, I've just fixed it--they should get through the pipeline in an hour or two.

**Comment by mugitty** [comment]
Both url's are giving a 404 error.

**Comment by kltm** [comment]
@mugitty it looks like production cleared their server problems--the URLs should be fine now.

**Comment by kltm** [comment]
From @mugitty 
```
I will update from  http://amigo.geneontology.org/cgi-bin/amigo/term_details?term= to http://amigo.geneontology.org/amigo/term/
```
closing
