### ISSUE TITLE
Add option for no correction to RTE

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#175]
This is from http://jira.geneontology.org/browse/GO-754

The idea is to add a "none" correction, in addition to the currently locked-in "bonferroni". This is fairly easy to do: add as an option and reintroduce the "Advanced" link.

**Comment by kltm** [comment]
Pinging on @mugitty.

**Comment by kltm** [comment]
Trying with this URL:

http://pantherdb.org/webservices/go/overrep.jsp?ontology=biological_process&input=P31946%0AP62258%0AQ04917%0AP61981%0AP31947%0AP27348%0AP63104%0AQ96QU6&species=HUMAN&correction=none&format=html

The results seem to show that Bonferroni was used even with the "correction" parameter set to "none". Is my usage correct here?

**Comment by kltm** [comment]
Looks like it works, but upstream is checking the form variable.

**Comment by mugitty** [comment]
Fixed!
