### ISSUE TITLE
Define ontology "roots" using configuration variables or files

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#178]
We occasionally have a page that for some reason needs to know the roots of the view (or other graph related meta-information). For example, the ontology and drill-down browsers.

Currently, this information is somewhat hard coded into the app. This is rather silly and could easily pulled from a configuration variable.

This is a requirement for a general AmiGO browser from a developer/deployment viewpoint.

**Comment by kltm** [comment]
This seems to be a dupe of #322 ?

**Comment by cmungall** [comment]
Yes, dupe.

At some stage it would be useful to switch from yaml to an annotation property, coordinate with
https://github.com/EBISPOT/OLS/issues/102#issuecomment-235536128
