### ISSUE TITLE
Show assigned_by in Source column

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#179]
E.g. http://amigo.geneontology.org/amigo/term/GO:0008140
Find 
```
UniProtKB       O43293  DAPK3           GO:0008140      PMID:14685163   TAS             F       Death-associated protein kinase 3       DAPK3_HUMAN|DAPK3|ZIPK  protein taxon:9606      20150126        ParkinsonsUK-UCL has_direct_input(UniProtKB:P18848)
```

Here assigned_by is  ParkinsonsUK-UCL

In theory we could have another col for DB prefix of the bioentity but this clutters. It's more important to show correct attribution for work.

**Comment by cmungall** [comment]
And probably best to actually relabel the "source" column to use consistent terminology. Although assigned_by is somewhat consistent with dublin core source

**Comment by kltm** [comment]
I'm not sure I'm following the action here: we currently display both source and assigned_by  for annotations.

**Comment by kltm** [comment]
Talked with @cmungall. This is in reference to the automatic annotation results tables that are generated here and there. The issue is to switch out source for assigned_by.
