### ISSUE TITLE
Add a handler to make "not"s sufficiently visible

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#180]
Add a handler for the qualifier column in order to make the contents sufficiently noticeable. This is from Val on:

 http://jira.geneontology.org/browse/GO-779

**Comment by rbalakri** [comment]
Also in AmiGO1, the NOT qualifier was nice and bright in red color (upper case). May be we can restore that display?
http://amigo1.geneontology.org/cgi-bin/amigo/gp-assoc.cgi?gp=PomBase:SPBC16A3.05c&session_id=577amigo1426806980

R

**Comment by kltm** [comment]
Fixed on master and 2.2.x, adding the required handler code and the required class.

**Comment by kltm** [comment]
Ping @cmungall to prevent further effort.
