### ISSUE TITLE
Revert loaded ontologies to 2.1.x to prevent exotic ontology overload

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#186]
On the ontology search page, for [Ontology source], we now have (at the moment in 2.2.x):

```tsv
ncbi_taxonomy	(1175662)	+	-
chebi_ontology	(56285)	+	-
biological_process	(28204)	+	-
mouse_ontology	(19445)	+	-
uberon	(10947)	+	-
molecular_function	(10837)	+	-
cellular_component	(3915)	+	-
adult_mouse_anatomy.gxd	(3229)	+	-
uberon/phenoscape-anatomy	(2682)	+	-
quality	(2515)	+	-
cell	(2128)	+	-
plant_anatomy	(1357)	+	-
eco	(583)	+	-
plant_structure_development_stage	(333)	+	-
none	(282)	+	-
external	(138)	+	-
go/extensions/gorel	(59)	+	-
cl	(22)	+	-
pato.ontology	(3)	+	-
plant_ontology	(2)	+	-
```

While we want these for testing for the time being, we do not want to overload users in production. Talking to @cmungall and @hdietze, it was decided to go back to the closest set we can to the previous set used in 2.1.x. This is only for 2.2.x, master will remain with the larger set for now.

We also need to make sure that our fix here does not interfere with the fixes for #160.

Long-term solutions will likely involve deeper fixes in searches, filtering, and facets--we do want to have everything in there eventually, but just not at the moment like this.

**Comment by kltm** [comment]
Open until corrections are confirmed on revived nakama.

**Comment by kltm** [comment]
Taking a look at the current results on http://nakama.berkeleybop.org/amigo, agreed that it is good enough for now.

**Comment by cmungall** [comment]
For future reference: we will abandon use of obo-namespace as an ontology class partitioning method.

One option is to use the ontology ID, but this is (a) opaque (who would know that cl is cell types?) and (b) does not partition go into 3 sets

We may then instead use a modified variant of namespace we control. This would become a strictly upstream ontology or ontology loading responsibility (we could choose to keep overloading the obo namespace tag). For example, 

 * idspace=go --> use namespace
 * idspace=cl --> cell type
 * idspace=uberon --> animal anatomy
 * idspace=po--> plant

etc

Another option is to combine the broad category and subsets into a single hierarchical facet. E.g.

 * go
    * biological process
       * prok (bp)
       * goslim (bp)
       * ...
    * molecular function
       * prok (mf)
       * goslim (mf)
       * ...
   * cell


We should also remove underscores in display (or better yet, upstream, making the category an object with human readable label)
