### ISSUE TITLE
Some pages do not display correctly in Chrome

### ISSUE THREAD

**Issue by rbalakri** [geneontology/amigo#191]
HI,
This page doesn't display correctly in Chrome-
http://amigo.geneontology.org/amigo/gene_product/RNAcentral:URS00004C9052_9606
Looks fine in Firefox.

Rama

**Comment by cmungall** [comment]
Oh dear, not good

Fortunately fine in beta
http://amigo2.berkeleybop.org/amigo/gene_product/RNAcentral:URS00004C9052_9606

And stage:
http://amigo2-test.stanford.edu/amigo/gene_product/RNAcentral:URS00004C9052_9606

So will presumably be fixed in public shortly. How did this escape our 
notice for so long?

@mdolanme is this something that can be tested for prospectively in 
future, e.g. using behave?

**Comment by mdolanme** [comment]
Sorry for the delay, network and email problems yesterday and today.

Would grabbing screenshots in various browsers be sufficient?



Mary E. Dolan, Ph.D.
Research Scientist
Department of Bioinformatics and Computational Biology
The Jackson Laboratory
Mary.Dolan@jax.org
207.288.6439
________________________________

**Comment by kltm** [comment]
It does not appear on any page in all cases. It seems to be an artifact of something in Bootstrap colliding with some defaults in the CSS...

**Comment by kltm** [comment]
And the very long GP name seems to be play. Only happens at certain zoom levels as well.

Found likely problems in upstream 2.2.x two-column widget--had a hard-coded width that could override the class CSS class definition. Fixed and tested on 2.2.x dev.

**Comment by kltm** [comment]
Just needs to be put into production.

**Comment by rbalakri** [comment]
Seth,

Thanks. Is there a way in github to indicate that this fix is ready for production?
Or do I need to let Kalpana know?

Rama

**Comment by kltm** [comment]
I already pinged @mugitty ; For branches (production releases), closing means that the fix has already been committed.

**Comment by kkarra** [comment]
Fix in production.

**Comment by kltm** [comment]
Looks good--thanks!
