### ISSUE TITLE
There appears to be an error in symbol creation in the GOlr loader

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#196]
Taken from another discussion, @cmungall writes:

The ... issue is a golr loading bug and could be assigned to @hdietze -- gene_association.goa_human uses SAA1 for P0DJI8, whereas for whatever reason it is ending up as SAA1_HUMAN in golr. See:
http://amigo.geneontology.org/amigo/gene_product/UniProtKB:P0DJI8

Assuming that this is not just a data problem, the expected fix would be that the symbol for UniProtKB:P0DJI8 would be "SAA1" instead of "SAA1_HUMAN".

**Comment by kltm** [comment]
Removed @hdietze as this is likely my code doing something odd.

**Comment by kltm** [comment]
Pinging on @cmungall.

**Comment by selewis** [comment]
This looks incredibly similar to the labels used by PAINT. Which method is
being called, that is which method of Bioentity ?

**Comment by kltm** [comment]
```shell
zgrep -c P0DJI8 *.gz
...
gene_association.goa_human.gz:43
gene_association.goa_ref_human.gz:43
gene_association.goa_uniprot_noiea.gz:41
gene_association.mgi.gz:6
gene_association.reactome.gz:17
```

Looking, is seems reactome uses the SAA1_HUMAN symbol. Who wins?

**Comment by kltm** [comment]
This is looking rather data. However, it would be nice to make sure that whatever symbol gets left out of becoming the "one" should be added to the synonyms list.

**Comment by kltm** [comment]
Who knows, but the information seems to be "correct" now in AmiGO production, so chalking it up to data and closing.
