### ISSUE TITLE
Update http://amigo.geneontology.org/xrefs info

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#199]
Migrated from:
geneontology/go-site#62

Current:

> This page is also available as a plain text file. Further documentation on database abbreviations is  available in the database abbreviations specifications (plain text format). To suggest new entries please use the GO contact form. 

Change to:

> This page is also available as a yaml file and a plain text file. See the documentation here:
 https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.md

Note the md contains info on how to suggest a new entry (github PR)

**Comment by kltm** [comment]
To get an immediate fix, we could also get a redirect at production to make sure http://geneontology.org/doc/GO.xrf_abbs_spec goes to the right place until a patch is put into production.

**Comment by cmungall** [comment]
No I think that should remain there as documentation for the legacy 
xrf_abbs format. I have added a link within it that points people to the 
new format and docs
