### ISSUE TITLE
Make more parts of annotation extensions searchable

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#200]
Currently in AmiGO, annotation extensions are stored as 1) a blob (annotation_extension_json) and 2) annotation extension classes (including class, class_label, the closures, searchables, etc.).

However, this means that you are unable to do things like find the target of an activity (e.g. has_input(UniProtKB:O89046) by normal searching methods. Moreover, even power tools like gannet are unable to do much here since the blob is not searchable. (The only way would be CLI tools, like the bbop libs, and parsing the output yourself).

The goal here would be to make a satisfying amount of the annotation extension structure available to the standard AmiGO interface.

This also means that we'll need to add more fields to the load.

This issue is originally from: http://jira.geneontology.org/browse/GO-838

**Comment by kltm** [comment]
Will need to work with @hdietze and @cmungall. Currently unsure of the overlap with complex annotation (lego) and other pushes.

**Comment by cmungall** [comment]
By a weird coincidence I answered the go help ticker at exactly the same time: #201 

The two are complementary. An additional field for this would be useful

**Comment by kltm** [comment]
While technically I got in first here, yours is more complete. I'll dupe onto #201 and comment there (and maybe make the title a little more clear to myself).

**Comment by cmungall** [comment]
We left a few, for possible future extensions

These should all have a standard closure quad

 * affects
 * affected_by
 * during
 * subfunction
 * substrate

**Comment by ValWood** [comment]
From
https://github.com/geneontology/amigo/issues/412
Please make it possible to filter on extension relationship type
