### ISSUE TITLE
error message for matrix tool

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#205]
I'm reporting this in case anything has cone awry. The error message is dated yesterday:

error: GOlr is currently being reloaded (started at 16:50 on 2015-05-18). Any results will be partial at best--please check back later.

**Comment by cmungall** [comment]
Was this the dev instance on Berkeley or production on geneontology.org?

**Comment by ValWood** [comment]
On 19/05/2015 18:11, Chris Mungall wrote:
>
> Was this the dev instance on Berkeley or production on geneontology.org?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/geneontology/amigo/issues/205#issuecomment-103597091>.
>

This is the link I use:
http://amigo2.berkeleybop.org/matrix

**Comment by kltm** [comment]
Sorry, this is a known error. it's just us trying to figure out how to get our pipeline back in working shape (a series of Very Bad Events). @hdietze things he'll have a workaround in place later today, and I'll start a new load then.

**Comment by kltm** [comment]
@ValWood you do **not** know about this, but in the meantime: http://amigo.geneontology.org/matrix

After we have our fix in, please forget about that.

**Comment by ValWood** [comment]
On 19/05/2015 19:09, kltm wrote:
>
> @ValWood <https://github.com/ValWood> you do *not* know about this, 
> but in the meantime: http://amigo.geneontology.org/matrix
>
> After we have our fix in, please forget about that.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/geneontology/amigo/issues/205#issuecomment-103618206>.
>


Thanks so much :), I will wipe...
