### ISSUE TITLE
Gannet annotation count query description is incorrect

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#206]
http://amigo.geneontology.org/gannet?query=q%3D*%3A*%0D%0Afq%3Ddocument_category%3Aannotation%0D%0Afq%3Dsource%3A%22TAIR%22%0D%0Afq%3Devidence_type%3A%22IEA%22%0D%0A&mirror=amigo_2_local_default

this doesn't seem like a facet query - the docs say it returns counts

**Comment by kltm** [comment]
Huh. I wonder if it was something else before.
And wow, that wiki page is dated... :disappointed:

**Comment by kltm** [comment]
Updated wiki a little bit, should now work on 2.3.x labs machines (i.e. amigo2/tomodachi).
