### ISSUE TITLE
Download button in goose always yields empty file

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#212]
From http://jira.geneontology.org/browse/GO-863

Example:

http://amigo.geneontology.org/goose?query=SELECT+*+FROM+term+INNER+JOIN+term_synonym+ON+%28term.id%3Dterm_synonym.term_id%29%0D%0A+WHERE+term_synonym+LIKE+%27protein+biosynth%25%27%3B%0D%0A&mirror=ebi&limit=1000

**Comment by cmungall** [comment]
Visualize link also doesn't work

**Comment by kltm** [comment]
Ugh. The link works, as well as visualize for me...

**Comment by kltm** [comment]
To clarify, on the given link, (re-)querying, download, and visualize all seem to work as advertised on the production site.

**Comment by kltm** [comment]
Sorry, got the 0 byte download problem now.

**Comment by kltm** [comment]
@kkarra and @stuartmiyasato , could you at some point roll this fix out (coordinating with rama and @mdolanme as necessary)? It is technically just a template variable change, so no big deal.

@mdolanme , ideally we'd be able to add a unit test for this issue.

**Comment by kltm** [comment]
@cmungall I was unable to duplicate any issues with visualize on the 2.2.x branch. Can you confirm the steps or come and show me? If so, it's its own bug and we can create a new ticket.

**Comment by cmungall** [comment]
May have been user error on my part. visualize works for me now

**Comment by kkarra** [comment]
Deployed fix below to production. https://github.com/geneontology/amigo/commit/a0dc8c72f8d2b3bea19229fe30219d8c446e14b0
Download file has contents and visualize link works (may have always worked)

**Comment by kltm** [comment]
@kkarra Great--thank you!
