### ISSUE TITLE
Possible XSS vulnerability in search interface

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#214]
From @stuartmiyasato:
```
A Cross-Site Scripting (XSS) vulnerability was reported on your website:
https://www.xssposed.org/incidents/65911/

```
And so on.

This is very much like the old AmiGO link issues that we had, and probably has the same solution (turn on the escaping in TemplateToolkit, and in the end disallow anything that looks like a URL).

This immediately affects the medial search, but may have implications elsewhere.

While this is marked as a show stopper, it is not a direct security issue for ourselves, rather random users getting pwned using our site as a vector.

**Comment by kltm** [comment]
@stuartmiyasato and @kkarra 
I've gotten a quick fix in for the vulnerable points in AmiGO on master and 2.2.x. This was a super simple template fix. Since this issue has been publicly disclosed, getting the fix into production sooner rather than later would be good.

AFAIK, this kind of thing should not affect the direct JS GOlr searches the same way as all input is going through a couple of transformation objects first that should pretty much cleanse it (although I have not fully picked it apart yet, so there may well be a way to worm one's way through it).

**Comment by stuartmiyasato** [comment]
@kkarra is out of the office today and tomorrow, and I am going to be in meetings for probably the rest of the day.  I'll try to push out the change either later tonight or sometime tomorrow.

**Comment by kltm** [comment]
No problem--it should be easy: just a couple of lines in a couple of temples. Again, not a security issue for *us* per se.

(and just for future searching, I'm adding: escape escaping filter html)

**Comment by stuartmiyasato** [comment]
@kkarra :  I've gotten tied up with other stuff and haven't had a chance to get to this.  Do you think you can put this fix into production?

**Comment by kkarra** [comment]
Sure. I  just saw this email. I will do it later today.

**Comment by kkarra** [comment]
fix is in production now. I have no way of checking. I am guessing Stuart should stop seeing those messages wherever it is that he saw it. Closing for now, reopen if the issue persists..

**Comment by kltm** [comment]
The test URL is available in the initial link:
```
http://amigo.geneontology.org/amigo/medial_search?q=%3Cimg+src%3Dx+onerror%3Dprompt%28%2FXSSPOSED%2F%29%3E
```
It seems to pass now.
