### ISSUE TITLE
More concise display of synonyms

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#218]
While I'm at it...

Often the synonyms take up a HUGE amount of the display when you land on a page

This is by no means a particularly bad example,
http://amigo.geneontology.org/amigo/term/GO:0004674

Could we

A, Hide alt GO IDs? (less useful)
and either
B, Make the display linear, comma separated (or collapsed). 
or  collapse them to show a couple with a more....link?

The display of synonyms, although required, is less critical once you are on the correct page.
You might need to be able to see them, but its unlikely to be you main interest. Often it is all that you see when you arrive.

**Comment by cmungall** [comment]
+1

**Comment by cmungall** [comment]
@hdietze to advise on alt_ids and coming changes to ontology policy re obsoletes

**Comment by kltm** [comment]
IIRC, we also have different types of synonyms that we'd like to be able to handle--we're currently just grouping them all in a general synonym pile.

**Comment by cmungall** [comment]
We can punt the synonym scopes, types and provenance to after 2.3, this will fall naturally out of #58. This is super-useful for the ontology group, but we have other ways of getting it, and not of immense use to general amigo users.

**Comment by cmungall** [comment]
Reopening, afraid this doesn't count as more concise:
http://amigo2.berkeleybop.org/amigo/term/GO:1903869
not useful!

I had in mind listing first `N`, and then doing the [more] button to list them all

Arbitrary first N is fine, but a better algorithm is to use provenance info but this depends on something like #58

**Comment by kltm** [comment]
Good example; fix was implementing first of part B in https://github.com/geneontology/amigo/issues/218#issuecomment-136175462
