### ISSUE TITLE
Display all edges in go-plus, not just the graph visualization subset

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#220]
From annotation call 2015-07-28 with @dosumis 

Relations such as [RO:0002315](http://purl.obolibrary.org/obo/RO_0002315) results-in-acquisition-of-features-of from go-plus are invisible in AmiGO

They should remain invisible for the purposes of most graph and hierarchy visualization, but should be shown in an infobox or similar to allow traversal.

For example
http://amigo.geneontology.org/amigo/term/GO:1904238

should have a link to
http://amigo.geneontology.org/amigo/term/CL:0000669

(TBD: where? in the Term Info section. Should be in "Ancestors and Children" tab, which is a table. Should probably NOT go in graph views, inferred tree views)

Also a reciprocal link should be present

**Comment by kltm** [comment]
Would these be of general interest, or just for the experts/curators? If the latter, would it make sense just to have one of the labs loads be /everything/, with the production (and the other head) loading the reduced version?

**Comment by cmungall** [comment]
Could be considered an advanced feature but *not* restricted to curators/GOC members.

There is no need to load anything beyond go-plus, it's purely a UI change that is required

**Comment by jaiswalp** [comment]
Any traction on this. Planteome group feels it is important to show these relations soon on the browser.

**Comment by kltm** [comment]
@cmungall So the action here then is to have a new field set (e.g. user_defined_closure_*) for this information, plus using that for the table (instead of/in addition to) the current set?

**Comment by cmungall** [comment]
No new closures required here. In general we may want additional closures, but these should be named for the name of the inferred relation in RO (e.g. a develops_from closure). The union of all such closures can easily be shared across all golrs, whether planteome, go, etc.

But that's not what this ticket is about. This ticket is about having the *direct* parents and children queryable from the API, which as I understand is best implemented in golr as a single new field called something like 'immediate-surrounding-graph' or similar which is a bbop-json graph blob with all direct edges incoming and outgoing from the focus node.

This can then be used to show parents/children, e.g. in the TermInfo display. Consult OLS-beta or Desktop-phenote TermInfo for ideal way for this to look.

**Comment by kltm** [comment]
Sorry, yes, this one always slips away from me for some reason.

I'm a little unclear how this would be from just loading all necessary relations into  ont-config.yaml's topology_graph_json? Would the issue with that be that simply having the whole graph in there be too large for the closure? If so, then yes, a new field would be called "neighborhood_graph_json" (or some other "_graph_json"). We could start on that fairly easily since Planteome is tracking the master branch.

**Comment by cmungall** [comment]
I'm not sure what you're suggesting.

If the suggestion is to extend the TopG for a class `C` to also include *any* direct edge `C R D`, regardless of R, then I think this should be fine. 

OTOH if the suggestion is to extend the TopG tfor a call `C` to include edges to nodes traversable by any series of relationship types, then this will explode.

Having a new json would also be fine. But I might tend towards bundling the direct edges into the existing TopG, provided that doesn't break anything.

**Comment by kltm** [comment]
Okay, so the second.

The action item here then is to: 1) add a new field (maybe neighborhood_graph_json) to ont-config.yaml and 2) populate it with a new graph function that gets all real single-step edges.

**Comment by kltm** [comment]
Tagging on @hdietze so there he has a heads-up--this is the all-edge neighbourhood field that I mentioned today.

**Comment by hdietze** [comment]
owltools has now a new method `getNeighbors`

**Comment by kltm** [comment]
This will depend on threading through berkeleybop/bbop-graph#3.
@hdietze is also working on better defining limited methods--from discussion, we'll be needing two fields loaded: the full graph and the *possibly* edge limited graph; we'd always graph the first, see if it was limited, and give the user the option to see the larger one (which could possibly be too big to load under normal circumstances).

**Comment by kltm** [comment]
Upstream graph metadata fixes in, but still need support in upstream JSON loaders (bbop-graph and bbop-graph-noctua),

**Comment by kltm** [comment]
This is now a perl template variable and supported by the JS graph stack. It requires a re-indexing to pull through, but should not crash without it.

**Comment by kltm** [comment]
It is currently pulled through in the [Neighborhood] tab, which is a replacement for the [Ancestors & children] tab.

**Comment by cmungall** [comment]
just placing this here for future reference.

the way the OLS displays this is useful. We see the closure over the traversal relations (is_a, part_of, ...) in a standard tree view (or could be graph view). The complete set of direct parents and children over all relations (e.g. participates in, as well as is_a, part_of) is shown in a distinct box.

http://www.ebi.ac.uk/ols/ontologies/po/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPO_0025405
