### ISSUE TITLE
Add a page for relations

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#221]
cc @dosumis 

Annotators have requested a page for relations, e.g.
http://amigo.geneontology.org/amigo/term/RO:0002315

This would be largely the same as existing class page (id, label, syns) etc. We can also show the subPropertyOf hierarchy etc (from the amigo and golr pov, just another graph, [like the one in protein2go](http://www.ebi.ac.uk/QuickGO/AnnotationExtensionRelations.html) )

Annotators would like a usage tab, which would show

 1. uses of this relation in the ontology (classes)
 2. uses of the relation in annotation extensions (associations)
 3. uses of the relation in lego models (would be nice to see visuals for the edges)

This part will require an addition to golr

UPDATE: it would be easy to power these by the biolink API

UPDATE:

@dosumis made a nice gonuts-like system whereby arbitrary markdown could be combined with markdown created from the rbox axioms: https://github.com/geneontology/annotation_extensions/blob/master/doc/results_in_morphogenesis_of.md

This is covered more generically in #421

**Comment by kltm** [comment]
If overloading was allowed, this could probably be added with few additional fields.

**Comment by pgaudet** [comment]
http://wiki.geneontology.org/index.php/Annotation#Annotation_Relations
