### ISSUE TITLE
IKR is not an option when filtering by evidence type

### ISSUE THREAD

**Issue by selewis** [geneontology/amigo#222]
Looking for non-PANTHER IKR annotations to GO:0000122 and at least some should be there (or at least the PANTHER ones should

**Comment by kltm** [comment]
Could you give me the chain of data such that you'd expect this to show up in AmiGO? Tagging on @hdietze just in case this is an evidence closure issue in the loader.

**Comment by kltm** [comment]
Note: IRK = Inferred from Key Residues

**Comment by selewis** [comment]
IRK :)

but really IKR

**Comment by selewis** [comment]
I am investigating an annotation of that was in an old paint GAF (being
touched up):
UniProtKB    P14923    JUP    NOT|not    GO:0000122    PAINT_REF:0023315
IKR
PANTHER:PTN000593411|RGD:620412|UniProtKB:P14923|UniProtKB:Q8SPJ1|UniProtKB:P14923
P        CTNNG|DP3|PLAK_HUMAN    protein    taxon:9606    20100818
RefGenome

Problem is that the corresponding annotation to an ancestral node is not
present. I was double-checking that it wasn't an independently made IKR
(other groups do use it). It appears that things are fine on my end (the
annotation is no longer relevant as a NOT or otherwise because the
ancestral node is now no longer a member of the family), but in the
meantime it would be good to be able to find all IKR annotations that don't
come from PAINT.

**Comment by kltm** [comment]
Which GAFs should these be in? If there is a GAF that could/should be added to the production load, that's fine (as you contact the production server for this kind of thing). Otherwise, some alternative route to get this information will have to be found. Tagging on @cmungall as we're talking about production data selection.

**Comment by selewis** [comment]
I don't think it is a production issue, but...

If the only choices for Evidence Type in AmiGO are those used for
annotation to that term (as opposed to every existing Evidence Type which I
had assumed) then my question is answered.

It is a production issue only in the sense that we should soon (this
month?) begin loading the PAINT GAF files directly and excluding them from
the MOD provided GAFs. This is on my plate to do.

-S

**Comment by selewis** [comment]
Skype is this is still unclear.

**Comment by kltm** [comment]
Suzi--it is the former: the only evidence types you can filter on are the ones that are relevant (exist in the closures) for the annotations for that term.
