### ISSUE TITLE
Add new model annotation schema and pages, remove legacy (redo complex annotations)

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#226]
This meant to encompass the removal of the legacy complex annotation pages and the addition of the new model annotation pages. A lot of work has been done since that first attempt and not much can be saved.

@cmungall has already added a new model_annotation.config.yaml file, @hdietze will take care of the loading bits (and mercifully take ComplexAnnotationDocumentLoader out of its misery).

**Comment by cmungall** [comment]
We left a few, for possible future extensions

These should all have a standard closure quad

 * affects
 * affected_by
 * during
 * subfunction
 * substrate

**Comment by kltm** [comment]
The initial Makefile and schema changes, along with necessary changes in the OWLTools loader (work and feedback to @hdietze) have been completed. We now need to:

1. Finish the redo of complex_annotations as model_annotations
2. Coordinate the update of tomodachi in a non-disruptive way.

**Comment by kltm** [comment]
Number two is now completed, number one is done for all but the visualizations.

Also, we'll have to come back and change some of the URLs once the meeting is over--there is a little bit there to point at noctua-dev temporarily.

**Comment by cmungall** [comment]
Link on landing page is not correct, still points to old. I can fix.

**Comment by kltm** [comment]
@cmungall , I manually linked it with a commit comment, but be careful with the links: you got the wrong repo and I don't think there really a way to undo it without messing with a whole chain of trees; this will show up again as tagged when the noctua repo reaches 226.

**Comment by kltm** [comment]
Rolled out.

**Comment by cmungall** [comment]
oops sorry
