### ISSUE TITLE
Term Page now shows up as title and header for all classes

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#235]
http://amigo2-test.stanford.edu/amigo/term/GO:0022008 

cc @kkarra

**Comment by kltm** [comment]
Not sure why I didn't get an auto-close on this...

**Comment by cmungall** [comment]
s/Closes/Fixes/
?

**Comment by kltm** [comment]
had "fixes #235" in a commit, but maybe that doesn't work on a branch...?
https://github.com/geneontology/amigo/commit/5f84893a7489a1977cefd1c42b26c0673ef0b006
