### ISSUE TITLE
Add a 'models' tab onto term and entity pages

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#237]
Example:
http://amigo2.berkeleybop.org/amigo/term/GO:0006096

Should have a tab that shows something like the pinned filter in the attached image

<img width="1397" alt="screen shot 2015-08-28 at 2 08 50 pm" src="https://cloud.githubusercontent.com/assets/50745/9557136/6339bd92-4d8e-11e5-8c43-629b84a49b30.png">

Depending on the timing of 2.4, we may opt to make this hidden in production or punt to 2.5 (there are dependencies as yet lacking tickets, such as changing production makefile to load noctua models)

**Comment by cmungall** [comment]
Pinning model search is a minimal requirement, but we may want to do more.

Imagine we have 3 different models each involving the process GO:0007224 'smoothened signaling pathway'. In addition to seeing all annotons that are part of this (via pinning as described above), we may also want to show a gallery of the 3 models (see https://github.com/geneontology/noctua/issues/221).

We may also want to make the union of all edges coming into or out of GO:0007224 in the 3 models navigable. Formally these are SOME-SOME axioms rather than the usual ALL-SOME axioms. This may inform the solution adopted for #220

**Comment by kltm** [comment]
From @ukemi

```
but it would be really cool if when an annotation is shown in the AMIGO2
results, you could click on it and go to a visualization of the Noctua
model from which it was derived. It would also be cool to show the
relation between the gene product and the GO term on the annotation result
in AmiGO2. Could replace the qualifier field, but I don¹t know how to make
qualified annotations in Noctua.

GeneX enables MF#1
GeneX enables part of BP#1
GeneX enables positive regulation of BP#2
GeneX enables direct activation of MF#2
GeneX causally upstream of BP#3
GeneX does not enable MF#4
GeneX acts in CC#1
GeneX enables positive regulation in CC#2 (see how the loss of model
information becomes huge here?)
```

**Comment by cmungall** [comment]
> but it would be really cool if when an annotation is shown in the AMIGO2 results, you could click on it and go to a visualization of the Noctua model from which it was derived

This ticket is primarily about putting a models/annotons tab under the term page, where there should be a clear path to see the full model.

This request seems more about when you view the lossy annotations; it would still be good to have a path from here to the model view

> It would also be cool to show the relation between the gene product and the GO term on the annotation result in AmiGO2. Could replace the qualifier field, but I don¹t know how to make qualified annotations in Noctua

Not following. In noctua you have control over all relationship types, there is no qualified hack as such

**Comment by kltm** [comment]
Closed in preference to new project https://github.com/geneontology/project-management/issues/66
