### ISSUE TITLE
Direct annotation columns should removed from search/bioentity page

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#238]
I questioned the availability of the "direct annotation" column (and its contents) , on the  "term" page, when you follow the link from here:
http://amigo.geneontology.org/amigo/search/bioentity?q=*:*&fq=regulates_closure:%22GO:0007049%22&sfq=document_category:%22bioentity%22

to "all genes gene products" 

Chris now agrees that it is better not to have this column in this context.

Reasons:
Often too many terms in the column  to read.
You therefore need to expand with a click to see the entire list of annotated terms.
There is a better option, also one click away. If you go to the gene page, you see all of the annotations, but here you get all of the  additional relevant data (source, evidence etc)

http://amigo.geneontology.org/amigo/search/bioentity?q=*:*&fq=regulates_closure:%22GO:0007049%22&sfq=document_category:%22bioentity%22

**Comment by ValWood** [comment]
Oddly
via this link (also to a GO term)
http://amigo.geneontology.org/amigo/term/GO:0004674
the 'direct annotation' column is used differently. it only list the terms which are descendants of GO:0004674 (i.e from which the GO:0004674 annotation is derived).
In this context the column makes sense to me.

The other view shows *every* term a gene is annotated to. I don't fully understand why these 2 pages show different columns. They are both displaying lists of gene products annotated to GO terms.

**Comment by kltm** [comment]
@ValWood titles should be meaningful--changing to what I get out of this item.

**Comment by cmungall** [comment]
Changed the title again - we certainly want to keep this column on other pages. The point is that it is not hugely informative on search/bioentity pages, for the reasons Val mentions. The user may as well click on the entity to see everything

**Comment by kltm** [comment]
@ValWood, @cmungall the two views are for different things: the first is for bioentities, so they may have multiple direct annotations; the second is for the annotations themselves, which only have one.

**Comment by kltm** [comment]
@cmungall ah, got it!
