### ISSUE TITLE
Boost human followed by MODs in search prioritization

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#239]
Trying to find beta catenin in human, nearly impossible; e.g.

http://amigo2-test.stanford.edu/amigo/search/bioentity?q=CTNNB1

Ideally human would be first followed by MODs. This could be a configuration, or alternatively scoring each gene by number of experimental annotations would be a nice generic way to do it. This would be an easy field for @hdietze to add when loading.

**Comment by cmungall** [comment]
To be fair one reason this is hard to find is due to this: #240

**Comment by kltm** [comment]
What this would boil down to would be two new fields, say: search_bin_priority_one and search_bin_priority_two. Human genes would populate the first one, MODs get the second, everybody else gets none.

The search would then be boosted on those two fields, say: search_bin_priority_one^4.0 search_bin_priority_two^2.0.

**Comment by kltm** [comment]
This is essentially the same as #102.

Tangentially related to berkeleybop/bbop-js#16.

**Comment by kltm** [comment]
Really, a refinement of the changes there. Will continue over there.
