### ISSUE TITLE
Generate reports and barcharts from golr

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#242]
Current:
http://geneontology.org/page/current-go-statistics

Given a little time, we could just abandon the images and make some nice
web-only charts using D3 (http://bl.ocks.org/mbostock/3886208) or
flotcharts (http://www.flotcharts.org/flot/examples/stacking/index.html)
or something.

**Comment by cmungall** [comment]
I see this is in the 2.4 milestone. Which framework did you decide in the end?

**Comment by cmungall** [comment]
I many ways, the count of experimental annotations is most meaningful. It's not hard to boost automatic annotations. Would it therefore make sense to always make the experimental block always show up at the bottom of the stack, to make visual alignment easier?

**Comment by cmungall** [comment]
- [ ] Annotations by Species by Aspect.  Like the one that is already there for Annotations by Source by Aspect, but by Species (for the same species listed in the current one for Annotations by Species). 
 - [ ] Curation of experimental annotations: publications.  Num unique publications (for all EXP annotations only) by Assigned by.  This shows how many publications have been curated by each group, and is probably the best metric for literature curation effort by the different contributing groups.
 - [ ]  Curation of experimental annotations: annotations/publication.  Num annotations (EXP only) / Num unique publications, by Assigned by, stacked bars for each aspect.   Gives an idea of how different groups annotate relative to each other (over- or under-annotation, or focus on high-throughput papers).
 - [ ] Curation of homology annotations. Num annotations (for all manual similarity evidence) by Assigned by, stacked bars for each aspect. Shows who is doing manual curation of inferred annotations.
 - [ ] Annotations by different IEA methods. Num annotations (IEA only, same limited list of genomes as in #1) by With field (i.e. method), stacked bars for each aspect. Shows which methods are used to provide computational annotations.

**Comment by kltm** [comment]
The go-site link, and graphics choice: geneontology/go-site#149
Implementation here.

**Comment by kltm** [comment]
http://tomodachi.berkeleybop.org/amigo/base_statistics

**Comment by kltm** [comment]
Okay, more-or-less have the replacement framework in place. Now let's looks at these new ones...

**Comment by kltm** [comment]
@cmungall has bumped down priority here, so I'm going to close this out and let people add new items that they might want to a wishlist item.
