### ISSUE TITLE
URL for SGD reference 

### ISSUE THREAD

**Issue by rbalakri** [geneontology/amigo#243]
HI,

The URL for SGD_reference (not gene) is not substituting the SGDID in the 'example_is' slot. Do we need to do something at SGD for this?
For example, click on the SGD_reference 'SGD_REF:S000148669' from the annotation table on this page-
http://amigo.geneontology.org/amigo/gene_product/SGD:S000003723
it takes you here-
http://www.yeastgenome.org/reference/[example_is]/overview

Thanks,
Rama

**Comment by kltm** [comment]
Rama,

This is actually a issue in the upstream data file db-xrefs.yaml at geneontology/go-site. Looking through the history, on March 13, it looks like you changed "example_id" to "example_is", creating a problem with the forwarding:

https://github.com/geneontology/go-site/commit/772f58f291ff340d091466119d086d62355bfdb1

You should fix that and then request that production updates/refreshes amigo. If you're unsure how to do this, create a new ticket on the go-site tracker with your message and this one.

Cheers,

-Seth

**Comment by rbalakri** [comment]
Seth,

I updated the 'yaml' file. 

Rama
