### ISSUE TITLE
Gene products as titles do not show up on gene product pages

### ISSUE THREAD

**Issue by rbalakri** [geneontology/amigo#244]
When I search for a gene name (cdc2 or Tem1) there is no title in amigo2-test. 
Compare:
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPBC11B10.09
http://amigo2-test.stanford.edu/amigo/gene_product/PomBase:SPBC11B10.09

Rama

**Comment by kltm** [comment]
Good catch; no end to the fun with titles this time around. I'll put the fix in on Tuesday when I get back.

**Comment by kltm** [comment]
Grump; I'd fix it right now real fast, but I'm effectively prevented from doing local development by #241.
