### ISSUE TITLE
Create a more programmatic system for loading (Makefile and env vars are not cutting it)

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#246]
While the Makefiles are simple and nice, we run into a rather irritating set of problems with the coordination of loads across different installations.

The ideal solution would provide a way of easily running loads with YAML files (local/remote?) being used to define the load (GAF, ontology, etc).

Given the tendency towards node/npm in AmiGO, the likely solution would be gulpfiles.

**Comment by cmungall** [comment]
I like yaml but whatever you think is best

**Comment by kltm** [comment]
The stated plan would be gulpfiles (programmatic JS) would be using gulpfiles; or are you referring to something else?

**Comment by kltm** [comment]
...actually, playing around, it might be really nice to have all of the meta-information stored in the amigo.yaml files as well. We currently have things like mirrors, rte, and loads all stored separately. It might be nice to have a single conf defining the entire amigo instance. While this would mean that there is some repetition in definition of things like GAFs, it would make it instantly apparent who is loading what and keep them individualized. Something to be said for both ways.

**Comment by kltm** [comment]
Since we're going to restart 2.3 anyways, and since downstreams (specifically Stanford) don't seem to really make much use of the Makefiles, let's go ahead and do this now rather than later and make single config file -> all installation info. This would also make tracking production easier.

**Comment by kltm** [comment]
With final discussions with @hdietze and @cmungall, new loading system is probably done. I'll try and tag on further fixes.
