### ISSUE TITLE
Add additional goal fields for additional OWL expressivity

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#249]
Note: a separate ticket will be created for the population of these. Individual fields vary from low to medium priority.

Some of these fields will make use of a owl-in-json representation (cc @dosumis), TBD, most likely extending the existing Minerva serialization (to be moved into own library? owl-json?) and thus reuse https://github.com/berkeleybop/class-expression/ .

## Association Documents

 * Add `annotation_extension_owl_json` - this will be a non-lossy representation of conjunctions and disjunctions in c16
 * Add `annotation_relation` - this is equivalent to the relation field in GPAD. OWLTools code already exists for inferring this
 * We also need something to accurately represents conjs+disjs in the WITH column in gaf2.1

## ontology_class Documents

 * Add `equivalent_class_expressions_json` - for any class document `C` this will contain `json(CE)` for all axioms of form `EquivalentClasses(C ... CE ....)`. Note id_label map should be complete for all values here
 * Add `disjoint_classes` [populating this is low priority]

**Comment by kltm** [comment]
* annotation_relation: is this a single ID, or something else?
* disjoint_classes: looks muiltiple and not a closure, so then this would be unpacked to disjoint_class_list and disjoint_class_list_label?

**Comment by cmungall** [comment]
* annotation_relation is a single ID
 * disjoint_classes. Correct, list, list_label, no closure

**Comment by kltm** [comment]
does annotation_relation need a corresponding label?
