### ISSUE TITLE
Loaded PAINT annotations appear to be incorrect

### ISSUE THREAD

**Issue by rbalakri** [geneontology/amigo#253]
Hi,

I'd like to clarify a couple of things about the PAINT annotation.

First, I thought that for databases where there was a designated authority annotation was not imported into the GO database unless it came in via the DB authority submitting GAF. However, today I noticed that the pombe PAINT GO data is already visible in AmiGO?

As we don't yet import the data into PomBase (we are waiting for reported errors to be fixed, which affected 50% of the annotations that were checked). This means that currently the data visible in Amigo and PomBase is different, we have always attempted to keep these 2 datasets fully aligned otherwise people get confused when performing enrichments and then referring to PomBase gene pages.

For other external GO data (i.e via F-P links, or InterPro mappings) we are able to apply our own internal QC checks and filter out errors. We would like to be able to to do the same with PAINT data. Otherwise, we will begin to accumulate many new annotation errors (which I have spent the past years cleaning up !).

Second, I notice that the PAINT NOT annotations are included in the PAINT GAF file. These annotations are a bit strange because we would normally only make a NOT annotation ifi we expected a GP to have a particular GO annotation, and it turned out not to. We use them very infrequently. The PAINT NOTs appear to be quite different as they are often applied to gene products where a particular annotation would never be expected in the first place. These NOT annotations seem as though they should be internal to PAINT (i.e they are a prompt to the PAINT family editor rather than a useful annotation in the GO database).

Thoughts?

Val

**Comment by kltm** [comment]
@rbalakri could you clarify the actionable item here, and fix the title to reflect that?

**Comment by rbalakri** [comment]
Looks like AmiGO is loading PAINT annotations that are not in the MOD specific GAF file. For e.g. any PAINT annotation for pombe has to come from the pombeGAF only.
Can this be resolved?

Rama

**Comment by kltm** [comment]
So is the issue that AmiGO (http://amigo.geneontology.org/amigo/load_details) is loading the PAINT pre-submission (http://www.geneontology.org/gene-associations/submission/paint/pre-submission/gene_association.paint_other.gaf), or is it happening before that?

**Comment by rbalakri** [comment]
I think AmiGO is loading from the pre-submission directory (although I haven't done a thorough check to see if it true for all GAF files).

r

**Comment by kltm** [comment]
AmiGO is loading: http://www.geneontology.org/gene-associations/submission/paint/pre-submission/gene_association.paint_other.gaf, should this not be the case?

**Comment by rbalakri** [comment]
Seth,
Loading the 'other' file should be okay. But this "other" file contains annotations for pombe (taxon:4896). May be the script that is producing this file is not doing the right thing?
Rama

**Comment by kltm** [comment]
Okay, so the issue is data: the loaded PAINT file contains annotations that should actually be represented in another GAF. While the effects are seen in AmiGO, this is actually an upstream data issue, yes? Tagging on @cmungall and @selewis to try and figure out what exactly is happening here.

**Comment by rbalakri** [comment]
Can you also tag Val on this issue?
Thanks,
Rama

**Comment by kltm** [comment]
She not in the amigo group so no autocomplete. If you look her up elsewhere you can just add her in with @USERNAME.

**Comment by ValWood** [comment]
I'm on here.....

**Comment by kltm** [comment]
Looks like it might be an upstream data issue; further tracking here: geneontology/touchup#23
