### ISSUE TITLE
The perl graph traversal, and possibly the javascript one as well, does not seem to be cycle-safe

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#254]
After loading (IIRC) only go-lego.owl, attempting to visit http://localhost:9999/amigo/term/MP:0004336 caused perl to consume all the RAM on my machine, needing manual intervention to prevent it.

The (now obvious, thank @hdietze) is that there is a cycle in the graph that the perl graph traversal bits (and likely the JS as well, since they are based on the perl) are not catching. I had thought that my coloring stuff done to prevent this, but this would seem to be proof otherwise.

Have already touched bases with @cmungall and @hdietze about this.

While this is a somewhat serious "B", it seems to be unlikely to be triggered in most cases, and is mostly an issue for the server, not the client. Also, since this has probably been an issue for a while and has gone unnoticed, I'm not going to completely freak out.

**Comment by kltm** [comment]
It's also worth checking that it may be specific to the bracket layout functions.

**Comment by kltm** [comment]
Standard graph layout works fine:

http://localhost:9999/visualize?inline=false&term_data=MP%3A0004336&format=png&mode=amigo&term_data_type=string

So this may well be just a bracket issue.

**Comment by kltm** [comment]
Works fine as well with manual ID insertion: http://localhost:9999/amigo/free_browse

Examining these though, it looks like an issue in the interaction between UPHENO:0001002 and HP:0000118. So barely an AmiGO issue outside of the perl (and maybe JS) bracket layout.

**Comment by cmungall** [comment]
*GOlr* should make no assumptions about the incoming OWL, other than (a) it is syntactically valid OWL and (b) it is coherent (I believe we have a coherency check, @hdietze can confirm). i.e. there should be no assumptions that no two classes are not equivalent (which is the same as SubClassOf cycles).

*AmiGO* can make the assumptions that the graph formed from the ontology using the configured set of object properties is an OBO-Basic graph:
http://owlcollab.github.io/oboformat/doc/obo-syntax.html#6.1

The current issue came up because we were loading a GOlr instance that was intended purely for supporting noctua/minerva is also used to drive an amigo.

**Comment by kltm** [comment]
The JS bails nicely on too much recursion (also confirming that it's an algorithm issue in the layout that affect both perl and JS), and drops out in the graph's get_parent_nodes(nb_id, pred_id) function, which looks like something in a local layout traversal like bracket (as opposed to one of the sugiyama ones that shortest path comb-down)...

This leaves the solution as either policy (that shouldn't happen--data bug) or code (global coloration for local layouts). Things should not crash on bad data, even if it shouldn't be there, so I'll keep this as a very low priority "B".

**Comment by kltm** [comment]
Note that this has come up again and has been rediscovered as an issue for the perl code for `GO:0006939` (do *not* look at this in AmiGO for obvious reasons). This has again been traced at least to the climber.
I first want to confirm with @cmungall that a cycle is present around there and that it is correct.

**Comment by kltm** [comment]
```perl
    $node_distance->{$obj_acc} = $self->max_distance($obj_acc);
    #...
    my $climb_counts = $self->_max_info_climber($self->{ACG_ACC});
```

Doing a sample of 1364 steps, we have the following distribution:

```
     57 BFO:0000002
     57 BFO:0000003
     57 BFO:0000004
     57 BFO:0000015
     57 BFO:0000040
     56 CARO:0000000
     57 CARO:0000003
     57 CARO:0000006
     57 CARO:0030000
     56 GO:0003008
     57 GO:0003012
     28 GO:0006936
     57 GO:0008150
     57 GO:0032501
     29 GO:0040011
     56 UBERON:0000061
     29 UBERON:0000383
     57 UBERON:0000465
     57 UBERON:0000467
     57 UBERON:0000468
     28 UBERON:0000479
     28 UBERON:0001015
     57 UBERON:0001062
     28 UBERON:0002204
     29 UBERON:0002385
     28 UBERON:0004120
     57 UBERON:0010000
     57 UBERON:0011216
```

tagging @cmungall

**Comment by kltm** [comment]
A hundred lines of walk:
```
GO:0032501
UBERON:0000383
GO:0040011
UBERON:0011216
GO:0008150
CARO:0000003
BFO:0000003
UBERON:0002385
UBERON:0000465
UBERON:0010000
BFO:0000002
BFO:0000004
CARO:0000006
UBERON:0001062
UBERON:0000467
UBERON:0000468
BFO:0000040
BFO:0000015
CARO:0030000
GO:0003012
BFO:0000040
GO:0003012
UBERON:0002204
BFO:0000015
CARO:0030000
BFO:0000004
UBERON:0004120
GO:0006936
UBERON:0001062
UBERON:0000467
UBERON:0000468
CARO:0000006
BFO:0000003
UBERON:0000465
UBERON:0000479
UBERON:0001015
UBERON:0010000
BFO:0000002
GO:0003008
CARO:0000000
GO:0032501
UBERON:0000061
UBERON:0011216
GO:0008150
CARO:0000003
CARO:0030000
BFO:0000015
GO:0003012
BFO:0000040
CARO:0000006
UBERON:0000467
UBERON:0000468
UBERON:0001062
BFO:0000004
BFO:0000002
UBERON:0010000
UBERON:0000465
BFO:0000003
UBERON:0002385
GO:0040011
UBERON:0000383
GO:0008150
CARO:0000003
UBERON:0011216
UBERON:0000061
GO:0032501
CARO:0000000
GO:0003008
BFO:0000040
CARO:0030000
UBERON:0002204
BFO:0000015
GO:0003012
GO:0006936
UBERON:0004120
BFO:0000004
CARO:0000006
UBERON:0000467
UBERON:0000468
UBERON:0001062
UBERON:0000465
BFO:0000003
BFO:0000002
UBERON:0010000
UBERON:0001015
UBERON:0000479
UBERON:0000061
GO:0032501
GO:0003008
CARO:0000000
CARO:0000003
GO:0008150
UBERON:0011216
CARO:0000003
GO:0008150
UBERON:0011216
GO:0040011
UBERON:0000383
CARO:0000000
GO:0032501
```

**Comment by kltm** [comment]
* order is alphabetical, as it is a grep/sort/uniq to get the count
* the perl code is what we have now and this code is causing problems now, so it needs to be fixed (which I believe I have already done, but am waiting for things to be less on fire before updating)
* it seems to be a problem with some kinds of cycles; any fix that removed cycles would fix this, but see above (i.e. I have an easy fix as it was likely a refactoring mistake on my part)

This is the code used in deciding how to "tab" elements for the neighborhood view, which requires a walk up from the bottom to get "distance" for the "tabbing".
