### ISSUE TITLE
odd search behavior

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#269]
When I search on a gene product ID (eg SPAC23A1.08c)
from here
http://amigo.geneontology.org/amigo

http://amigo2.berkeleybop.org/amigo/medial_search?q=SPAC23A1.08c

the result is under "general' rather than
Genes and gene products 
or
Associations

**Comment by ValWood** [comment]
Also the link from general takes me to PomBAse I can't seem to get to SPAC23A1.08c in Amigo...

**Comment by kltm** [comment]
This is essentially a restatement of #120, that ID parts are not loaded into most of the search indexes. There's an extra level of weirdness here though in that some of the "hidden" indexes are exposed in the backup system that is currently dealing with AmiGO traffic while production is down.

I'll add this as an example to that issues.

 http://amigo.geneontology.org/amigo/gene_product/PomBase:SPAC23A1.08c
