### ISSUE TITLE
Make default results "gene products" rather than annotations

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#270]
When I come to AmiGO and do a search on a term, like  "mitochondrion" I (and most users) am almost always interested in the number of gene products annotated to this term, not the number of annotations (which is arbitrary).

So I search on mitochondrion.
I get otal: 83996; showing 1-10
I assume this is gene products and start to apply my filters

pombe 1636. I know this is too many because  pombe has ~750 mitochondrial proteins. I realise I am searching annotations not gene products.  There is nothing which makes this clear so I don't think any user would have any way of knowing....

I MUCH preferred the old AmiGO where you specified upfront whether you were searching gene products are annotations. It was much clearer. If there has to be a default, it should be gene products (makes much more sense biologically). I'm sure this previously was the case?

(I have also seen users confused by the numbers because of  this in helpdesk tickets)

**Comment by cmungall** [comment]
Just to clarify, would you prefer

 1. That the right panel actually showed one line per association, but that the numbers (in the top of the panel AND in the facets) were for distinct gene/products
 2. That the right panel showed essentially just a list of gene/products (as you currently get when you click on "Link to all genes and gene products annotated to term X"; but with term info still at the top)
 3. That the right panel was less table-oriented and showed things in a more structured way; e.g. grouped by gene, and a row for every *relevant* association for that gene (with the facets counting genes not associations)

(2) would be the easiest to implement, it's just a switch in defaults, but we should be aiming towards what is best.

**Comment by kltm** [comment]
@ValWood, just to clarify here, the change that you want would look like:
* when a user does a search from the landing page,
* selects an term item from the dropdown,
* goes to the term page,
* instead of an annotation search like: http://amigo2.berkeleybop.org/amigo/search/annotation?q=*:*&fq=regulates_closure:%22GO:0005739%22&sfq=document_category:%22annotation%22
* the user should see a gp search like: http://amigo2.berkeleybop.org/amigo/search/bioentity?q=*:*&fq=regulates_closure:%22GO:0005739%22&sfq=document_category:%22bioentity%22
I believe that the current behaviour was by popular demand (or possible historical), so it would be a bit of a change. Easy to make, but it might surprise users.

**Comment by ValWood** [comment]
Proably you shouldn't make a major changes to this based on only my feedback, but it would be useful to have some focussed  user testing on this to see what people *think* they are looking at.
Myself, I only realise I am looking at annotations when I see  the same gene in multiple rows, but this isn't always obvious from the 10 entries you can see by default, or when I know the numbers are not what I expected.

- I don't remember the behaviour was ever by products (it would be good to know what influenced the change if it ever did search gene products by default)
- I doubt many users have figured out that they are seeing annotations and not gene products, because very few people would know what numbers to expect 

A better immediate  solution might be  keep the current display as the default but show both counts:
Total annotations: 83996;  Total gene products  51848 (instead of just "Total"), at least then everyone would have a better clue what they were looking at, but would not be a radical changes, and if people are usually interested in the gene product count, it would always be right there on the page...

**Comment by kltm** [comment]
Hm. Unfortunately, producing that effect in the current stack would actually be a bit of a trick. Once #104 is complete, we could make a new pager widget that did this, but before then it would be less disruptive to just make a complete switch.

A middle ground that could be added would be on annotation searches:

Total **annotations**: 83996;

and on gp searches:

Total **gene products** 51848;

**Comment by ValWood** [comment]
Seth I think that the "middle ground" would be good initially.   It would be great if the product count could be displayed in the longer term.

**Comment by kltm** [comment]
If you feel that is a workable solution, I'll close this out and make new tickets to that effect.

**Comment by ValWood** [comment]
sounds good.

**Comment by cmungall** [comment]
+1

on language did we decide annotations vs associations? The latter may be less ambiguous (some non-GOC people may think of the genes as being 'annotations'. I think 'associations' is less curator jargon and less prone to misintepretation)

**Comment by kltm** [comment]
Please feel free to clarify on #275.

**Comment by ValWood** [comment]
Associations- IIRC.
