### ISSUE TITLE
Free text filter is unobviously  "sticky"

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#271]
I filtered in Amigo using free text filtering "Dap3"

I removed the filter and filtered on taxon "S.cerevisiae"

The filter is still present, even though I removed it and the filters do not show that it is present.

**Comment by ValWood** [comment]
![free-text filter is sticky](https://cloud.githubusercontent.com/assets/7359272/10877026/3dd6cb32-813a-11e5-8c79-a0d4eaf2b7d9.jpg)

**Comment by ValWood** [comment]
I need to reload the page to remove

**Comment by kltm** [comment]
Yes, this is a case of that I've worked with this so long, it has been overlooked. The behaviour quirk here is this: the text search ignores anything less than three characters in most places, with the expectation that a user trying to clear the filter would use the [X] box in the upper right.

A better behaviour here would be that the widget clears the filter when there are less than three characters and the last input character was "delete". Or better, that a clear is done on a delete when that are three characters, if we want to not worry about a look-behind.
