### ISSUE TITLE
NOTs included in annotated gene products

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#272]
When I search on a term (e.g DNA recombination), and download results list, it includes
SPCC736.09c
SPAC30.03c
SPAC15E1.07c
SPCC24B10.14c

These are only annotated to "recombination" wth a NOT qualifier.  It is not obvious from the filter options or the results column, that NOT annotations are included.

I think NOT should be filtered out by default, with the option to include them if required?

**Comment by kltm** [comment]
Could you qualify the page you're working on and the exact process you're using to produce the download? Most term pages offer the "Qualifier" filter that would take care of this.

**Comment by ValWood** [comment]
http://amigo2.berkeleybop.org/amigo/search/bioentity?q=*:*&fq=regulates_closure:%22GO:0006310%22&sfq=document_category:%22bioentity%22

Gene products. There is no "qualifier filter" on this page because I am looking at gene products no annotations. However, if the only annotation is a NOT, they are not  actually annotated to the term at all....

At PomBase we display these on the gene pages
http://www.pombase.org/spombe/result/SPCC736.09c
but we exclude from counts of gene products annotated to the term

I think that is what a biologist would expect. Its confusing to retrieve the list of genes annotated to a term, only to find that many of the annotations are negative. Especially as you are not downloading the qualifier field using the download default  (I used the default which is Acc and Label). I only figured it out when I looked at the intersect   to figure out the differences.

**Comment by kltm** [comment]
I think we could use @cmungall here. An issue here is that there is no single GAF line that corresponds to a line in the table that you see in the search (or are able to download), but rather it is a weak sum of the information collected about a bioentity. In this view, there is no "NOT" to speak of since there is no particular annotation under discussion.

**Comment by cmungall** [comment]
@ValWood is correct. This is a bug. They simply should not be in the bioentity closure. They make sense in the association closure since the qualifier is a property of the association

**Comment by kltm** [comment]
@cmungall the "showtopper" tag implies pulling the plug until solved, but there is no clear action here that isn't upstream. Should we pull the backup amigo at this point?

**Comment by cmungall** [comment]
I think we can get a golr load fix out soon?

**Comment by kltm** [comment]
Okay to verify, the idea is that when the owltools fix is in place (provided by @hdietze?), we'll bake that into the amigo branches and set the load to go, accepting a five hour outage, during which time we'll redirect to a message stating that we're having an emergency rebuild?

**Comment by hdietze** [comment]
Pushed a fix in owltools, waiting for integration build to verify tests

**Comment by kltm** [comment]
Let me know when it lands. To verify, there should be nothing new in the owltools code that would prevent the amigo release branch (of owltools) from merging in master?

**Comment by hdietze** [comment]
Integration build passed.
I checked all the changes since the fork for amigo-2.3.x in owltools and they appear to be not problematic.

**Comment by kltm** [comment]
@cmungall, since there will be at least a five hour outage, I wanted to verify that I should go ahead. I think the easiest route would be to leave the AmiGO live, but add a very LARGE and RED warning message that it is being reloaded.

**Comment by kltm** [comment]
As well, it might make sense to make a more public announcement as well.

**Comment by kltm** [comment]
@hdietze, after a reload, the following still appears in the closure:
```
PomBase	SPCC736.09c	tfx1	not	GO:0000724	PMID:18062930	TAS		P	TRAX		protein	NCBITaxon:4896	20080829	PomBase	
```

**Comment by hdietze** [comment]
Okay, that needs further investigation. I'm not sure that we use/display the proper closures here or need some other mechanism.

**Comment by cmungall** [comment]
@kltm do you mean GO:0000724 appears in the closure for the bioentity document for SPCC736.09c?

I'm trying this on toaster:
```/solr/select?defType=edismax&q=bioentity:"PomBase:SPCC736.09c" AND document_category:"bioentity"&wt=json&indent=on```

but I don't see it (which indicates the fix worked)

**Comment by cmungall** [comment]
Things seem to work as expected on the user views

<img width="940" alt="screen shot 2015-11-03 at 9 19 32 am" src="https://cloud.githubusercontent.com/assets/50745/10915516/0f941af4-820c-11e5-8a19-1ecac436697f.png">
<img width="1427" alt="screen shot 2015-11-03 at 9 18 48 am" src="https://cloud.githubusercontent.com/assets/50745/10915517/0faba99e-820c-11e5-98d0-3b7aa17ac72d.png">
<img width="1436" alt="screen shot 2015-11-03 at 9 18 25 am" src="https://cloud.githubusercontent.com/assets/50745/10915518/0fcd0288-820c-11e5-90a2-6c289ede31c0.png">

**Comment by cmungall** [comment]
I have not tested this thoroughly but based on what I see so far I'm confident about closing this ticket, thanks everyone!

**Comment by kltm** [comment]
Okay, I'll take that. I was going off of Val's first comment--I read it as annotation download from term page.
