### ISSUE TITLE
Make it easier to search by PMIDs

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#285]
E.g.

 * add a grebe template
 * allow typing of PMID:nnnn into search field on annotation search (seems to tokenize too early now)
 * add PMID page (thought we had a separate ticket? can't find)

**Comment by kltm** [comment]
* Easy.
* There is another issue about stuff like this in here somewhere (related to #120 constellation). You can, however, apparently currently search for 25281747 and "PMID:25281747" in annotation fairly effectively as a temporary workaround.
* Wasn't the PMID page a monarch proposal? I can't remember having it here before. The idea would be to get that information from elsewhere/pre-load it and then have it and all loaded PMID annotation info?

**Comment by cmungall** [comment]
1. cool!
 2. Ah, I think I was searching using a PMID we didn't have. In which case the results are unintuitive, as everything matches "PMID"
 3. Would be good to have for GO. Could move over mon component when done

**Comment by cmungall** [comment]
Grebe template not a high priority (don't recall where this came from).

The others covered in the #349 and #120 so closing this
