### ISSUE TITLE
It is possible to navigate to a "gene_product" page, instead of a "bioentity" page

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#287]
From @elserj conversation.

```
> Hey neat--that should not exist. Or maybe it exists as a compatibility
> layer to an older version (more likely as I think about it). However,
> that page should be impossible to navigate to in the normal course of
> use--"bioentity" should be the standard one. If you got there through
> clickable navigation, please let me know: it might be a bug.
From http://amigo.geneontology.org/amigo/search/annotation, all I did was click on the first item in the "Gene/product" column, "SS1G_02765". 
```

It shoud not be possible to navigate to a "gene_product" page. Instead, it should be a "bioentity" page

**Comment by cmungall** [comment]
is this a surface issue? Are the two pages identical or divergent?

**Comment by kltm** [comment]
Very surface methinks (linker), if there is an issue at all.
I think in my head, with the initial report, I might have been conflating search/bioentity and amigo/gene_product (the former is definitely not possible, the latter is correct, e.g. http://wiki.geneontology.org/index.php/AmiGO_2_Manual:_Linking_To_AmiGO_2#Gene_Products). If @elserj could maybe supply some of the original context, and I could review where this is.

**Comment by elserj** [comment]
I actually don't have a problem with how it currently works at all.  As I recall, you were surprised I got to the gene_product page and opened a ticket for it.  I actually thought it was working correctly.

**Comment by kltm** [comment]
Okay then, no more late nights for me: I did indeed see "search" in the path rather than the "amigo", probably since we were talking about a search page.
Thanks for getting me back on the right page!
