### ISSUE TITLE
Database entry showing up on Synonyms line in gene_product page if column 11 in gaf is empty

### ISSUE THREAD

**Issue by elserj** [geneontology/amigo#288]
Copying from my email to @kltm but @cmungall suggested to open an issue for it:

So, I'm trying to fix this issue where the "Database" entry shows up on the "Synonyms" line if there is no synonym defined in the gaf file.  The column is defined to be optional, so I would assume it should be fine but it doesn't look right.  Compare these two pages:
http://dev.planteome.org/amigo/gene_product/Ensembl_Plants:OS01G0773700
http://dev.planteome.org/amigo/gene_product/Ensembl_Plants:OS09G0252800
(showed the error at time of ticket creation, data load is temporary, Chris saw the issue and can possibly explain if data is no longer loaded)

The second one is correct, but that is where I added "Justin" in the synonym field in the gaf.

I think I've narrowed down the issue to the template file pages/gene_product_details.tmpl but this section looks correct to me:
```
<dt>Synonyms</dt>
      [% sl = GP_INFO.synonyms %]
      [% IF sl.size == 0 %]
      <dd>None</dd>
      [% ELSE %]
      [%    FOREACH synh IN sl %]
      <!-- <dd class="syn">[% IF synh.scope %]<span class="type">[% synh.scope %]</span>: [% END %][% synh.acc %]</dd> -->
<!--      [%       ## Something broken in the GAF or pipeline? %]-->
      [%       IF synh == "" %]
      <dd>(n/a)</dd>
      [%       ELSE %]
      <dd>[% synh %]</dd>
      [%       END %]
      [%    END %]
      [% END %]
```
If I'm reading this right, I think what it should do is if no synonyms are defined, it should put the text "None" there, but it doesn't appear to be doing that.  I was hoping another pair of eyes could see why it isn't.  I could change the gaf files, but I think that is the wrong solution as the column should be optional.

Let me know if you need any more info.

**Comment by kltm** [comment]
@elserj those two pages still show the error, so I can see the problem. It seems like...maybe almost and error at the html level so that the wrong item gets bumped up? Weird.
(And updated your comment for formatting.)

**Comment by kltm** [comment]
@elserj Could you send me a test GAF with those two lines and I'll see if I can re-create it on this end to see what is going on.

**Comment by elserj** [comment]
[go_ortho_test.assoc.txt](https://github.com/geneontology/amigo/files/79249/go_ortho_test.assoc.txt)
I did do a bit of troublshooting before I emailed you.  If I output the "sl" object as referenced above, I get nothing for my problem case, but the IF statement isn't entered.  For the other case, I get an "ARRAY" object, if that is helpful.

Maybe there is a chance that it could be caused by my changes to the yaml files or the templates?   But the only change I have made in the gene_product_details.tmpl file is the address for feedback.  Let me know if you can't replicate.

**Comment by kltm** [comment]
Okay, I've duplicated this locally.

**Comment by kltm** [comment]
Odd that this slipped through. Essentially, in some cases data comes back from the worker (perl/lib/AmiGO/Worker/GOlr/GeneProduct.pm) as null instead of an empty array (I'm not sure if that should always be an empty array or if null is legit, but that's not a worry for here). I've fixed it by adding a couple of extra checks.
