### ISSUE TITLE
Alt ID links for GO terms return a 404 error

### ISSUE THREAD

**Issue by elserj** [geneontology/amigo#289]
Example, free text search for "axoneme assembly" since this is a term that has a GO id in the "Alt ID" column in the search table.  Clicking on either of the given links in that column takes to a 404 error page, suggesting to search by synonym, which does work.

@jaiswalp suggested either getting rid of the hyperlink entirely, or direct it to the search.  Note that this only seem to be a problem for GO ids.  For example, Uberon ones got to a purl link, which redirects to ontobee, so I'm not sure what the best solution actually is.

**Comment by elserj** [comment]
Initial ticket Planteome/amigo#6.  More comments with that ticket.

Looks like the link is being created via db-xrefs.yaml, so maybe just use a different xref for GO?

**Comment by jaiswalp** [comment]
problem is the original term does not exist. It was merged to the term for which they appear as ALT ID. If there is term history it can be linked there. My suggestion would be to avoid any hyperlinks.

**Comment by kltm** [comment]
@elserj dbxref changes do not work here as these are not external references, but rather internal references, which means we need to look at the linker.

What the linker usually does is see if it can match the string, and if so, create the appropriate link. The best solution then would be to have the linker ignore the obvious GO ids in the case of the alt id column. I believe this can be accomplished with either an overriding handler of a modifier to the linker duck class being used in amigo.

**Comment by kltm** [comment]
Naturally, this would be better solved with a solution to #91. This would mean at the perl level, if an initial data load was not created by the worker, it would try again, searching in the alternate_id field for a match, and return that load.

**Comment by kltm** [comment]
Exploring the linker.js code, a fix would not be possible there without monkeying around with the widget argument passing (field needs to be passed as modifier argument, rather than just gross category). That would probably be a long-term Good, but not really the bandwidth now to take care of it. I'm going to next look at the handler system, which is a bit of a large hammer to get the display to /not/ do something, but the easiest tool at hand right now.

**Comment by kltm** [comment]
While my fix seems to work, a preferable solution (short of fixing the general problem raised in #91) would be to make sure that 1) the modifier information always gets passed, as a field in the right context, and 2) that this is consistent with the use of modifiers elsewhere.
