### ISSUE TITLE
AmiGO should support a more full JSON REST API for data retreival

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#292]
While AmiGO current supports a minimal API (i.e. http://wiki.geneontology.org/index.php/AmiGO_2_Manual:_Linking_To_AmiGO_2), there is a clamour for a more full-bodied API:

```
Since Planteome's AmiGO2 instance is currently the "warehouse of record" for Planteome ontologies and annotations, it makes the most sense to use as much AmiGO API functionality as we can, perhaps behind a Planteome API wrapper (i.e. www.planteome.org/api/term_search/q=<query>, www.planteome.org/api/term/PO:0001234/json, etc.)

We know we can get JSON for single term data:

    http://dev.planteome.org/amigo/term/GO:0022626/json

...but what about JSON from a (partial) keyword search? This returns HTML: http://browser.planteome.org/amigo/search/ontology?q=plant%20height
```

It should be noted that while there is interest in moving forward with a new and better AmiGO API based around the JS API, rereading the initial request, the minimal requirements could likely be met with the current perl framework.

**Comment by preecej** [comment]
Conversation capture:



Justin,

For your short-term aims, given the information, I believe that
something could be levered into the current framework relatively easily.
(The longer term goals would require more work, with the graph-based
stuff outside of AmiGO.)

There is other interest in capturing some very basic GIS elements in
AmiGO, so that might be something that would fold into the system.

A minor question about BisQue: is that a matlab based project?

Cheers,

-Seth

**Comment by jaiswalp** [comment]
See if this helps https://apiary.io/ in building APIs.

**Comment by jaiswalp** [comment]
Plant Breeding API is using this http://docs.brapi.apiary.io/#

**Comment by kltm** [comment]
Poking around a little, it seems to be an interesting tool, but I feel a bit squeegee about using non-free tooling in a project. (Oh hi, GitHub!). I'm not entirely sure what one would get over swagger and a mock server however.

**Comment by jaiswalp** [comment]
I think its free for open source project like ours.

**Comment by kltm** [comment]
Sorry, I meant "free" as in OSS or libre software, rather than free of charge. (For the former, I'm always happy to pay.)

**Comment by jaiswalp** [comment]
i get it

**Comment by kltm** [comment]
Instead of opening a new ticket, let's continue on here. This is from a discussion with @elserj @preecej @hdietze earlier today, and to help fill in @cmungall about what we talked about.

Given some of the technical details about the final use of the JSON API (used for non-JS clients for things like autocomplete, etc.), I no longer believe that we can accomplish these goals extending the current perl API.

Because of this, the API services will initially be a standalone service, probably copied right out of the geneontology/go-numbers-service code (which would likely be folded back in at some point), and separately deployed. While initially just a server wrapper for the JSON API, it would be the seed for an eventual "AmiGO 3", which would be a UI layer over it that was essentially a port of the current AmiGO 2 stack. (This final bit would be in the nebulous future as a deliverable.)

As the geneontology/go-numbers-service already lays out the use of engines and arguments, and I have heard nothing yet that isn't essentially a RESTification of the current bookmark "api" (which we already have), an initial usable effort is not expected to take more than a day, and should be ready during the window of February given by @preecej .

**Comment by preecej** [comment]
Thanks, Seth. To brass tacks, then...

Immediate use-case: Serve two API methods from planteome.org (via the AmiGO platform) -- ontology term search and ontology term details -- that return ontology data from Planteome's Solr instance for annotating images with ontology terms in the CyVerse Bisque environment. Needs to be fast enough to be integrated with autocomplete boxes and dialogue labels on 3rd-party Bisque client-side interface

**Method 1: Term Search**
Request: URL in the following format, or similar: /amigo/search/term?q=<partial or complete term name>
Optional parameters: include_synonyms, ontology_filter, max_results, prioritize_exact_match
Response: JSON (0 to many results)
- {
term_search_response: [
{
match: <term name>,
match_type: <term or synonym>
accession_id: <##:#######>,
ontology: <ontology name>
},
...
}

**Method 2: Term Detail** - this already exists!
Request: /amigo/term/<accessopn_id>/json
Response: JSON (0 to 1 result)
as in this example: http://dev.planteome.org/amigo/term/PO:0000050/json

This is a starting point. Feel free to suggest refinements. Thanks!

**Comment by cmungall** [comment]
What is the expected value of the ontology field?

**Comment by preecej** [comment]
A distinct namespace representing a particular ontology: gene_ontology, plant_ontology, plant_disease_ontology, traint_ontology, etc.

Justin Preece
Sr. Faculty Research Assistant, Bioinformatics
Jaiswal Lab, Dept. of Botany & Plant Pathology
m: 214-288-1510
Oregon State University

**Comment by cmungall** [comment]
This is currently impossible for amigo as there is no such metadata in any of the existing ontology files.

First you'll want to insert a dc:title annotation on each ontology. Then we can either have a generic ontology owl:annotation query method, where the client passes in the annotationProperty, or a specific method. Either way the annotation needs to be there.

**Comment by cooperl09** [comment]
Could it use the exiting ontology annotation in the header, rather than the whole namespace? 
For example:
ontology: to
ontology: po

**Comment by preecej** [comment]
i vote for using default-namespace. this value will be converted to natural language for use by "real-live humans" in a client UI.    ;)

**Comment by cmungall** [comment]
You can't use default-namespace, it's a syntactic directive that exists only in .obo. 

I recommend using standard annotation properties

**Comment by preecej** [comment]
Fine. **dc:title annotation on each ontology**. Who should make this annotation?

We just need to be able to pull the name of the ontology associated with a term, since I am assuming that our search results will mix ontology terms (PO, GO, TO, EO, etc. all living in one AmiGO data store), and our users would like some clarity in identifying the source of various terms as they annotate images and other data.

Seth: How does this sound to you?

**Comment by kltm** [comment]
We talked a little about this and it sounds good. We'll chart progress for this part on #305.

**Comment by kltm** [comment]
@elserj While there is some more work to do (mainly trying to re-enable the numbers services in this fork and getting the payload to be lighter in "autocomplete" situations), you might want to start taking a look at deploying (and otherwise playing with) amigo.js.
To invoke, try:
```
gulp run-amigo-api
```
TODO:
- [ ] try to re-enable the numbers services in this fork (currently numbers services borked)
- [ ] get the payload to be lighter in "autocomplete" situations
- [ ] remove hardwire to GO GOlr instance

**Comment by kltm** [comment]
Short of bugs, I think that this has all been implemented for the first pass (with some use cases being met by creating additional search personalities).
