### ISSUE TITLE
Improved views of annotations for biologists (redundancy filtering)

### ISSUE THREAD

**Issue by selewis** [geneontology/amigo#294]
Reduce redundancy by filtering out IEA annotations (to the same gene product) that are to broader terms (i.e. just show the most specific IEAs for that gene product).

**Comment by selewis** [comment]
Actually this could be useful for any evidence type, just showing the most specific information available.

**Comment by kltm** [comment]
@cmungall This may be #43 depending on approach.

**Comment by cmungall** [comment]
@kltm - correct. I think the only approach is to precompute something in the golr index

**Comment by ValWood** [comment]
+1
At PomBase we do this with IEAs NAS and TAS,. We only use these to *supplement* manual annotation and discard anything which is less specific than any manual annotation. Nobody misses them and we remove 87% of our IEAs in this way (all but ~4000 currently). 

This has lots of other advantages as well making the annotation easier for our users to consume, the bad IEA annotations are now easy to spot.
https://github.com/geneontology/go-annotation/issues

http://www.slideshare.net/ValerieWood/pombase-internal-rules-for-curation-using-ontologies
slides 23 -28

**Comment by cmungall** [comment]
Dupe with #43
