### ISSUE TITLE
Improved views of annotations for biologists (visual compaction)

### ISSUE THREAD

**Issue by selewis** [geneontology/amigo#295]
Reduce redundancy by only showing the annotation of the same term to the same gene product once. Simply indicate with a \* or + sign that there multiple statements with supporting evidence (multiple evidence codes and/or multiple papers) for this association.

**Comment by kltm** [comment]
This was something that actually existed in the AmiGO 1.x series.
Also pinging @cmungall .

**Comment by ValWood** [comment]
+1
We do this too.
http://www.pombase.org/spombe/result/SPBC11B10.09#go-molecular_function

We only show the biologically relevant detail (anything with a different extension). Click on the + to see all the evidence and source.

Next I would like to go  a step further  in the gene product view by also hiding (experimental) annotations to ancestors which do not have unique information (as mentioned previously we already filter redundant IEA, but we 'discard' these.  Here we would keep the annotations but hide them in the default display, and show them in the full display).

**Comment by cmungall** [comment]
Dupe with #43
