### ISSUE TITLE
AmiGO source filtering impossible

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#298]
This is probably really a jenkins QC check issue so it could be 'wrong tracker'

Shouldn't all the sources match the database prefix in some file somewhere?
I was trying to filter annotations on source BUT

WormBase  and WB
FlyBase and FLYBASE
UniProt and UniProtKB
AspGD and ASPGD
GO_Central GO_CENTRAL GOC

**Comment by kltm** [comment]
No problem @ValWood --likely wrong location, I'd guess geneontology/go-site would be better to start.

It sounds like a data problem. AFAIK, there is no additional data massaging (in this case, collapsing) at this end before loading. @hdietze , any thought here?

Whoever takes this, please leave a reference to the new location and close this out.

**Comment by kltm** [comment]
Still looking for this data issue to get moved. any thought from @hdietze or @cmungall ?

**Comment by ValWood** [comment]
Ah *that's* where this ticket is

**Comment by cmungall** [comment]
Assigned to @hdietze to provide recommendations. As we migrate the perl gaf checks to jenkins, will this reporting become more transparent?

**Comment by kltm** [comment]
To add to this list:
ENSEMBL <=> Ensembl
REFGENOME <=> RefGenome
It looks like somebody is filtering though an old db system and then we're getting them back.

**Comment by kltm** [comment]
@cmungall no more Heiko, so we'll need a new action for the pipeline.

**Comment by kltm** [comment]
Either way, this is not a "hotfix" item (blocking all other work); moving to "wishlist".

**Comment by cmungall** [comment]
Or you can move to go-site

**Comment by kltm** [comment]
Yes, cannot possibly be fixed within the AmiGO codebase.
