### ISSUE TITLE
amigo filtering  gene products on 'type'

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#300]
I was trying to answer a question for one of our users yesterday

I got stuck, because I could not filter  annotations based on "gene product type"
http://listserver.ebi.ac.uk/pipermail/pombelist/2016/004480.html
(I was only interested in the annotations for protein coding genes, not tRNA other ncRNA),
but this is not an available filter?

**Comment by kltm** [comment]
"type" is currently only available on the gene product search pages (http://amigo.geneontology.org/amigo/search/bioentity), not the annotation ones.

The closest one could get would be: http://amigo.geneontology.org/amigo/search/bioentity?q=RNA%20binding*&fq=type:%22protein%22&fq=regulates_closure_label:%22RNA%20binding%22&sfq=document_category:%22bioentity%22
which would be gene products, but not annotations

If this is a necessary feature, we could add that to the loader for the next version.

**Comment by cmungall** [comment]
Seems arbitrary/asymmetrical to have it in one and not the other?

**Comment by kltm** [comment]
Yes, there are many asymmetries in there from the piecemeal evolution of the loader code.

**Comment by ValWood** [comment]
I think commonly users are working only with proteins and ideally wish to filter out tRNAs, rRNAs and other non-coding RNAs from downloaded annotations.

Although this will still be tricky when lots of sources use 'gene_product' instead of the more specific  protein or ncRNA (even when this is clearly known). Is there a soft check  to encourage people to migrate to the correct object type?

**Comment by cmungall** [comment]
Of interest - stuff coming from RNAC is not typed correctly: https://github.com/geneontology/go-site/issues/234

However, the scope of this ticket is just about the behavior of AmiGO, assuming AmiGO gets the correct input

**Comment by cmungall** [comment]
> If this is a necessary feature, we could add that to the loader for the next version.

No need for loader changes, it's loaded. It's a one-line conf change to include this is a facet (and probably to include as an extra column). Maybe we could even hot-fix this.

This is v useful, as we are reporting on miRNAs in NAR

**Comment by kltm** [comment]
@cmungall Do you really want this as a production hotfix, or are you fine with it being available on the development server?

**Comment by cmungall** [comment]
Dev server fine

**Comment by kltm** [comment]
http://tomodachi.berkeleybop.org/amigo/search/annotation
