### ISSUE TITLE
A large number of missing UniProtKB annotations

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#301]
I think there must be a LOT of UniProt annotation missing?

If I filter on annotation
assigned by UniProt
and
Experimental evidence

and there are only 9987 results  (5 species)

**Comment by ValWood** [comment]
![missing uniprot_annotation](https://cloud.githubusercontent.com/assets/7359272/13111951/a6d9a7f4-d580-11e5-89c4-27e2ad780067.jpg)

**Comment by kltm** [comment]
With the same setup, I currently get 262854 annotations and a /lot/ of species. This sounds an awful lot like you were somehow able to access AmiGO during a load, which should not be possible (tagging @stuartmiyasato just in case). Can you confirm that you were definitely at http://amigo.geneontology.org ? Unfortunately, your screenshot does not contain enough information to confirm the location (it's mostly cut-off in the lower right part of the image).

**Comment by stuartmiyasato** [comment]
> With the same setup, I currently get 262854 annotations and a /lot/ of species. This sounds an awful lot like you were somehow able to access AmiGO during a load, which should not be possible (tagging @stuartmiyasato just in case)

@kltm you are correct, this should not be possible in production.  All of the web servers on the AmiGO servers (httpd, nginx, jetty) are turned off when the data is being refreshed.  Our Nagios monitoring is showing HTTP downtime once a day, presumably when the refresh is taking place, so I don't think it's possible.

**Comment by kltm** [comment]
@ValWood Okay, my next guess is that you were on the non-production Berkeley servers and caught one of them during a refresh (possibly at http://amigo2.berkeleybop.org or http://tomodachi.berkeleybop.org), which would probably not be very hard at all given the time difference. If you see something like this again, please confirm the URL and let us know (or tag it on to this ticket); otherwise, since I cannot reproduce, I'll chalk it up to freak accident or different server for now.

**Comment by cmungall** [comment]
I'm going to open this until we try some more tests, or until Val confirms she was on a dev URL. This is a serious production issue if it's on the production URL.

I find the timing suspicious. This would have been between 8am-8.30am PT.  @stuartmiyasato what times do the loads happen? We should at least do some tests around the same time tomorrow. Recall we previously had issues with cached URLs for the solr index happening at this time (although the phenotype was for it to simply spin and show no data).

**Comment by cmungall** [comment]
OK, I know what's going on here... hold up...

**Comment by ValWood** [comment]
My bookmark is here http://amigo.geneontology.org/amigo
I wasn't anywhere else unless somehow my actions  from here picked up a dev URL...

**Comment by ValWood** [comment]
Ah OK its this

> Sometimes the assigned_by field is UniProt
> Sometimes the assigned_by field is UniProtKB

I have an open ticket about this somewhere, help desk I think.....(it isn't only this one, there are others listed in 2 ways FB and flybase etc.

There used to be a hard check on the contents of this field which used the dbxrefs config file, has this been dropped?

**Comment by stuartmiyasato** [comment]
> I find the timing suspicious. This would have been between 8am-8.30am PT. @stuartmiyasato what times do the loads happen? We should at least do some tests around the same time tomorrow.

@cmungall:  The load starts at 5pm PT.  amigo2a is down from roughly 8pm to 9pm PT for the data refresh, and amigo2b is refreshed from roughly 9pm to 10pm PT.

I'm assuming @ValWood has found the "real" issue with the assigned_by field, but just in case you need the above data...

**Comment by kltm** [comment]
If there is a ticket elsewhere (GO Helpdesk mentioned), this should be closed here--this is pretty far up the pipeline away from AmiGO.

**Comment by cmungall** [comment]
moved https://github.com/geneontology/go-site/issues/163
