### ISSUE TITLE
Rename "Grebe" to something less weird

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#303]
Nobody knows what Grebe is or does, except maybe Tanya. Rename it to something better and try and get some traffic through there.

**Comment by ValWood** [comment]
I had forgotten, but @tberardini told me how cool it was  about 3 years ago ;), I'm sure nobody else on  the planet has even seen it...

**Comment by tberardini** [comment]
It *is* cool!

**Comment by ValWood** [comment]
"Get started with Grebe" makes me think, oh no, I don't want to learn anything new right now....maybe another day...maybe on a train when I have a free minute?...Pocket?... NOPE never doing that.
