### ISSUE TITLE
Add proper ID space information to term information

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#305]
Add at least the proper ontology ID space information for terms. Fall back to ID.

Seeded from:
https://github.com/geneontology/amigo/issues/292#issuecomment-185993297

Tagging @cmungall @hdietze @preecj @elserj

**Comment by kltm** [comment]
This will require coordination with a new function on OWLTools, double tagging @hdietze.

**Comment by kltm** [comment]
Original reference in #292.

**Comment by elserj** [comment]
@preecej, not preecj.  Making sure he sees this.

**Comment by kltm** [comment]
:disappointed:

**Comment by hdietze** [comment]
The new id space function in OWLTools is now available for use in the flex loader.

**Comment by kltm** [comment]
This should now be completely strung through.

**Comment by preecej** [comment]
Thanks! We'll test it at: test.planteome.org/api once we pull it down.
