### ISSUE TITLE
Reorder the filters in the left panel for annotation search

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#307]
cc @thomaspd

http://amigo.geneontology.org/amigo/search/annotation
Reorder the filters in the left panel.  It should go:

 * Ontology (aspect)
 * Organism [new label for what is now Taxon]
 * Evidence type
 * GO class [new label for Inferred Annotation]
 * GO class (direct) [new label for Direct Annotation]
 * Annotation qualifier
 * Annotation extension
 * Contributor [new label for Assigned by]
 * PANTHER family

**Comment by kltm** [comment]
Easily accomplished by changes to metadata/ann-config.yaml.
