### ISSUE TITLE
Use a whitelist of evidence types in faceted search

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#308]
From @thomaspd

>  The Evidence type filtering choices should be simplified, to only include the terminal node classes, and no parent classes except for experimental evidence and similarity evidence 
> used in manual assertion.

Note that this is analogous to what we have partially done for taxa in #247 and #209 

Also same question as here: https://github.com/geneontology/amigo/issues/247#issuecomment-185521480

**Comment by kltm** [comment]
From today's discussion, rather than adding a new field for evidence here, we're considering adding an evidence whitelist as part of the amigo configuration "context". The offshoot here would be that it would be abstractly applied to and manager moderated filter in an abstract way.
This may be the best route here, but will require some changes. It might be best to jump to the newer manager and widget versions so the fix does not need to be ported.

**Comment by kltm** [comment]
@cmungall 
Talking to @hdietze about doing the same thing here as we did in #247, we'd likely want to do some other cleanup around evidence codes (it's very old stuff harkening back to 3-letter codes), making it a little more involved. As well, we'd want a subset (or subsets) that should be tagged.

**Comment by cmungall** [comment]
If @mchibucos is open to it, I will just add the subsets directly to eco

I assume the same thing - no need to add classes that are directly referenced, only the grouping classes?

(@hdietze if you want to get this moving you could make a PR directly on eco-edit)

**Comment by mchibucos** [comment]
Sounds fine to me @cmungall to add them to ECO. Go ahead!
By the way, what is a "PR"?

**Comment by cmungall** [comment]
pull request

speaking of which, I just merged your obof eco pr

**Comment by mchibucos** [comment]
Ah. Thanks Chris!

**Comment by kltm** [comment]
The flag will be "--solr-eco-subset-name". Value TBD (@cmungall @hdietze )
"evidence_type" and "evidence_type_closure" will still be produced, but are considered legacy at this point, to be deprecated.
Our new fields will be:
```
 "evidence"
 "evidence_label"
 "evidence_closure"
 "evidence_closure_label"
 "evidence_closure_map" (schema autogen)
 "evidence_subset_closure"
 "evidence_subset_closure_label"
 "evidence_subset_closure_map" (schema autogen)
```
As this subset is going to be directly added to ECO, testing will be blocked until a tag version is release (although @cmungall says that this can be done relatively quickly).

**Comment by kltm** [comment]
Will test locally first; tomodachi also already prepped with new schema and tools.

**Comment by kltm** [comment]
From @cmungall 's commit, the full CLI arg will be then:
```
--solr-eco-subset-name go_groupings
```

**Comment by kltm** [comment]
@cmungall will you let me know when that's wild, or should I watch for evidenceontology/evidenceontology#93 to be merged?
