### ISSUE TITLE
Improve tip text on some download buttons

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#309]
From @thomaspd

> Tips on the download buttons should be changed:
> GAF chunk download -> Download (standard format)
> Flex download-> Download (customizable format)
> Increase download limits to at least 600,000 if possible (so someone can get all annotations for a particular organism).

(as a general note, we have been replacing some of this private terminology like 'grebe'. 'Flex' should go the same way)

<strike> @kltm - is 600k safe? do we need some kind of throttle or iterator? </strike>

**Comment by kltm** [comment]
Unfortunately, unknown. I know of no method of throttling, and I think an iterator would probably cause more problems than solve. If this is necessary, I'd first test to see how well that works, and then consider throwing hardware at it.

**Comment by cmungall** [comment]
Max number of downloads: #193

**Comment by kltm** [comment]
"flex" and "grebe" should now be gone. As well, with the last update, button formats have changed:
http://tomodachi.berkeleybop.org/amigo/search/annotation
Given the new text, shall we still have the longer labels here?

**Comment by thomaspd** [comment]
Thanks Seth, this looks good, and I think the button text is probably enough.  One more thing I now see: it may not be obvious to users that they can add filter criteria by clicking on the different buttons in the left panel.  What do you think about adding brief text above the “Ontology (aspect)” button, something like: "Click below to add filters:”?

Thanks,
Paul.

**Comment by cmungall** [comment]
FYI Matrix compare doesn't appear to be working. I can bring up the dialog, but Continue does nothing.

I like having the ability to download either in GAF format or a custom format. I'm not sure how best to communicate this succinctly in either a very short label or glyph. However, the GAF download is probably the higher priority, so this one should be prominent and clear. "GAF" is GO lingo. Many people will know what it means, especially the power users who want to download, but many people coming here for the first time won't.

**Comment by thomaspd** [comment]
Maybe 'standard (GAF) format' on the button if not too verbose, and 'custom format' for the other?

Sent from my iPhone

On Mar 23, 2016, at 8:01 PM, Chris Mungall <notifications@github.com<mailto:notifications@github.com>> wrote:


FYI Matrix compare doesn't appear to be working. I can bring up the dialog, but Continue does nothing.

I like having the ability to download either in GAF format or a custom format. I'm not sure how best to communicate this succinctly in either a very short label or glyph. However, the GAF download is probably the higher priority, so this one should be prominent and clear. "GAF" is GO lingo. Many people will know what it means, especially the power users who want to download, but many people coming here for the first time won't.

**Comment by kltm** [comment]
@cmungall #323.
