### ISSUE TITLE
The menu items at the top of the page should be the same as for the Homepage

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#310]
From @thomaspd

> The menu items at the top of the page should be the same as for the Homepage

I think this requires more discussion. Currently these are conceived of as different things: the website and an application. This distinction has always served us more than users. However, attempting to blur the distinctions in an incomplete way could lead to confusion.

**Comment by kltm** [comment]
I'm not sure this is the right title.
I think there is a very useful separation between the two, and the distinctions are important. That said, there could be much more done with the website to have it link in, full from, and get users to the right places in the applications that we offer.

**Comment by thomaspd** [comment]
Maybe there’s a middle ground— the Amigo menu can have all the items that the Homepage has, preferably in the same place, and then additional Amigo-specific items.

**Comment by kltm** [comment]
Similar, at least: an exact copy, as it stands, would likely cause confusion with things like documentation. Personally, I think that it would rather clouds the distinction, and make maintenance of both ends harder.

**Comment by kltm** [comment]
Any more comments for this one? I'm starting to be able to see the end of this release and am trying to close out tickets?
