### ISSUE TITLE
Filter changes for ontology search

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#311]
From @thomaspd

> Amigo2, for ontology (http://amigo.geneontology.org/amigo/search/ontology):
> 1. Remove Ancestor filtering item— I don’t see a use case for it.

OK, let's do this for now. It's overwhelming. But I think there is a use case for having some high level subset in there. For example to see all behavior, or all cellular process. This is analogous to #247 

There is also some discussion of this buried in this (closed) ticket:
https://github.com/geneontology/amigo/issues/186#issuecomment-95358518

> 2. Filter out all ontology sources, except for the GO, by default (though user can of course remove the filters)

I thought we had a ticket for this, but can't find it.

> 3. Filter out all obsolete=true terms by default (though user can remove it).  Obsoletion should be renamed to Obsoletion status.

+1

**Comment by kltm** [comment]
The fix for the default idspace filtering was a little more involved as it needed to be generalized to non-GO situations, but puts to use our new idspace information.
