### ISSUE TITLE
Decommission AmiGO 1.x

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#312]
From @thomaspd:

> Amigo1 (http://amigo1.geneontology.org/cgi-bin/amigo/browse.cgi):
> 1. Remove the following menu items:
> Search
> Browse
> BLAST
> Homolog Annotation
> Tools and resources

Context:

> because from feedback I’ve gotten, people still like to try to 
> browse ontologies using a tree expand/collapse

We should just kill amigo1, but I agree that the tree browse functionality is required. This is in ticket #51

I would rather just implement 51 (I think it can be done without solr5). But if this will take a while then I guess changing the menu in amigo1 is what we have to do...

**Comment by kltm** [comment]
We have like a half dozen "browsers" floating around and the amigo1 code paths are an irritation in amigo2. However, the enrichment and slim functionality is still occasionally used, so it would be nice to have something in place there.

Selectively removing menu items from various parts of AmiGO would likely cost more time than it's worth.

**Comment by kltm** [comment]
The browser bits are in item #163.

**Comment by kltm** [comment]
I'm scared to go into the A1.x code again, much less try to get it into production. I'd prefer to frame this as whether or not we should decommission A1.x completely or allow the ghost to bump around a bit more. Given that some (?) people (?) still use it and that we still "support" things like our Galaxy, my druthers would be to let it be--AFAIK, it's taking *no* resources besides remembering to leave the power on and it apparently gets use.
If somebody is interested, our analytics might point to a way of knowing when might be the right time to flip the switch.
If there is not more feedback here, I'll re-frame it as a on/off issue and kick it to 2.5.

**Comment by kltm** [comment]
Preemptive change in state as we wind it down.

**Comment by kltm** [comment]
gone on experimental: http://amigo-exp.geneontology.io/amigo/software_list

**Comment by kltm** [comment]
Clearing--just needs rollout on production. Can get that when release done.
Heads-up to @stuartmiyasato

**Comment by kltm** [comment]
@stuartmiyasato There should now be no new traffic to AmiGO 1.x--all remaining traffic should be historical.

**Comment by kltm** [comment]
A note from @stuartmiyasato :

...I have turned off Apache on the AmiGO 1 servers.  They can be re-enabled quickly if needed.  I have also commented out our AmiGO 1 loading jobs out of cron.  I can turn these off permanently in a week or two if we don't see any resulting problems.

One thing I noticed is that DNS for amigo1.geneontology.org is currently pointing to an AWS instance (the old www server), so rather than getting a notice that users can't reach the server, connecting to <http://amigo1.geneontology.org/> instead gives the message "Not Found  The requested URL / was not found on this server."  I guess it's generating a redirect or acting as a reverse proxy?  Not a big deal, just wanted to point out the behavior.

**Comment by stuartmiyasato** [comment]
I have not received any reports of problems resulting from turning off the AmiGO 1 web servers.  I have now powered down the AmiGO 1 servers.  If think we should consider this service permanently retired now.  The machines are so old that I'm not sure we can get the disks to spin up if we power the servers up again!

Can we close this ticket or are there any other tickets dependent on this one?

**Comment by kltm** [comment]
We have received some feedback from people that were still using it, but I think it's just one of those things--we no longer have have pipeline in place and we cannot offer outdated data. Not ideal without firm replacements, but there's not much we can do.

A salute to you and those servers for keeping service to the community for so long! I think this ticket is done and AmiGO 1.x is finished: 2007?-2019, not a bad run.
https://web.archive.org/web/20071012054757/http://geneontology.org/amigo/help-front.shtml
https://web.archive.org/web/20071031105722/http://www.geneontology.org/amigo/help-browse.shtml

**Comment by pgaudet** [comment]
Do we want to announce this ? 
@kltm @suzialeksander

**Comment by kltm** [comment]
I believe this was discussed a while back and we agreed to just let this go.
