### ISSUE TITLE
Absolute links turned into relative links on amigo/xrefs page

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#313]
http://amigo.geneontology.org/xrefs

All the URL example links are broken

**Comment by kltm** [comment]
Cannot be closed until applied to 2.3.x and passed on to @stuartmiyasato.

**Comment by kltm** [comment]
@stuartmiyasato This is a simple template update. Would you or @kkarra be able to close this once pushed out to production?

**Comment by stuartmiyasato** [comment]
@kltm Sorry, I don't have a whole lot of time to look at this.  What is the procedure to update the template?  Just a normal "gulp install" or something else?

**Comment by kltm** [comment]
In fact, a repo pull should be enough--templates are not currently cached. If anything besides the template comes down there shoud be the "gulp install" step.

**Comment by stuartmiyasato** [comment]
Okay, I'll probably do the "gulp install" step anyway to make sure it doesn't break anything.  Tonight's refresh would run "gulp install" automatically.  I'd rather be present when it runs just in case anythng breaks!

**Comment by stuartmiyasato** [comment]
I have made the changes.  Can someone please test to see if the links are working correctly?

**Comment by kltm** [comment]
I've tested on amigo.geneontology.org and the two stanford severs directly--they all look good!
