### ISSUE TITLE
Update production AmiGO after upstream data fix

### ISSUE THREAD

**Issue by monicacecilia** [geneontology/amigo#315]
The UM-BBD URLs at UMN are not working, so each GO term that has UM-BBD as _Source_ leads to a page that no longer exists. For an example, please visit http://amigo2.berkeleybop.org/amigo/term/GO:0018920
or 
http://amigo.geneontology.org/amigo/term/GO:0018920

Edith Wong followed up with Emanuel from __[eawag](http://eawag-bbd.ethz.ch/index.html)__ and below is his response: 
>The UM-BBD/PPS has been transferred to Eawag-BBD/PPS under the general address of http://eawag-bbd.ethz.ch. Thus, you can now find the glyphosate data, for instance, under http://eawag-bbd.ethz.ch/gly/gly_map.html. 
>Please note, however, that as of around the middle of next year, Eawag-BBD/PPS will go offline and be completely replaced with the successor system enviPath (https://envipath.org). With regards to contents we intend to completely migrate all data from Eawag-BBD/PPS, but the form will be different.
>Right now we are working on a feature of the new system that allows to easily map the old addresses to the new ones.
>If you have joined the email list umbbd-users@sympa.ethz.ch you will receive detailed information about this mapping as soon as it is finalized.

These URLs should be updated.

**Comment by tberardini** [comment]
Possibly related update needed for this file:

https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml

- database: UM-BBD
  name: University of Minnesota Biocatalysis/Biodegradation Database
  generic_urls:
    - http://umbbd.msi.umn.edu/
  entity_types:
    - type_name: entity
      type_id: BET:0000000

**Comment by kltm** [comment]
I believe that this is not an AmiGO issue, but rather an upstream data issue. The proper location would be geneontology/go-site. I'll leave this open for "hotfix" resolution with @stuartmiyasato after upstream data is fixed.

**Comment by monicacecilia** [comment]
Sorry @kltm, you are right. I should have added that to go-site. -- had the wrong repo on screen.

**Comment by kltm** [comment]
Links to geneontology/go-site#165

**Comment by kltm** [comment]
Does anybody know of the upstream data has been fixed for this case? I can't find any actionable error either...

**Comment by kltm** [comment]
I've attempted to fix upstream, and it looks fine on http://tomodachi.berkeleybop.org/amigo/term/GO:0018920 .
@stuartmiyasato, at your leisure, could you do a refresh of the amigo data ("make install" or "make refresh" IIRC) and close out this item?

**Comment by kltm** [comment]
Sorry, or @kkarra .

**Comment by kltm** [comment]
This would have finally been solved by the new AmiGO release.
