### ISSUE TITLE
Wrong Relation Displayed in Inferred Tree View?

### ISSUE THREAD

**Issue by ukemi** [geneontology/amigo#316]
I think there is a bug in displaying relations in the inferred tree view for a GO term. If you search on the ontology term 'phosphatase complex (GO:1903293)' and display the inferred tree, the relation displayed between 'phosphatase complex' and 'phosphatase activity' is 'capable_of part of'. It should be 'capable_of'.

**Comment by kltm** [comment]
http://amigo.geneontology.org/amigo/term/GO:1903293#display-lineage-tab

**Comment by kltm** [comment]
Nuts, I get the "correct" answer using the JS browser:
http://nakama.berkeleybop.org/amigo/browse
There is almost certainly a bug in the perl engine then.

**Comment by kltm** [comment]
I'm thinking that I'd rather drop the perl version altogether and just have a form of the JS one in its place--I do not want to have to keep aligning these two codebases.

@ukemi , you like the current tree behavior with jumping between pages, right?

**Comment by kltm** [comment]
Ugh, or maybe not--there is also the [Ancestors and children] view.

**Comment by kltm** [comment]
Duplicated locally.

**Comment by cmungall** [comment]
Technically it's not wrong, it's just imprecise (as capable-of-part-of is the parent relation). However, it is confusing. We should show the more specific capable-of.

**Comment by kltm** [comment]
Okay, I see where this is going. In the transitivity closure, we have the following relations:
```json
                        {
                            "sub": "GO:1903293",
                            "obj": "GO:0016791",
                            "pred": "capable of"
                        },
```
and
```json
                        {
                            "sub": "GO:1903293",
                            "obj": "GO:0016791",
                            "pred": "capable of part of"
                        },
```
Both are, of course, right. This looks like the shadow of #161, with the JS grabbing one, and perl the other.
This could be "solved" by adding these relations to the weighing system.

**Comment by cmungall** [comment]
Bit ad-hoc, would be better to have better redundancy filtering 
upstream, but the weighting is at least a good and easy fallback
