### ISSUE TITLE
Matrix compare no longer works

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#323]
From @cmungall , matrix compare no longer works:
http://tomodachi.berkeleybop.org/amigo/search/annotation

Are we still using this thing?

In is almost certainly an un-migrated manager plus an un-migrate landing page.

**Comment by cmungall** [comment]
It's an incredibly powerful and cool feature (if a little unintuitive, and lacking a few features that would make it super-awesome). I doubt many external users use it. Can be dropped from 2.4 and kept as a labs feature til 2.5

**Comment by kltm** [comment]
Had to get in there with the new manager coordination as well (a bunch of iterations there).

@cmungall , unless I borked something, this should be working again.

**Comment by ValWood** [comment]
It's all working at
http://amigo2.berkeleybop.org/matrix
as it was...

![pombe](https://cloud.githubusercontent.com/assets/7359272/14105691/0e3c1938-f5a5-11e5-8906-0300e10fd8cb.jpg)

Pombe matrix looking nice and clean...although I already spotted a couple of annotation/ontology errors to clean up.

Will be nice when others can use too. I know @RLovering and Kimberly(https://github.com/orgs/geneontology/people?page=2 can't find github name here?)
interested....

**Comment by ValWood** [comment]
(At the moment you can only select pombe or all other organisms, all other organisms gives a very noisy splotch)

**Comment by cmungall** [comment]
Unfortunately the term 'matrix' is a bit generic here...

The ticket was about the facet-matrix-view (not sure if that's @kltm's official name), i.e. you search annotations, faceting on some field, e.g. species, then click the matrix button to plot two facets against each other (e.g. evidence by aspect). This got borked in the refactor but Seth has fixed.

We should call yours something like term-overlap-matrix (although the existing URL is fine).

**Comment by ValWood** [comment]
Ah OK. My name was tagged in some commits. Unfortunately I didn't know which ticket the commits went with.

Happy to test anything if you point me in the right direction.

**Comment by kltm** [comment]
Sorry @ValWood, I tagged you in the commits, but there wasn't a particular ticket about this; I've started one here #327.
