### ISSUE TITLE
Problem with display of annotation extensions on tomodachi

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#325]
Easily visible on the 2nd row for this gene 
http://tomodachi.berkeleybop.org/amigo/gene_product/MGI:MGI:3036246
shows the raw json
```
"relationship": {"relation": [{"id": "BFO:0000066", "label": "occurs in"}], "id": "CL:0000017", "label": "spermatocyte"}}
```

correct behavior here:
http://amigo2.berkeleybop.org/amigo/gene_product/MGI:MGI:3036246
'occurs in spermatocyte'

**Comment by kltm** [comment]
It seems like a handler has managed to not fire. Looking at the display, this may be general.

**Comment by kltm** [comment]
While pass-through seems to be working, I can confirm that no dispatch is being called.
