### ISSUE TITLE
Term Matrix may have issues after conversion to new framework

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#327]
The term matrix may have taken some damage from bitrot and framework migration between the last two releases. This ticket is to see if it still functions as expected, or if it needs from work.

Tagging @ValWood.

**Comment by kltm** [comment]
I can confirm that this is not currently working and needs some TLC.

**Comment by kltm** [comment]
Okay, tested on tomodachi (http://tomodachi.berkeleybop.org/matrix) now gives the same results as the original.

**Comment by ValWood** [comment]
Very nice. It all seems to work.
It might be good to make it clearer where the results are ( even a message saying scroll down for  results). I  thought it had not run at first.

I also like the new feature for ordering.
But what is "by input index?"

**Comment by ValWood** [comment]
Ah "preserve input order"?

**Comment by ValWood** [comment]
Actually the input order is always preserved so that toggle isn't working, but otherwise, very nice.

**Comment by ValWood** [comment]
Current information:

Enter a list of GO terms to see the co-annotations--the count of shared bioentities to pair-wise terms. Keep in mind that the more you enter the longer the initial startup will be.
If you wish to limit yourself to certain species, etc., use the filters on the left.

Suggest:
Enter a list of GO ID's to see the co-annotations--the count of shared gene products annotated to pairs of terms. Use the taxon filter to limit  species. 

eg. See numbers of gene products co-annotated to slim cellular process terms:
use this list (GO:0006457 GO:0071852 GO:0006629	 GO:0006399 GO:0006259 GO:0000003 GO:0044281 GO:0051276 GO:0000278 GO:0002181 GO:0006810 GO:0007010 GO:0016071
GO:0007005 GO:0006351  GO:0042254 GO:0023052 GO:0006464  GO:0006091
GO:0044262)

**Comment by ValWood** [comment]
Also it would be nice if the mouse over pop up allowed you to access the list of co-annotated genes.
I have been working around this by moving over to our query builder and querying the intersect, but most others will need this to assess intersections further.

**Comment by ValWood** [comment]
I'll put the 3 actions in a new ticket.

**Comment by kltm** [comment]
I agree with making the results more integrated into the display, but I think I've hit a point of diminishing returns with it until I can switch the toolkit (there are a few items around for that).

I've updated the text as described.

I'm not quite following the "input order" line, but it work for me and you've opened three tickets from here, so I'll follow on those.
