### ISSUE TITLE
Possible improvements for drill-down browser

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#332]
When you first arrive your search is pinned to  "document-category: annotation"

i) I always find 'document category' a slightly none obvious description (it isn't a document category is it?)
ii) I usually  (or often) want to search on gene products, not annotations, but I can't work out how to get rid of this filter.

iii) taxon. I think the taxon view should be populated by the species with the most EXPERIMENTAL annotations rather than any annotation.  I want to see the major models here as these are the most popular species to search on.

iv) The buttons are a bit large (it doesn't quite look as slick as the existing filter menu  somehow). Also, why do they need to look differnt?

v)

I filtered on process and pombe. I see this:
![drill down 1](https://cloud.githubusercontent.com/assets/7359272/14138214/d5d361d6-f663-11e5-954c-8c3c6e92bddf.jpg)

It isn't obvious why there are component annotations here?
So I decide to look at the annotations.
It isn't super obvious  how to access annotations. The link is  are a bit hidden at the bottom of the popup.

![drill down2](https://cloud.githubusercontent.com/assets/7359272/14138267/4061f184-f664-11e5-9543-77d76fe248aa.jpg)

Here:
Is ontology ID space  GO necessary here (or should be deprioritised)

Could "Retrieve annotations" be at the top?
Could default text be smaller? Make it a bit more compact?

Then, I get to this page:
![dd3](https://cloud.githubusercontent.com/assets/7359272/14138386/e4a7a0ae-f664-11e5-92bb-dfaa4982923a.jpg)

...and I really have no idea what I am looking at here.
What are the 1726 annotations  linked to 'component' in the original search. Thats what I was trying to establish, but these are process annotations.....very confused

**Comment by ValWood** [comment]
Will test some more when i know what I'm looking at.

**Comment by kltm** [comment]
1. This is a different ticket elsewhere, dealing with better text in the selected filter box
2. For the drill-down, I'd prefer to pick either annotations of gene products for the time being; later on, we might be able to make it toggleable
3. Assuming we are looking at annotations, one could select the evidence filter first and then select taxon; other than that (ans the other item about the general filter), there will be no way to make something like that work in the near term
4. We are currently bridging two different tool sets, without the resources necessary to finish it off before this release; there is a ticket open about this already

For the other parts, you added the process filter and then clicked through "cellular_component"; I'd assume the remainder exist due to cross-ontology connection.

For the location of the of the data retrieval, I will see what I can do there.

**Comment by cmungall** [comment]
I prefer gene products as default.

For (3), I expect this is a global request. I agree that the current data-driven ordering is not always perfect. But I think a fix will need to wait to 2.5. I will make a note in #247 so we don't forget this though

**Comment by kltm** [comment]
Two votes for gps--I'll switch that over.

**Comment by ValWood** [comment]
For me, you have dealt with everything in this ticket *except* why I see the component terms. I now understand why it happens but I think its bad to do this here.

So take the first annotation in my 'component' results. 
signal transduction involved in yada yada
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0072480#term=ancchart

This is getting a 'component annotation, because within the ontology this term is linked to 'intracellular'.
These links are currently incomplete, but this process term just happens to have one. It all process terms had their between ontology links established then, if I filter on process I would  see

biological process 12070
cellular component 12070
(or the gene product count once you switch).

This makes the ontology aspect filter pointless. If I filter on process, I only want process. 
If I'm interested in component too, I would not use the filter.

Its even less obvious why I see MFs (because MFs are 'small processes'. This must be via some 'regulates' relationship which is even more difficult to justify)

@cmungall  do you get me?

**Comment by kltm** [comment]
Okay, almost done, but there are enough comments here I want to clarify the final actions:

1. Do we keep this display over annotations (and keep the evidence filter) or switch to gene products (and lose evidence filter)?
2. *If* we we stay on annotation, do we keep aspect, remove it, or replace it with something more clear (e.g. direct or inferred annotation)?

**Comment by cmungall** [comment]
@ValWood agreed, it's logical but really confusing, I commented on this here: https://github.com/geneontology/amigo/issues/163#issuecomment-202979080 (sorry about all the drilldown tickets Seth, we're all just stoked to see it and can't contain ourselves!). Anyway, looks like aspect filtering is now gone on tomadachi.

Not sure I totally understand the choices, but I think the most logical that is possible within the current golr framework is toggling between:

 1. entity counts. Facets: taxon
 2. annotation counts. Facets: taxon, evidence

If it's easier to be uniform, then taxon only is fine. If it's easier to have no toggle, then 1. only is fine for 2.4

Note that dd_browse on tomadachi currently says "Nothing to filter" under organism, but I expect that is to do with the issue you and @hdietze are working on.

**Comment by kltm** [comment]
Okay, so we'll convert to bioentity no matter what, and then time willing let the user select to use annotations instead; aspect gone.

For the last part there, that will not be populated until the next load, but it's really cool.

**Comment by kltm** [comment]
No type or source for gene product filters?

**Comment by cmungall** [comment]
Type yes,

Source (as in DB prefix) is a bit of a legacy no need for it here, we 
have taxon

**Comment by ValWood** [comment]
I'm still not sure why you can't have aspect filter with different behavior. I often want to browse the annotations of a single aspect. 
I don't understand why, if you filter on process, logically you still need to show component or function totals (even if there are inter ontology links, even if inferred annotations are there, I specified that I only wanted process totals).
