### ISSUE TITLE
Term matrix feedback, text change

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#333]
https://github.com/geneontology/amigo/issues/327

Current information:

Enter a list of GO terms to see the co-annotations--the count of shared bioentities to pair-wise terms. Keep in mind that the more you enter the longer the initial startup will be.
If you wish to limit yourself to certain species, etc., use the filters on the left.

Suggest:
Enter a list of GO ID's to see the co-annotations--the count of shared gene products annotated to pairs of terms. Use the taxon filter to limit species.

eg. See numbers of gene products co-annotated to slim cellular process terms:
use this list (GO:0006457 GO:0071852 GO:0006629 GO:0006399 GO:0006259 GO:0000003 GO:0044281 GO:0051276 GO:0000278 GO:0002181 GO:0006810 GO:0007010 GO:0016071
GO:0007005 GO:0006351 GO:0042254 GO:0023052 GO:0006464 GO:0006091
GO:0044262)

**Comment by cmungall** [comment]
+1 to the proposed documentation update

Also, I think this is another case where the full set of facet filters is overkill. Not sure I see a use case for any of the filters other than species.

**Comment by ValWood** [comment]
Agreed,  I was thinking aspect could be useful, but essentially terms are dictated by ID list so no other facet is required. This  change would also probably make
https://github.com/geneontology/amigo/issues/336 a non issue

**Comment by kltm** [comment]
Closed in #327.
