### ISSUE TITLE
In the term matrix, allow access to gene list via pop-up

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#334]
from  https://github.com/geneontology/amigo/issues/327

Mouse over pop up  should allow you to access the list of co-annotated genes.
I have been working around this by moving over to our query builder and querying the intersect, but most others will need this to assess intersections further.

**Comment by cmungall** [comment]
You can do this by clicking on it. The modal dialog isn't very clear:

"Cell operations

Pair-wise bioentity search"

You then click it to get the list of genes via a search.

I would just remove this and have the click take you directly to the search

**Comment by ValWood** [comment]
Ah got it. Previusly I always thought this had been disabled. I presumed that the grey pop up which follows the cursor around was the pop up box
(the one which says the term name ID and number). 

Can all of this be in a single pop up?
term ID 
term ID
Annotation number  (hyperlinked  to retrieve  annotations)

**Comment by kltm** [comment]
Yeah, I'm working with a not great toolkit here (although I have found one I rather like and will switch when given a chance).

The reason for the modal right now is that I'm expecting more information and operations to appear in that box.
