### ISSUE TITLE
In drill-down browser, it is not clear how to open terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#337]
https://github.com/geneontology/amigo/issues/331#issuecomment-203613831

revising the drill down browser text made me realise that I could open terms (despite it being called drill-down, doh).  Even once I knew it was possible  it wasn't obvious how. You automatically click on the  term and get annotations which sort of distracts you from the drill-down. I think this is partially because the traingle to click on is so tiny. Would the little 'plus in a box icon' be more obvio
![dd](https://cloud.githubusercontent.com/assets/7359272/14166816/7e38e508-f70e-11e5-9a55-a6e773a4e4b8.jpg)
us here?

Or bigger triangles. Something to make it clearer 'click here'

**Comment by kltm** [comment]
Totally agree, but this may be a limitation of the toolkit. I'll take a look at that late today.

**Comment by ValWood** [comment]
I see it now. Its not so pretty but you can't have everything ;)

**Comment by kltm** [comment]
I'll try and give it a spit shine later on if/when I get the chance--I started to get a headache moving the wee pixels around. I think it at least says "click me" better than the last one.

**Comment by ValWood** [comment]
More delicate "+'s" would do it;)
