### ISSUE TITLE
matrix filter  omitted

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#338]
Oh sorry, I wasn't paying full attention here
https://github.com/geneontology/amigo/issues/333

An evidence code filter would be super-useful here.....
I would usually ignore IEAs in a first pass (because most will disappear once the experimental outliers are purged).
Might also be useful to see other sources like IMP ....

**Comment by kltm** [comment]
Unfortunately, since this is a bioentity view and not an annotation view, and because we go not have bioentity evidence aggregates in our store, we cannot give an evidence filter here.
