### ISSUE TITLE
Please make the filters and drop down 'sticky'

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#339]
This has been infuriating me for so long I don't know why I haven't opened a ticket before now.

Every time you set your filters and then proceed to an annotation you have to reset your filters.

Same if you want to browse all the annotations or products. Say there are nearly 100  annotations/products and  you change the drop down, you have to reset it after EVERY annotation you look at  to access the ones further down the list.

Ideally the default would be ~100 anyway. If you have more than 10 you would usually want  to see all them without changing a filter.

**Comment by kltm** [comment]
@ValWood I'm not sure what tool this is in reference to?

**Comment by kltm** [comment]
As well, there is #50.

**Comment by cmungall** [comment]
I think this ticket is a dupe with #50

**Comment by kltm** [comment]
That's what I thought ,but wasn't sure. If it's to do with the tree browser, it would either be "wontfix" or #50, otherwise #50.

I'll copy @ValWood 's comment to over there.

**Comment by ValWood** [comment]
Yep. AmiGO generally.
