### ISSUE TITLE
Create usable inferred browser widget from legacy bbop-js

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#342]
This ticket is to encapsulate the revival of the legacy bbop-js browse widget into the new bbop-widget-set npm framework, and have an example of that at the traditional /amigo/browse.

This will be of some interest for evidenceontology/evidenceontology#95 .

**Comment by kltm** [comment]
I'm most of the way through this, but I think I'll need to thread through some of the old bracket graph code into bbop-graph, or somewhere else.

**Comment by kltm** [comment]
The widget has been returned to functionality, as well as slightly better integration in the amigo setup. That said, it's still the same ugly thing as before, so comments and code are welcome.

**Comment by dolleyj** [comment]
When I initially attempted the browse widget, I was using the bbop.js CDN. Now that the browse widget has been restored, is it included in the CDN?

**Comment by kltm** [comment]
The CDN has been deprecated. We are now trying to distribute all of the widgets, etc., via NPM.
The packages will be amigo2-instance-data and bbop-widget-set, I've just made another release that contains the updates. The API is pretty much the same, but the location different: bbop-widget-set.browse.
Please make note of #321 .
Compiled example: http://tomodachi.berkeleybop.org/amigo/browse
https://github.com/geneontology/amigo/blob/master/javascript/web/Browse.js

**Comment by kltm** [comment]
I do not have the documents automatically generated yet, I will take a look at that.

**Comment by dolleyj** [comment]
I didn't realize that about the CDN. Thanks! I'll checkout those links.

**Comment by kltm** [comment]
Sorry, it's been a crazy month; there will be a lag as process and docs catch up to the code.
You might also want to note that the two packages I mentioned are now based out of this repo, in javascript/npm/, even though they are independent packages in NPM. Once #321 is cleared to satisfaction, they may (we'll see) be moved out.

**Comment by dolleyj** [comment]
That's good to know. Thank you.

**Comment by dolleyj** [comment]
Would it be possible to get a specific data structure (JSON) input example for this widget? Thank you!

**Comment by kltm** [comment]
Currently, we have tree browsers based off of berkeleybop/bbop-graph at:

 http://tomodachi.berkeleybop.org/amigo/dd_browse
 http://tomodachi.berkeleybop.org/amigo/browse

The first of these is not a "widget" yet, although it could be made so, but is rather "apps" within AmiGO that uses the available graph structures to create itself using the jstree package.
The latter now uses the bbop-widget-set package, available on NPM separately, housed as a sub-package in the amigo repo: https://github.com/geneontology/amigo/tree/master/javascript/npm/bbop-widget-set , https://github.com/geneontology/amigo/blob/master/javascript/npm/bbop-widget-set/lib/browse.js.

The topology and transitivity graphs need to have their documentation updated, but are currently explained here: https://github.com/berkeleybop/bbop-js/wiki/Graph
The real-world use is in https://github.com/geneontology/amigo/blob/master/javascript/web/Browse.js#L101, but if you are trying to have your own data backend (instead of using GO data) you'd probably have better luck with looking at the browse.js code: https://github.com/geneontology/amigo/blob/master/javascript/npm/bbop-widget-set/lib/browse.js#L129
