### ISSUE TITLE
inheritance over "regulates"

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#343]
I noticed that  "protein kinase regulators" are still retrieved when  you search on "protein kinase". This is misleading and it did not used to happen in GO (it took me a couple of years to persuade Ensembl that they should not do this, but should do what GO does, and now we do the opposite).

I thought there was a ticket about this but I can't find anything on the AmiGO tracker.
I can only find
https://github.com/geneontology/go-site/issues/126

**Comment by kltm** [comment]
I believe this is a dupe.
#210 #319, and I believe others?
Searching for "protein kinase" will give you a bunch of hits, including these.

**Comment by ValWood** [comment]
OK. Its quite a big problem.....

**Comment by kltm** [comment]
It looks like #210 is that active ticket right now.

**Comment by cmungall** [comment]
Yep, this one should be top priority for 2.5

**Comment by cmungall** [comment]
There will probably be some discussion at the GO meeting of relevance, 
talk to @vanaukenk about her and @ukemi's qualifier proposal

**Comment by ValWood** [comment]
I would love to see the Biological process terms  related to 'activity regulation' such as
        activation of protein kinase activity
	positive regulation of cyclin-dependent protein serine/threonine kinase activity
disappear from GO. 

But we will still need terms to annotate the molecular functions of real enzyme regulators like cyclins:
 GO:0019887 protein kinase regulator activity
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0019887#term=ancchart
and these currently have a 'regulates' relationship to protein kinases too.
