### ISSUE TITLE
Add a publication page

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#349]
Continued from 3rd bullet in #285 

The page would be fairly similar to bioentity etc pages, e.g.

`/reference/PMID:25281747`

e.g. same as http://amigo.geneontology.org/amigo/search/annotation?fq=reference:PMID:25281747

The document type would be association, and it would be pinned on this reference/publication.

Note that we don't store publication objects in golr. These could be fetched dynamically. NCBI eutils are pretty easy to use, and someone has already done the work here: https://www.npmjs.com/package/ncbi-eutils

optional: @vanaukenk may have ideas about how this page could hook into TPC. We could also do fun things like hook into the scigraph annotator to parse the abstract for GO terms and genes on the fly...

**Comment by kltm** [comment]
This would not be JS (so no NPM), but rather a perl external call. Should be easy enough though.

Another option is to just offer something through the current bookmark/link mechanism--we already have a "public" way of directly linking into AmiGO, so one could just use that, e.g.:
 http://amigo.geneontology.org/amigo/search/annotation?fq=reference:PMID:22835028
Ideally we could offer this as an extension like:
 http://amigo.geneontology.org/amigo/search/annotation?reference=PMID:22835028
Rather than the "unclean" filter pass-though. This would be trivial to add.

**Comment by kltm** [comment]
Is this a want now thing, or are we looking at 2.5 or wishlist?

**Comment by kltm** [comment]
Looks easy-peasy:
 http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&id=22835028
Although, if we get spidered, they'll the the resulting hammer...

**Comment by cmungall** [comment]
That's another reason I was thinking this could be client side.

Why not write the pmid info widget as a standalone pure js component?

**Comment by kltm** [comment]
I've been really happy with how robust and discoverable our pages have been with the server processing. Good for search engines as well. Moreover, the JS-only skip is not going to be true for much longer--spiders are starting to do JS anyways. It may not be be a big deal for NCBI though if they get advertising and have the capacity? Know somebody to ask there?

Anyways, a "widget" wouldn't really be what happens in this case, it would be a simple info getter that then feeds into something that recreates a page to be like /amigo/term and /amigo/bioentity.

Either way (client or server), it looks like it would be fairly easy to implement. If it's important enough, we could toss it in for 2.4.

**Comment by kltm** [comment]
Yeah, let me clarify that there: how much "advertising" would such a page need and should this be added for 2.4 (I'm guessing several hours for a first pass, but it may take a bit more for things like medial search to be hammered out)?

**Comment by cmungall** [comment]
> but it may take a bit more for things like medial search to be hammered out)?

I would make that a new ticket can punt it to 2.5

> It may not be be a big deal for NCBI though if they get advertising and have the capacity? Know somebody to ask there?

They're pretty responsive. It's standard practice to have a delay when running batch scripts, e.g

http://search.cpan.org/~cjfields/Bio-EUtilities-1.73/lib/Bio/DB/EUtilities.pm#delay

But of course we wouldn't be batch scripting here. This was the other reason to do client side. If done asynchronously the main page could render, then the metadata could appear after an acceptable user delay. But whatever you think best.

**Comment by kltm** [comment]
Another wrinkle here: I'd assume that pmid:xyz references would then generally refer to our own pages rather than kicking out to an external reference? Or would that be view-dependent? Depending on the answer, sorting that out (possibly creating new handlers) might take a little extra time.

**Comment by cmungall** [comment]
http://www.ncbi.nlm.nih.gov/books/NBK25497/#chapter2.Usage_Guidelines_and_Requiremen

In order not to overload the E-utility servers, NCBI recommends that users post no more than three URL requests per second and limit large jobs to either weekends or between 9:00 PM and 5:00 AM Eastern time during weekdays. Failure to comply with this policy may result in an IP address being blocked from accessing NCBI. If NCBI blocks an IP address, service will not be restored unless the developers of the software accessing the E-utilities register values of the tool and email parameters with NCBI. The value of tool should be a string with no internal spaces that uniquely identifies the software producing the request. The value of email should be a complete and valid e-mail address of the software developer and not that of a third-party end user. The value of email will be used only to contact developers if NCBI observes requests that violate our policies, and we will attempt such contact prior to blocking access. In addition, developers may request that the value of email be added to the E-utility mailing list that provides announcements of software updates, known bugs and other policy changes affecting the E-utilities. To register tool and email values, simply send an e-mail to vog.hin.mln.ibcn@seitilitue including the desired values along with the name of either a developer or the organization creating the software. Once NCBI establishes communication with a developer, receives values for tool and email and validates the e-mail address in email, the block will be lifted. Once tool and email values are registered, all subsequent E-utility requests from that software package should contain both values. Please be aware that merely providing values for tool and email in requests is not sufficient to comply with this policy; these values must be registered with NCBI. Requests from any IP that lack registered values for tool and email and that violate the above usage policies may be blocked. Software developers may register values of tool and email at any time, and are encouraged to do so.

**Comment by cmungall** [comment]
> I'd assume that pmid:xyz references would then generally refer to our own pages rather than kicking out to an external reference

Yes, you'd have to double hop to get to pubmed, just like for genes etc

**Comment by kltm** [comment]
Thank you for digging up the T&C. That's actually quite reasonable. I'll start a dialog with them and "register" either way, but it looks like it might go either way; although, certainly, the JS client method would be "safer" from our POV. Holding out hope for server though, I'll drop them a line and see.

**Comment by kltm** [comment]
Rushed draft here:
http://tomodachi.berkeleybop.org/amigo/reference/PMID:22835028
Not liking how the JS-only client is working, but it functions.

**Comment by kltm** [comment]
I'm not using JSOP there (as E-utilities does not accept it) and my "paranoid" browser blocks the ajax request. If the above URL doesn't work for you, try a more lenient setup.

**Comment by kltm** [comment]
Second draft, now with some internal routing for just PMIDs in most displays.

**Comment by kltm** [comment]
Morning meeting feedback from @cmungall indicates that this is fine as-is. As well, no feedback from NCBI about how we'd use their resources.
I'm still super unhappy with the current ajax-iness of it all, but I think out-the-door takes precedence over pretty much anything else at this point. If I'm still irritated, I'll revisit in the next release.

**Comment by kltm** [comment]
From email thread:
```
Would we want some kind of text "are you the author of this paper? If so does this look OK? Email us!" 
```
