### ISSUE TITLE
Re-enable round tripping with external Galaxy instances

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#358]
We previously operated under the assumption that we would operate our own Galaxy instance and that AmGO would interact *mainly* with it. With the de-prioritizing of the BBOP/GO Galazy instance, a lot of this code fell by the wayside.

At the request of @ndunn, we are looking at allowing an AmiGO instance to interact with non-BBOP or explicit Galaxy requests (as opposed to default ubiquitous internal ones that we had previously).

As a pilot, we'll add a button to [Upload to Galaxy] on /amigo/search/annotation pages for when the GALAXY_URL is well-defined. Clicking on this button will pass back the URL bookmark for the current search, allowing Galaxy to take the set GAF data.

Also tagging @cmungall .

**Comment by kltm** [comment]
@ndunn This will (should) work for tomodachi.berkeleybop.org/amigo/search/annotation, assuming you have a correct GALAXY_URL defined.
You'll need to add the correct trigger in you galaxy tools. I believe this is what our old one worked off of:
https://bitbucket.org/cmungall/galaxy-obo/src/e29c68304c23628cb474bf4ac5f778c31a456850/tools/data_source/general.xml?at=default&fileviewer=file-view-default
That URL will obviously need to be changed to the currently user one.

**Comment by kltm** [comment]
Whoops: @nathandunn.

**Comment by nathandunn** [comment]
I see so it round trips into Galaxy.   Do you use a tool with this? 

Nathan

**Comment by cmungall** [comment]
Yep - that's what the bitbucket URL is

**Comment by kltm** [comment]
Apparently not going to be used, but part of 2.4 release now with re-merge.

**Comment by nathandunn** [comment]
Yeah, sorry, I should have updated that.   Let me know if this ever starts up again.

**Comment by kltm** [comment]
What do you mean "starts up again"? The code is done...

**Comment by nathandunn** [comment]
Ah never mind.
