### ISSUE TITLE
Explore OLS solr index configuration to see if there are potential synergies

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#359]
https://github.com/EBISPOT/OLS/blob/master/ols-solr/src/main/solr-5-config/ontology/conf/schema.xml

We're fairly happy with our schema, but worth exploring alignments to see if there are synergies.

More relevant is the text search settings?

cc @simonjupp

**Comment by kltm** [comment]
IIRC, this is driven by BioSolr, which I got an overview about from @tonysawfordebi at the last GO meeting.
We will indeed be tearing some stuff up when we jump to Solr 5(?, 6?), so it would probably be good timing to revisit some stuff.
Already in the cards, and in the tracker, is to switch to ngram, or the lastest best...

**Comment by ValWood** [comment]
Assess value of searching comments and definition (current behavior), is this useful?
Examples?

PomBase curators and Kim will compare OLs to Canto for FYPO and OLS to QuickGO for our next few searches and report any problems.

**Comment by kltm** [comment]
A fair amount of time without action.

**Comment by cmungall** [comment]
@ValWood did you complete your analysis?

We will likely be adopting some configuration parameters from the EBI's BioSolr setup (being done by @jnguyenx )

**Comment by ValWood** [comment]
I had forgotten about this, but I haven't encountered any  ontology term search issues using QuickGO.....
