### ISSUE TITLE
Production AmiGO's metadata is out of date

### ISSUE THREAD

**Issue by monicacecilia** [geneontology/amigo#362]
Hi @kkarra 

I entered new data into [db-xrefs.yaml](https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml) (see [PR#196](https://github.com/geneontology/go-site/pull/196)), leaving AmiGO currently out of date. We'd like to have the production AmiGO instance updated (install or refresh steps) to pick up the new data. There are no code changes, only metadata.

Thanks in advance!

**Comment by kltm** [comment]
As there has been no action here, this will be solved when we hit 2.4 (which I'll push towards today).
