### ISSUE TITLE
Correct current issues with base statistics in AmiGO

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#364]
This is a continuation of some of the conversation on #242.
As it needs to be fixed in all versions, it will be marked "hotfix".
- [x] "Experimental annotations by assigner" should be "Annotations by assigner"
- [x] When E. coli is used for taxon, it should the closure, not direct. That should probably be generally true for all species in all views.
- [ ] There is an issue where "publication" numbers tend to get doubled as both PMID and GO_REF are counted in the facets. The fix is either manual counting in the cacher, or splitting them up at the schema level. Either way, an immediate fix may be hard to come by.

Additional needs should be added to this top level list, with a comment reference for discussion.

**Comment by kltm** [comment]
From @ValWood:

 - [ ]  first graph EXP by species has no cerevisiae?
 - [ ]  second graph  (EXP by assigner) is difficult to use because dwarfed  by automated GO central assignments from F-P links
- [ ]  Annotations by aspect/species by evidence is missing cerevisiae
- [ ] I think the numbers in EXP annotations by publication are incorrect. For pombe  you have 21,000 but we have curated <3000 publications, the number for SGD (91,000) exceeds the number of GO annotations. Flybase has 2 entries (FlyBase/FLYBASE)

**Comment by kltm** [comment]
@ValWood
The first issue was due to looking at direct annotations to the "head" of the head tree, rather than transitive annotations; this should now be fixed. @stuartmiyasato , could you confirm that running "gulp cache" is part of the periodic pipeline? If so, no further action is needed here and it will clear out on its own.
For the second, noted. In the meantime, you zoom in on the sections you want by drag-highlighting the area you want to view. There are all sorts of tools and fun that can be had within the graph boxes.
The third should also be fixed as above.
Finally, as mentioned in the opening of this ticket, part of the numbers issue is from the PMID/GO_REF double count. As well, it is an annotation count essentially, rather than publications. That can definitely be worded more clearly, and is probably not the most useful number anyways.

**Comment by stuartmiyasato** [comment]
@kltm Continuing the train of thought from #425 the amigo-base-statistics-cache.json file is being created on both production servers:

<pre>
amigo2a> ls -al perl/bin/amigo-base-statistics-cache.json
-rw-r--r-- 1 golr adm 8616 Mar 13 22:56 perl/bin/amigo-base-statistics-cache.json
</pre>

<pre>
amigo2b> ls -al perl/bin/amigo-base-statistics-cache.json
-rw-r--r-- 1 golr adm 8616 Mar 13 22:47 perl/bin/amigo-base-statistics-cache.json
</pre>

The timestamps seem to correspond with when I ran the "gulp cache" command manually.

Anything else you want me to check?

**Comment by kltm** [comment]
:blink: :blink:

**Comment by kltm** [comment]
@stuartmiyasato Ooookay. That's not what I would expect, but we're getting somewhere. Locally, aimed at the production GOlr, my file is:
```
sjcarbon@moiraine:~/local/src/git/amigo[master]$:) node ./scripts/amigo-create-base-stats-cache.js --server http://golr.geneontology.org/
sjcarbon@moiraine:~/local/src/git/amigo[master]$:) dir ./perl/bin/amigo-base-statistics-cache.json
-rw-r--r-- 1 sjcarbon sjcarbon 8686 Mar 13 23:54 ./perl/bin/amigo-base-statistics-cache.json
```
So, the sizes are different. Must be different information coming in then. Or you are running a different script. I guess the first question would be what is the `git status` in the directory of the machines(?) that are generating this file? I just bounced over to the `2.4.x` and the script looks right, except for the new server target flag, which I'll go ahead and add to help with the debugging.
The next thing is to see the contents of your config file that is on the machines that are producing this data file. If we can eliminate one or both of those, that would be good.

**Comment by stuartmiyasato** [comment]
@kltm 

```
amigo2a> git status
# On branch 2.4.x
# Changed but not updated:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   gulpfile.js
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	gulpfile.js.orig
#	perl/bin/amigo-base-statistics-cache.json.orig
#	scripts/amigo-create-base-stats-cache-new.js
no changes added to commit (use "git add" and/or "git commit -a")
```

```
amigo2b> git status
# On branch 2.4.x
# Changed but not updated:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   gulpfile.js
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	gulpfile.js.orig
#	perl/bin/amigo-base-statistics-cache.json.orig
#	scripts/amigo-create-base-stats-cache-new.js
no changes added to commit (use "git add" and/or "git commit -a")

```

The untracked files list is expected.  We modified the gulpfile.js file, so I keep the original copy around for reference.  I also kept a copy of the amigo-base-statistics-cache.json file around for reference when I ran the updated copy of amigo-create-base-stats-cache.js from github, but I apparently need to edit that file to work locally, so I renamed it to -new and put the original file back in place.

Which config file are you looking for?  amigo.yaml?

**Comment by stuartmiyasato** [comment]
@kltm Doing a "git pull" seems to have done the trick...

```
bash-4.1$ git pull
remote: Counting objects: 151, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 151 (delta 77), reused 75 (delta 75), pack-reused 69
Receiving objects: 100% (151/151), 12.30 MiB | 2.29 MiB/s, done.
Resolving deltas: 100% (93/93), completed with 38 local objects.
From git://github.com/kltm/amigo
   e4f7ad2..0740696  2.4.x      -> origin/2.4.x
 * [new branch]      cmungall-patch-4 -> origin/cmungall-patch-4
 * [new branch]      cmungall-patch-5 -> origin/cmungall-patch-5
 * [new branch]      issue-370  -> origin/issue-370
   29938bf..b9664dc  master     -> origin/master
Updating e4f7ad2..0740696
Fast-forward
 javascript/npm/amigo2-instance-data/package.json |    2 +-
 javascript/npm/bbop-widget-set/package.json      |    2 +-
 javascript/web/GeneralSearchForwarding.js        |    2 +-
 package.json                                     |    2 +-
 scripts/amigo-create-base-stats-cache.js         |   15 +++++++++++----
 5 files changed, 15 insertions(+), 8 deletions(-)
```

Now S. cerevisiae shows up on the annotations graph.  I'll hold off updating amigo2b until I hear back from you, just in case you want to do further comparisons...  Thanks!

**Comment by kltm** [comment]
Yes, that's good then--production was just a little behind on the fixes to 2.4.x, so that should do it. Looking at the history, the only other fix in there, besides versioning, should be for https://github.com/geneontology/amigo/issues/383, which I didn't know I put onto the 2.4.x branch (marked 2.5.x).

I think that his is probably good to push out as-is, which will correct the graphs. You will not get the #383 fix without a recompile (`npm install && gulp install`), but nothing bad will happen either.

**Comment by stuartmiyasato** [comment]
@kltm Okay, I have applied the changes to amigo2b and it seems to have worked there as well.  Thanks.

Unrelated, but I was trying to download one of the statistics graphs and it failed in Safari and Chrome ("Sorry there was a problem downloading your png"), although it succeeded in Firefox.  Not sure if this is a specific problem with production, or if it's worth mentioning in a new issue or not...

**Comment by kltm** [comment]
Thank you!

For your other issue, I've open and commented on #426.

Otherwise, for the scope of this item, I think we're done.

**Comment by kltm** [comment]
While currently closed, I want to highlight that ""Experimental annotation publications by
assigner" on the base_statistics page is still quite confusing. We should look into removing/rectifying/clarifying that at some point as questions do come up. As an example of what could be done better numbers-wise using TAIR as an example:

```javascript
var request = require("request");
var us = require("underscore");

var url = "http://golr.geneontology.org/select?defType=edismax&qt=standard&indent=on&wt=json&rows=0&start=0&fl=bioentity,bioentity_name,qualifier,annotation_class,annotation_extension_json,assigned_by,taxon,evidence_type,evidence_with,panther_family,bioentity_isoform,reference,date,bioentity_label,annotation_class_label,taxon_label,panther_family_label,score,id&facet=true&facet.mincount=1&facet.sort=count&json.nl=arrarr&facet.limit=-1&fq=assigned_by:%22TAIR%22&fq=evidence_subset_closure_label:%22experimental%20evidence%22&fq=document_category:%22annotation%22&facet.field=reference&q=*:*";

var res = null;
request({
    url: url,
    json: true
}, function (error, response, body) {

    if (! error && response.statusCode === 200) {
	res = body;
	//console.log(body);

	console.log('---');
	console.log(us.reduce( res.facet_counts.facet_fields.reference,
			       function(memo, facet){
				   return memo + facet[1];
			       }, 0));
	console.log(us.reduce( res.facet_counts.facet_fields.reference,
			       function(memo, facet){
				   return memo + 1;
			       }, 0));
	console.log(us.reduce( res.facet_counts.facet_fields.reference,
			       function(memo, facet){
				   if( facet[0].substr(0, 4) === 'TAIR' ){
				       return memo + 1;			       
				   }else{
				       return memo + 0;
				   }
			       }, 0));
	console.log("---");
    }
});
```
