### ISSUE TITLE
Add better user interaction for feedback and annotation and ontology corrections

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#365]
This is a product of the http://wiki.geneontology.org/index.php/Data_Capture_Working_Group meeting on 2016-07-13.

The current community feedback mechanism is the "Community" field and GO Nuts.

The intention is to make minimal functional changes to enhance the UX; small enough that we can squeeze it in to the current release, if possible.

An ideal solution (from the POV of this ticket) would be:

- [ ] adding an eye-catching element to the summary/information section, that leads to the appropriate GO docs and/or go-helpdesk
- [ ] Moving the "community" section to there or otherwise making it more clear

Verbiage ideas:
- "Data community"
- "Your data"
- "How's the data?"
- "Data health [first aid icon]"

**Comment by kltm** [comment]
@cmungall Could I get some quick feedback from you on this?
* http://tomodachi.berkeleybop.org/amigo/term/GO:0008219
* http://tomodachi.berkeleybop.org/amigo/gene_product/UniProtKB:P06702
* http://tomodachi.berkeleybop.org/amigo/reference/PMID:12626582
We need to fix the contact page now, make it friendly, but it should now be more obvious what we want users to do.

**Comment by kltm** [comment]
Still need to backport to 2.4.x...or just get 2.4.x onto master again.

**Comment by cmungall** [comment]
"term usage" is confusing for gonuts. I think it's maybe time to move gonuts to something like the xref section.

"data health" :heart: is cute but a bit too developerry. I think something like "give us feedback ont his would be better

**Comment by kltm** [comment]
I worry about the use of phrases like "feedback" in this case. Not only do we use it elsewhere on the page in a different sense, it strikes me as more page/UX-oriented, rather than "data right here right now". I think you're right that "data health" might be not quite right; what about the other ideas in https://github.com/geneontology/amigo/issues/365#issue-165418443?

**Comment by kltm** [comment]
Merged 2.4 with master again, so it got picked up there.
