### ISSUE TITLE
Ensure non-redundancy in neighborhood view

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#366]
This issue is a budding off of https://github.com/geneontology/amigo/issues/360#issuecomment-227564958

The neighbor/display-sentences-tab displays what are apparently redundant relationships
http://tomodachi.berkeleybop.org/amigo/term/GO:0072442#display-sentences-tab

Same for any graphical views
http://tomodachi.berkeleybop.org/visualize?inline=false&term_data=GO%3A0072442&format=png&mode=amigo&term_data_type=string

This is not an amigo issue per se. It is to do with how owltools assembles the bbop-json graph that amigo is displaying.

Briefly: owltools includes the genus from an equivalence axiom, even though this may be redundant with an inferred relationship. It does this because omitting this is not guaranteed safe unless we have guarantees that a composition of `reason o relax o reduce` has been performed. Previously this was not done in the GO pipeline, now it is. So in theory it should be safe to change the behavior. We'll need to set aside some time for testing here.

We could also have amigo be defensive and perform its own reduction. We could do a more aggressive transitive reduction.

If you don't fully understand this ticket it's in part because documenting this is its own unfulfilled ticket here: https://github.com/ontodev/robot/issues/85

**Comment by cmungall** [comment]
Example of problem:
http://amigo.geneontology.org/amigo/term/GO:1990086#display-lineage-tab

The link to apoptotic process (GO:0006915) is redundant

go-plus has been pre-reasoned and relaxed and reduced, the subclass structure only should be removed

this is the problem:

https://github.com/owlcollab/owltools/blob/41e1f585d7a8135081c3f2e56c4aa6590901227b/OWLTools-Core/src/main/java/owltools/graph/OWLGraphWrapperEdges.java#L346-L351

**Comment by kltm** [comment]
Will leave re-opened until confirming test in local AmiGO installation.
As well, we're interested in if this is a dupe with #360 .

**Comment by kltm** [comment]
@cmungall 
After an owltools rebuild and local reload, I'm still getting:
```
 lens fiber cell apoptotic process 	[occurs_in relation] occurs_in  	lens fiber cell (CL:0011004)
lens fiber cell apoptotic process 	[is_a relation] is_a  	epithelial cell apoptotic process (GO:1904019)
lens fiber cell apoptotic process 	[is_a relation] is_a  	apoptotic process (GO:0006915) 
```

**Comment by kltm** [comment]
Talking to @cmungall , but it appears that https://github.com/geneontology/amigo/issues/366#issuecomment-282159691 may be a bit of a red herring.
Looking at tomodachi vs. production, the gross case of the topology graph under biological_process does indeed seem to be fixed.

@cmungall Are we okay with https://github.com/geneontology/amigo/issues/366#issuecomment-282159691 ?

**Comment by kltm** [comment]
Reconfirming problem exists on owltools
```
sjcarbon@moiraine:~/local/src/git/amigo[master]$:) java -jar ./java/lib/owltools-runner-all.jar --version
git-revision-sha1	46ba4782a5020513d2c58b10c62b2a1befa1dc17
git-revision-url	https://github.com/owlcollab/owltools/commit/46ba4782a5020513d2c58b10c62b2a1befa1dc17
git-branch	46ba4782a5020513d2c58b10c62b2a1befa1dc17
git-dirty	true
```
https://github.com/geneontology/amigo/issues/366#issuecomment-282159691

**Comment by kltm** [comment]
For my local test load, I have:
```
    - http://purl.obolibrary.org/obo/go/extensions/go-gaf.owl
    - http://purl.obolibrary.org/obo/eco.owl
    - http://purl.obolibrary.org/obo/go/extensions/go-taxon-subsets.owl
```

**Comment by kltm** [comment]
Upping severity as it affects dd_browse rather severely.

**Comment by cmungall** [comment]
I think this is caused by redundancy in go-plus, which will be fixed by, 
https://github.com/geneontology/go-ontology/pull/14424
likely tonight

**Comment by kltm** [comment]
Well...at some point we cleared this...
Things seem fine now given the above context.
