### ISSUE TITLE
Linkouts for SO terms going to the wrong pages

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/amigo#367]
Hi,

It looks like the linkouts for SO terms are going to an old URL.

I just clicked on a SO term (SO:0001850) displayed in an Annotation Extension and it took me to this page:

http://song.sourceforge.net/SOterm_tables.html#SO:0001850

but probably should have gone here instead:

http://www.sequenceontology.org/browser/current_svn/term/SO:0001850

--Kimberly

**Comment by kltm** [comment]
@vanaukenk This is not an error in AmiGO, but the metadata/users.yaml file in the go-site repo. This item will be kept open until resolution there, but in the future you may want to just open "link" issues in the go-site tracker.

@cmungall That "current_svn" is a little worrying; more so than "cgi-bin", unless "svn" has a particular meaning to them?

**Comment by cmungall** [comment]
On 27 Jul 2016, at 14:41, kltm wrote:

> @vanaukenk This is not an error in AmiGO, but the metadata/users.yaml 
> file

db-xrefs, SO is not a user :-)

https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml

> in the go-site repo. This item will be kept open until resolution 
> there, but in the future you may want to just open "link" issues in 
> the go-site tracker.
>
> @cmungall That "current_svn" is a little worrying;

Indeed

**Comment by kltm** [comment]
@cmungall Too many YAML files today...
Does anybody want to ping SO to make sure that's what they want, or should we just go ahead with the wacky URL?

**Comment by vanaukenk** [comment]
@kltm - thanks; I'll use the go-site tracker for any stuff like this in the future.
Do we still want to contact SO?  I'll do that, if needed.

**Comment by kltm** [comment]
Looking at you, @cmungall -- it's all the same to me in the end...

**Comment by kltm** [comment]
Any takers?

**Comment by cmungall** [comment]
Use the OBO PURL

**Comment by kltm** [comment]
@stuartmiyasato @kkarra I believe that the correct info should now be in the file; after you update (gulp install or gulp refresh IIRC), could you close out this ticket?

**Comment by stuartmiyasato** [comment]
Sorry, this got lost in the whole 2.4.x upgrade.  I have upgraded production and it looks okay to me, but I'd like another pair of eyes to look at the results before we close out this ticket.  Can someone (like @vanaukenk) verify that SO:0001850 now links to the proper URL?  Thanks!

**Comment by kltm** [comment]
I've confirmed that this works looking at: http://amigo.geneontology.org/amigo/gene_product/UniProtKB:Q9Y618
Cheers!
