### ISSUE TITLE
Allow "search" in gene-to-term in API (can labels be used as arguments to information resources?)

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#369]
From @elserj :

We'd like to be able to search the /api/statistics/gene-to-term with something other than bioentity.  Reason being that in general, users are not going to be searching with the bioentity.

We figured out that it would be possible to combine /api/search/annotation and gene-to-term, but this seem really inefficient.  It looks from the search that if we could search by "bioentity_label", we could get what we want.

For example, we currently search for a term with the following URL:

http://test.planteome.org/api/statistics/gene-to-term?bioentity=TAIR:locus:2146569

But we then need to know the bioentity is "TAIR:locus:2146569".

We think that most users will instead have something like an AT number such as "AT5G28400".

We can find the bioentity by using:

http://test.planteome.org/api/search/annotation?q=AT5G28400

and grabbing the data<bioentity_label>, but this is inefficient.

It would be much better if we could have a URL such as

http://test.planteome.org/api/statistics/gene-to-term?bioentity_label=AT5G28400

but this currently doesn't work.

My guess is that this could be added by modifying /bin/amigo.js in the "app.all('/api/statistics/gene-to-term'" function by adding bioentity_label stuff similar to how bioentity is already there, but I'm not sure that is all there is to it.  Thought I'd ask you since you would know better what would be needed.

I can create a ticket for this, but thought I'd check with you first.  I'm also willing to code it out and submit a PR if you don't have time, if you could just point me in the right direction to where to add it, or if there might be weird issues from trying to implement this.

**Comment by kltm** [comment]
The main issue here is that symbols (what gets mapped to label a lot) are not particularly unique. While any example that you give *may* be unique, it is certainly not generally true, which is why the information part of the API relies on the canonical ID as the method to extract information--it is an info service, not a search service.

What you are doing is something that I would mark as the "correct" method: search for the label, or whatever hook you want, if it is unique, get the info, if it is non-extant or ambiguous (more than one answer), throw an error. In client or server JS, that should just be a single nesting in initial resolution process, and hopefully not too cumbersome.

Anyways, that's my initial though on the issue. Is there a particular speed problem you're running into to get the canonical ID from the search? The two-hit method would indeed not be ideal for attempting something instantaneously.

**Comment by elserj** [comment]
I agree about the non-uniqueness.  Could it be possible to enforce it so that querying over these terms also requires a taxon to be specified?  That should limit most of the overlap, I think.

Well, I bring up the inefficiency as we are looking to do this for possibly thousands of genes/bioentities for a web page.  We already have some speed issues and I can imagine processing it with double the API calls will make it worse.  

To be clear, I said that we figured out it was possible to do it with the /api/search, but we haven't actually implemented it.  Waited to hear back on this request first.

**Comment by kltm** [comment]
*species* is already an option...although I'm not honestly sure why it's already there in the API. Maybe it's over-enthusiastic copying from the term-to-gene service, which makes sense. Anyways, even with that, let's say, for example, the API user inputs human and "numa1", the stored data might look like:

http://amigo.geneontology.org/amigo/search/bioentity?q=numa1*&fq=taxon_subset_closure_label:%22Homo%20sapiens%22&sfq=document_category:%22bioentity%22

You can see that we may or may not still be talking about a bunch of different entities, that may or may not be tied to various terms given other parameters.

On a slightly different note, are you intending on hitting the API thousands of times as a caching step, or is the intent to do that live? If the latter, I do not believe there is a workable solution for that without writing your own proxy and aggressive tuning. For our own live tools that hit the backend merely hundreds of times (and since you are not allowed unlimited connections from most browsers), there is a batching implementation in the manager, which we couple with a loading bar. Actual processing can still take minutes.

If you'd like, it might be good to touch bases on skype or something to get more details about the use case and see what can be done.

**Comment by kltm** [comment]
Closed in favor of #370 .

**Comment by kltm** [comment]
(note the the example(s) given above change and might not work due to current production golr load issues)
