### ISSUE TITLE
Create an entity disambiguation service for the API

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#370]
This follows from the call to talk about the issues around #369 . Talking to @qubotong @elserj and @cmungall .

The takeaway from the call is that we want to have the API support an entity disambiguation service that is functionally almost identical to what the old AmiGO term enrichment service provided. The fields to be scanned would be either user provided or work from defaults; they would be prioritized and short circuit (e.g. if label > synonym, then if an exact label match is found, it does not try to match synonym). Input would be at least a list of strings and a species/taxon id. Output would be something like:

``` json
{
 "good": [
  {"input": "bar", "results": [{"id": "YARG:0022002", "matched": "bio_label"}]}
 ],
 "bad": [
  {"input": "bar", "results": []}
 ],
 "ugly": [
  {"input": "bar", "results": [
    {"id": "YARG:0022003", "matched": "bio_syn"}, 
    {"id": "YARG:0022004", "matched": "bio_syn"}]}
 ]
}
```

Speed will be important, so we're going to tilt it towards elimination from the to-try pool as we progress, rather than a complete result (which is why we have an ordered "try" list). 

Bonus points will be given for creating a "session" endpoint in the API that, when a long-running command is given, dynamically creates a REST endpoint a la /session/234234234 that is reported back to the user in the initial response. This endpoint can then be polled for results, as well as information about completion status. It may be best for the endpoint to then self-destruct after the first hit after completion.
This bonus material is not necessary for completing this ticket, and may be better served as its own feature request.

**Comment by kltm** [comment]
The opposite (or extension) of this would fit the use case of id -> name/label for @mugitty .

**Comment by elserj** [comment]
Just wondering if there was an update on this.  Can we help out at all?

**Comment by kltm** [comment]
My apologies: unfortunately, not a lot of progress here--there has been some AmiGO work done recently, but no time on the API.
What kind of time pressure are you currently under? Is this a blocker for another item?

**Comment by elserj** [comment]
Just checking in again to see if this had made any progress.  It is sort of a blocker for the gene enrichment project Botong is working on.  We are currently working on some visualization issues, but I think before we can really open this up for use, we will need to have this working as I don't think users will be using internal ids, which is what we are currently using for testing.

**Comment by kltm** [comment]
@elserj Unfortunately, there has been no bandwidth for this. You might want to have @jaiswalp touch bases with @cmungall to make sure that priorities are aligned.

**Comment by jaiswalp** [comment]
@cmungall this is delivery on the project. I suggest bumping this on priority. It will also help other GOC users as well.

**Comment by kltm** [comment]
Some planning with @cmungall .
As a possible way to to get around the http overhead, we're going to implement a species-level cache of all documents and desired fields for disambiguation. I'll try and set something up so that the cache is flushed within a certain time period; as well, look at having a warmup set for common or large species at startup time.

**Comment by cmungall** [comment]
Apologies for the radio silence, we had the GO meeting and we need to make changes in advance of persona going down end of Nov, which is a hard deadline.

We're on this right now. FYI, here is our strategy:

 - The API will take an NCBITaxon ID (required) plus a list of strings (with additional config options later)
 - The server will do an initial (possibly memoized) query to solr on the bioentity document type, pulling all IDs, labels, syns, fullnames for that species (typically max 20k entries see comments below). I'm guessing <1s with solr
 - We will do an in memory traversal of the returned structure, matching against different fields, return a json object the same structure as above (milliseconds)

We're juggling a number of different things here, but should have something to report next week

In writing this, I realized something else we need to take into consideration. Do you have good representative gene lists for each genome? This is required for meaningful statistics.

**Comment by kltm** [comment]
I have not tested this for very large inputs yet, but things seem to be working as expected.

**Comment by kltm** [comment]
For the time being, the current search field set is:

```javascript
var bioentity_search_fields = [
    "bioentity",
    "bioentity_label",
    "bioentity_name",
    "bioentity_internal_id",
    "synonym"
];
```
With _bioentity_ assumed to be unique and ubiquitous in the GOlr documents.

This, however, is easily parameterized.
