### ISSUE TITLE
Grebe / Search templates broken in production

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#373]
http://amigo.geneontology.org/grebe

Regardless of which template is chosen, filling in a value has no effect. It takes you to a page with all annotations in golr

**Comment by kltm** [comment]
Confirmed and serious. Closing code will need to add unit test.

**Comment by stuartmiyasato** [comment]
Is this functionality also broken on amigo2-test.stanford.edu or does it work properly there?

**Comment by kltm** [comment]
Borked on test as well. Probably something trivial... Grump grump...

**Comment by kltm** [comment]
The new query bookmark, oddly, never seems to make it to the live search page. Some error in construction / liftoff on the generating page then.

**Comment by kltm** [comment]
Re-merged from master to try and get the latest fixes.

**Comment by kltm** [comment]
@stuartmiyasato I'm not going to have a complete testing platform for a bit (nakama is reloading, and I'm not sure it will take). Could you get the latest 2.4.x onto amigo2-test so I could take a whack at it before promoting the (very small change) to production?

**Comment by stuartmiyasato** [comment]
@kltm I just installed the latest 2.4.x on amigo2-test.  I did not reload data so that is kind of old, but that shouldn't affect your ability to test the code, correct?  Let me know if you need a new data load as well.

**Comment by kltm** [comment]
GOOSE still loads slowly and the counts are off, but those are expected. This is now ready for production.

That said, we now have a new "hotfix" issue to deal with, so give me a few minutes to make that update before a production push. #364
