### ISSUE TITLE
Need to update NCBI E-utilities calls to use HTTPS

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#374]
We need to update the E-utilities calls to https within the next month.

Context:
```
Dear Colleagues,

As we announced on June 10, 2016 (https://www.ncbi.nlm.nih.gov/news/06-10-2016-ncbi-https/), NCBI will be transitioning to using HTTPS-only protocols on September 30, 2016. This change may affect any software that uses NCBI APIs such as the E-utilities or NCBI software toolkits such as the C/C++ and SRA toolkits.

Based on a review of incoming API requests, we have identified your email address as being associated with API calls using the HTTP protocol. We are writing to ensure that you are aware of these upcoming changes so that you can make any necessary updates to your software. If you are not making such calls, please disregard this message and accept our apologies.

Recently we published a page that describes these changes and offers suggested actions you can take to mitigate any problems with your software that may arise. It also lists several test servers that you can use to check the performance of your current API calls.

http://www.ncbi.nlm.nih.gov/home/develop/https-guidance.shtml

This page is also linked from the NCBI Develop page (a direct link from the NCBI home page) and the NCBI API page:

http://www.ncbi.nlm.nih.gov/home/develop/
http://www.ncbi.nlm.nih.gov/home/develop/api.shtml

Please review these documents and plan to take action soon. If you have questions, please write to abc@xyz.
```

@cmungall Are you using E-utilities anywhere else?

**Comment by kltm** [comment]
@stuartmiyasato Could you put the code on amigo2-test again so we can check it again? I think this is it for the hotfixes for now.

While things are looking good again for testing automation, our local tests are currently all failing due to no mysql mirror for GOOSE being currently available. Annoying, but we'll test around it.

**Comment by stuartmiyasato** [comment]
@kltm I updated the code on amigo2-test and reinstalled.  It should be ready for testing.

**Comment by kltm** [comment]
@stuartmiyasato Well, I'm going to give up on the behave tests for now--the more I fiddle with and correct them, the more breakage there is. This seems to be an unpleasant consequence of switching to phantomjs from the firefox driver; unfortunately, they are both broken, but in lovely different ways.
Besides the ever-irritating GOOSE, failing tests work work when retrying in browser, so good enough.
Good for production for me.

**Comment by stuartmiyasato** [comment]
I was able to upgrade the production machines.  @kltm can you test production to make sure the desired fuctionality works correctly?

**Comment by kltm** [comment]
Looking at http://amigo.geneontology.org/amigo/reference/PMID:8224193, it all seems good. The test set works fine as well. Thank you!
