### ISSUE TITLE
Lablelling "regulates closure" not good for general users, and make GO term name visible

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#377]
Here,  
1. Is the wording "regulates closure" necessary? Would the label "term" not be better?, or does this  mean something else (the fact that 'regulates annotations are included here could probably be under a help icon?, or if required (includes is_a, part_of and regulates relations).
2. Could we spell out the GO term, there is nowhere on this page to see the term you have searche on (i.e here "mitotic cell cycle")

![acc name](https://cloud.githubusercontent.com/assets/7359272/17738403/040174d8-6489-11e6-88b1-a75e456b6aa1.jpg)

**Comment by kltm** [comment]
This is a general issue around how the filtering widget is structured. I am certain that there is a ticket already about this (forgetting which repo); it is a known issue that will be addressed when the widget is next re-written.
