### ISSUE TITLE
Increase default results count from 10 to ?

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#378]
Could we increase the default display number here (personally I dislike the page scrolling, I would prefer to see all of the results at once, or at least as high a default as possible, is this prohibitive?). 
At the moment the maximum is 100  per page (this would be a more useful default, but its still often too low).

This would  also not be *quite* so annoying if the filters were 'sticky'
Currently none of the filters are sticky.
So if I have filtered on "pombase", and switched the filter to show  100 annotations, if I then access a gene product, and then go back to this page using the back button, I need to reset both the organism and the result count  to  100

![acc name](https://cloud.githubusercontent.com/assets/7359272/17738755/8d006914-648a-11e6-95d9-4c32262a0059.jpg)

**Comment by kltm** [comment]
@ValWood There is a cost to increasing the default number per page. As well, I've talked to other users who prefer to be able to quickly filter to get to the results they want, rather than having the slower response/render time of 100 results.

The "stickiness" would be #339 or #50.

**Comment by ValWood** [comment]
I don't know how a filter would work for most terms? If I want to see the genes annotated to mitotic cell cycle,  or chromosome segregation for most organims its going to be over 100 genes.  I guess this might work as an option for an organism with little annotation, or for a leaf node term, but its not a universal  solution.
v

**Comment by ValWood** [comment]
How many users did you poll?

**Comment by kltm** [comment]
Informal feedback during initial development for widget, likely less than a half-dozen, but no formal notes.

**Comment by cmungall** [comment]
Responsivity is important, I don't like having to wait for annotations 
if I just want to jump to a term page and see the term info (and maybe a 
distribution over species or something)

However, when I do want to look at annotations, the 10 is rarely 
satisfying. I typically set my filters then max out the limit (unless 
it's a rare case when we have a very specific term with only a handful 
of annotations in the species of interest). The lack of stickiness 
probably bothers me less as I have a different usage pattern.

Not sure what the answer is, but just that I don't think it's unusual to 
want to pack your screen with as much information as possible and/or use 
browser scrollbars.

There are undoubtedly smarter ways to compact this too, but lots of us 
still like big lists.

**Comment by kltm** [comment]
Again, this will all be sorted out with some stickiness in the bookmarking/url tickets mentioned above.
