### ISSUE TITLE
Intensely confused by "direct anntotation" and "inferred annotation"

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#379]
I mentioned this a year or so ago and I didn't get around to submitting a ticket about it.
I still find this behavior very confusing. I'll try to explain.....
1. I search on a term  "mitotic cell cycle" and filter on "Pombase"
2. I  access gene products, I get 430 results (correctly)
3. I don't understand what the  filters 'direct annotation' 
   see image
   ![still confusing-mitotic cell cycle](https://cloud.githubusercontent.com/assets/7359272/17738921/2161a596-648b-11e6-8b10-1ed303674d87.jpg)

or
inferred annotation
![inferred](https://cloud.githubusercontent.com/assets/7359272/17738942/33571e48-648b-11e6-8c0d-8353039a37bb.jpg)
are telling me in this context.

They both show  high level CC terms like 'cell' cell part' 'intracellular', or function terms like "protein binding'

One thing I am sure of  is that these annotations do not have any relationship to the term I have searched on, in the ontology:

![mitotic cell cycle](https://cloud.githubusercontent.com/assets/7359272/17739030/9700557c-648b-11e6-9026-8acae021110e.jpg)

What we appear to be presented with here is " the complete parentage of _ALL_  of the annotations for all the genes in your list"...I am unclear what the use case for this interpretation of  "direct anntotation" and "inferred annotation" (or the difference between the 2). To me these phrases  do not  describe what is being displayed, and if it has been requested it seems like some advanced functionality that should probably be hidden from the average user (or correctly described?).

Can anyone explain exactly what is meant by
"direct anntotation" and "inferred annotation" in this context. I  think the phrase to describe this  is closer to "co-annotated terms"- ( i.e gene products annotated to this term are also frequently co-annotated to this term). If this is the case, I'm not convinced that an annotation filter is the best place for this,  it is very unintuitive.....

**Comment by ValWood** [comment]
@ukemi

**Comment by kltm** [comment]
Duping onto #443
