### ISSUE TITLE
Graph image download from QuickGO apparently broken

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#381]
Does not show graph view. Link takes you to QuickGO but not to graph view.

**Comment by kltm** [comment]
Duplicate:
Start at http://amigo.geneontology.org/amigo/term/GO:0044195, click on [Graph Views], there should be a cached image from QuickGO available.

**Comment by kltm** [comment]
Cannot resolve http://localhost:9999/visualize?term=GO:0022008&beta=0&inline=false&mode=quickgo !

**Comment by kltm** [comment]
@stuartmiyasato I merged in from master again, with the fix for better filesystem persmissions during cache creation. This fix worked out-of-the box for tomodachi and nakama. 

I'm noting that this isn't a problem on http://amigo2-test.stanford.edu/amigo/term/GO:0022008 (then click [Graph Views]), but there is still a problem on http://amigo.geneontology.org/amigo/term/GO:0022008 (then click [Graph Views]). Not sure the right way to test that for you, but unit tests are passing here (as well as they every do these days) on tomodachi, which it closest to your setup. Maybe one machine first?

**Comment by stuartmiyasato** [comment]
A bit of an aside, but possibly related for testing purposes -- the image appears broken to me for http://amigo2-test.stanford.edu/amigo/term/GO:0022008.  @kltm can you try clearing your browser cache and see if the image still works for you?  I'm going to try a couple other browsers, but it appears broken on test and in production for me.

**Comment by kltm** [comment]
Well, broken now, even without a refresh. Who knows. All the better for testing though.

**Comment by stuartmiyasato** [comment]
@kltm Okay, I am going to update test first then...  Will let you know when it's done.

**Comment by kltm** [comment]
amigo2-test looks good to me now.

**Comment by stuartmiyasato** [comment]
@kltm Ha, I was still running "gulp cache" when you responded.  :)  Okay, I'm going to do amigo2a in production now.  If that looks good, I'll do amigo2b after.

**Comment by kltm** [comment]
Great--thank you! The unit tests on amigo2-test are looking okay (-ish, except for some race conditions which manually test fine and the counts, which are to be expected).

**Comment by kltm** [comment]
amigo2a looking good, and tests are as expected.

**Comment by kltm** [comment]
amigo2b looks good as well. also looked at amigo...I think you're done rolling it out? I'm seeing 2.4.24 everywhere now.
Thank you for your help with the quick rollout!

**Comment by kltm** [comment]
Hm, I just lost 2.4.24 to 2.4.22, and amigo2b is gone. I'll just wait until you're done--sorry ;)

**Comment by stuartmiyasato** [comment]
@kltm I ended up reinstalling on amigo2b.  /tmp/cache wasn't getting updated.  I suspect it was related to permissions.  I wiped the directory and reinstalled.  amigo2b looks better now.

**Comment by kltm** [comment]
On amigo2a, it looks like you might be two minor versions behind (2.4.22 vs 2.4.24). I think testing is probably going to be good either way now as the correct directory permissions were initiated.
Otherwise, everything is looking fine.

**Comment by stuartmiyasato** [comment]
Not sure what happened there...  git pull showed everything was up to date.  Anyway, I did a reinstall on amigo2a and it's now showing up with version 2.4.24.  Hopefully everything is good now.

**Comment by kltm** [comment]
Looks good to me--thank you for all the scramble!
