### ISSUE TITLE
Autocomplete displays html entity encoding instead of character

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#383]
![amigo_bug2](https://cloud.githubusercontent.com/assets/7359272/18316596/22ad4e3a-7513-11e6-86e2-a88b0d5a2268.jpg)

**Comment by kltm** [comment]
Huh, I thought we had this somewhere already... @jnguyenx, would you remember if this was captured somewhere, or something we just ran across while testing the Solr 6 stuff?

Either way, the full description is that, either in the index or in the display, there is some kind of impedance mismatch with the html entities and the display code. Although other character sets seem to display just fine (#260).

IIRC, this is fixed at the Solr level, expected with the Solr 6 upgrade.

**Comment by kltm** [comment]
Correct on disk and over wire "negative regulation of mRNA 3'-UTR binding".
