### ISSUE TITLE
The slim service for AmiGO 1.x does not complete on some inputs

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#384]
I can't get
http://amigo1.geneontology.org/cgi-bin/amigo/slimmer
to run to completion on pombe input list

I wanted to check whether  the slim now provides  the list of "unslimmed" GP's 
(this is critical to  use a slim)

**Comment by ValWood** [comment]
note the  amigo1 url is where you get to if you follow the link from here
http://amigo.geneontology.org/amigo/software_list

**Comment by kltm** [comment]
@ValWood Unfortunately, long story short, the legacy slim interface is no longer supported and only offered as a best-effort for people and groups that are running sets small enough to run to completion on the current hardware; a small test of random input returned results. Your input is probably large enough that it cannot complete in the allotted time, causing a timeout somewhere along the way. It's possible that multiple runs might help warm up the database enough that it can complete, but that is rather marginal advice.

While there is no usable web interface currently officially offered, the official tool is through OWLTools:
http://geneontology.org/page/go-slim-and-subset-guide#Map2Slim_option_in_OWLTools
