### ISSUE TITLE
AmiGO should exclude regulates relationship from enrichment tool by default

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#386]
Doesn't anyone else find this odd default behavior for the enrichment tool?

http://jira.geneontology.org/browse/GO-1335

Val

I heard back from MGI, and they think the difference is probably a result of the regulates relationship. When you use the enrichment tool on AMIGO2, they apparently exclude genes annotated to regulates children, but when you search AMIGO2 using the GO term it does return the genes annotated to regulates cild term. For example, 'regulation of somitogenesis' is a child term of 'somitogenesis', and this is a child of 'segmentation'. This regulation term would not be considered in the enrichment but would be included in the results when you search ith a term string. When I took the lists of genes returned from the enrichment (97) and compared them to the list associated with the term (103), the genes in the difference are all annotated to some kind of regulation of X where X is a child of segmentation, but they are not annotated to any isa or partof children of segmentation.
Some of the enrichment tools out there such as the GO Term Finder at Princeton (http://go.princeton.edu/cgi-bin/GOTermFinder) by default follow these terms, and if you look down the page to the advanced options, you see a toggle called ‘Follow regulation links’. So when it looks for all the genes annotated to a term, it includes all the genes annotated to regulation of that term. It appears that this is not the behavior of the AMIGO2 tool.

**Comment by kltm** [comment]
The AmiGO 1.x enrichment tool is no longer supported and it does not take into account pretty much anything. If you are referring to the PANTHER tool that we link out to, you'd probably want to contact them directly.

**Comment by kltm** [comment]
Pinging @ValWood @mugitty .
