### ISSUE TITLE
"full text search" retrieving spurious GPs

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#387]
There are 648 pombe genes annotated to "cell cycle" 
When I do an ontology search on "cell cycle" I retrieve these 648 genes.

However when I do a full text search I retrieve 688 genes.
All of the  real cell cycle genes are included

![overlap](https://cloud.githubusercontent.com/assets/7359272/18624601/ee6e3332-7e40-11e6-81e4-674a033e1d3b.jpg)

**Comment by ValWood** [comment]
These are some of the GPs which are not "cell cycle associated
SPAC3A12.09c
SPBC8E4.03
SPAC1952.11c
SPAC17A2.05
SPAC24C9.06c
SPCC18.18c
SPAC29A4.13

This is my best guess is that these have some annotations which contain the word "cell" and some which contain the word "cycle" 
(all of the ones I looked at were nitrogen cycle, or TCA cycle)

**Comment by ValWood** [comment]
![mitotic_cell_cycle](https://cloud.githubusercontent.com/assets/7359272/18625771/9c5e5f2e-7e48-11e6-8a33-374b56d7fd5e.jpg)
Similarly if I search on "mitotic cell cycle"
The free text search gives my 40 spurious hits

**Comment by ValWood** [comment]
Hmm for the mitotic one most are probably caused by this missing parent:
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0071851#term=ancchart

**Comment by ValWood** [comment]
Most of the rest  are due to annotations to "mitotic spindle pole body"
 and "meiotic cell cycle"

Some of these we know are meiosis specific. The "meiotic spindle pole body" annotations are because this ORFeome data was   expressing these genes during vegetative growth

I am working on a clean up of these
https://github.com/pombase/curation/issues/791

Although in general, I wonder if it makes sense to take a search string "mitotic cell cycle" and 
look for separate occurrences  of the composite strings "mitotic" and "cell  cycle"  for the same gene product ?

**Comment by kltm** [comment]
@ValWood If you are looking for things with text, that is the free text filter and it may pick up things that are not specific to a term. You can use quotation marks to lock in that specific phrase, but you should really be using the "inferred annotation" filer to the term "cell cycle", e.g.:
http://amigo.geneontology.org/amigo/search/bioentity?q=*:*&fq=taxon_subset_closure_label:%22Schizosaccharomyces%20pombe%22&fq=regulates_closure_label:%22cell%20cycle%22&sfq=document_category:%22bioentity%22

**Comment by cmungall** [comment]
The concern is valid, and addressed here #158 

in particular @dosumis' comments: https://github.com/geneontology/amigo/issues/158#issuecomment-61954725
