### ISSUE TITLE
spurious free text annotation

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#388]
Probably related to
https://github.com/geneontology/amigo/issues/387

But check the top hits for "cell cycle"

![cell cycle](https://cloud.githubusercontent.com/assets/7359272/18626137/fe3b9d54-7e4a-11e6-968c-101fd104a68c.jpg)

**Comment by kltm** [comment]
This is the correct current functionality for the AmiGO free-text filter. See #387.

**Comment by cmungall** [comment]
ooh, this is terrible behavior. 

again to quote @dosumis in https://github.com/geneontology/amigo/issues/158#issuecomment-61954725 "But limiting functionality may do less harm than confusing users"

Agree completely. I was previously in favor of keeping the free text filter as a power user feature. But until we can improve it's functionality (both specificity and adding features like auto-recognizing ontology terms and converting to the correct search) it's better it goes away.
