### ISSUE TITLE
Graph views in AmiGO and QuickGO out of sync

### ISSUE THREAD

**Issue by tberardini** [geneontology/amigo#389]
@kltm requested that I open this issue after my email to him below.
"Thank you for pointing this out. This is (likely) a production issue.
Could you go ahead and open a ticket in the AmiGO tracker? I'll use that
as a jumping-off point to get production doing the right thing."

------------------
I edited the parentage of the term 'sorocarp development' probably about two weeks ago. I can see the new parentage using the inferred tree view in AmiGO and in the Ancestor Chart in QuickGo but the Graph View in AmiGO is sadly out of date.  How often is this updated and why is there a disconnect between the graph view and the inferred tree view?  This can be disconcerting.

http://amigo.geneontology.org/amigo/term/GO:0030587

http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0030587#term=ancchart

**Comment by kltm** [comment]
@tberardini I believe that this is due to a stale cache being used in production. Once the upstream image file is downloaded from QuickGO, AmiGO will continue to use that file as long as it is there. Periodically, the filesystem cache needs to be flushed.

@stuartmiyasato Do you have running something like 
```
gulp clean-filesystem
```
as part of the weekly rollout? I think something like that used to be in place, but might have fallen by the wayside with the rollout of the new system. Just moving all the files to /tmp or otherwise disposing of them would be fine as well.

**Comment by stuartmiyasato** [comment]
@kltm We are not running that command as I never saw that in the documentation (and after a quick search, still don't see that documented anywhere.).  Not sure what you mean by a weekly rollout?  AmiGO 2 is updated nightly, so when would be the best time to run this command?

**Comment by kltm** [comment]
@stuartmiyasato Ooo, nightly! I always forget how much quicker things are now.

The cleaning and maintenance are (incompletely) documented here:
 http://wiki.geneontology.org/index.php/AmiGO_2_Manual:_Installation_(2.4.x)#Afterwards
 http://wiki.geneontology.org/index.php/AmiGO_2_Manual:_Administration
to make up for the change away from the Makefile, which, IIRC, was integrated with the old rollout.

We actually had a thread about this on 9/10/2014 and 9/11/2014 with the title "Re: QuickGo Diagrams shown in AmiGO vs. same diagrams in QuickGO". I think it got lost in the interim.

**Comment by stuartmiyasato** [comment]
@kltm So just to be clear, should I be running "gulp clean-filesystem" immediately prior to "gulp cache"?  I need to modify our local loading scripts, so I want to make sure I'm doing the "right thing."  :)

**Comment by kltm** [comment]
Yes, that is correct. Current, that gulp command would run:
```
gulp.task('clean-filesystem', shell.task(_run_cmd_list(
    ['./scripts/blank-kvetch.pl',
     './scripts/clean-filesystem.pl -v -s',
     './scripts/clean-filesystem.pl -v -c',
     './scripts/clean-filesystem.pl -v -r']
)));
```
so actually not affecting the "gulp cache" command at all--they look like they are completely independent. However, I could see more cleaning functionality in the future, so it's probably good to keep them in that order.

**Comment by stuartmiyasato** [comment]
I have run the "gulp clean-filesystem" command and added it to our loading script.  @tberardini, does http://amigo.geneontology.org/amigo/term/GO:0030587 look better to you now?

**Comment by tberardini** [comment]
I'm going crazy.  I'm loading the same page multiple times and sometimes I see the old graph and sometimes I see the new graph.  Sometimes new, sometimes old.   GaaaaaahhHH!
<img width="1250" alt="screen shot 2016-09-19 at 4 45 04 pm" src="https://cloud.githubusercontent.com/assets/4998871/18652589/721cb19e-7e88-11e6-89ca-de1e15720218.png">
<img width="1270" alt="screen shot 2016-09-19 at 4 43 39 pm" src="https://cloud.githubusercontent.com/assets/4998871/18652588/721c5a6e-7e88-11e6-8d3e-fda21b76126b.png">

**Comment by kltm** [comment]
Huh. @stuartmiyasato, you updated both machines?
@tberardini, it's likely due to a stale cache somewhere along the way--the fact that the new images show up at all means that we're probably on the right path.

**Comment by tberardini** [comment]
Note that both pics are from (amigo2b) and the pic of the 'old' graph was taken AFTER the pic of the 'new' graph.

**Comment by kltm** [comment]
As represented above, the lower one is the new one and the upper one is the old one, correct?
Locally, I've purged my caches and get the same one as on the QuickGO site (delta the subsets), and as the lower one above.
Any remaining issues are likely around getting things purged in production and letting any other caches timeout out or get erased.

**Comment by stuartmiyasato** [comment]
Let me try restarting the web servers and see if that makes a difference.  If not, I suggest just waiting until tonight's refresh completes and seeing if that fixes the problem. Tonight's load has already begun -- it will probably be done around 10:00 pm local time.

Okay, web servers restarted, "gulp clean-filesystem" and "gulp cache" run.  How does it look now?

**Comment by tberardini** [comment]
Yes.  Lower = new, upper = old.

It still looks 'old' to me. Reloaded the page just now.

I will check again tomorrow.

**Comment by kltm** [comment]
Hm. @stuartmiyasato I wonder if they are not purging correctly on your system? That could be a bug, or a configuration mismatch.
My local working directory is /tmp. The files that need to be purged then are located in /tmp/cache/afs_qg_ont_files/ .

**Comment by stuartmiyasato** [comment]
@kltm What exactly gets deleted?  Everything underneath that directory?  It's possible that we're running into permissions issues.  The user we use to run all the gulp commands sometimes has issues with the cache directory which is owned by the web server user.  It may be that "gulp clean-filesystem" and "gulp cache" need to be run as the web server owner instead?  It's not clear to me what those commands do so I can't evaluate if something needs to be changed.

**Comment by kltm** [comment]
Yes, this is hard to debug.
For our purposes though, we want the removal of "???/cache/afs_qg_ont_files/*", where "???" is the path to your AmiGO working directory. How this is accomplished doesn't really matter (and may be hard to script with out gulp files due to permissions anyways).
As these are relatively disposable VMs, and I don't think that are links out, any CLI nuke of thos files should be fine.

**Comment by stuartmiyasato** [comment]
@kltm Okay, yeah, I have manually cleared that directory before and had issues due to ownership.  I may need some time to think this through.  I'll do this manually for right now and see if it makes a difference.  Automating it may be fun...

**Comment by kltm** [comment]
Yes, recursive deletes are always "fun".
amigo2a seems to have the correct version now. I think this is the right track.

**Comment by stuartmiyasato** [comment]
How long do files stay in the cache?  Some files date back to August.  Is this expected?

**Comment by stuartmiyasato** [comment]
If I clear the cache directory manually, I am having trouble regenerating the cache files.  I'll look into this further tomorrow.  In the meantime, I have restored the old (probably out of date) cache files.

**Comment by stuartmiyasato** [comment]
@tberardini I'm getting the "new" graphs from both servers now.  How is it looking to you?

**Comment by tberardini** [comment]
It is looking beautiful!!  Updated, new, not stale.  Go ahead and close this ticket if you think all that needs doing is done. 

Thanks very much, Seth and Stuart.

**Comment by kltm** [comment]
Thank you @stuartmiyasato !

**Comment by kltm** [comment]
@stuartmiyasato For https://github.com/geneontology/amigo/issues/389#issuecomment-248374727 ,
AmiGO itself does not age out the caches. Instead it was made dumb enough that it could be hot removed from the filesystem, leaving it to the site to decide the best policy.

Along those lines, if you're interested, I have a find command lying around here somewhere that does a scan for files over a certain age and feeds them to rm. You probably have something similar.

**Comment by stuartmiyasato** [comment]
@kltm Ah, got it.  So given that I don't have a good feel for how often cached files change, what do you recommend for an expiration time?

**Comment by kltm** [comment]
Well, we'll either need to match our own schedule, or quickgo's. My druthers would be to have the scan and purge happen when the new indexes go out, as part of the loading pipeline.
So daily then? As we probably get spidered, the delete will probably add a few minutes, but shouldn't be too bad.
