### ISSUE TITLE
Add link to amigo publication pages from NCBI using LinkOut

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#392]
We can click on the PMID of any annotation in amigo to see a summary of annotations from that publication, e.g.

http://amigo.geneontology.org/amigo/reference/PMID:9769173

This has links to https://www.ncbi.nlm.nih.gov/pubmed/9769173

On the NCBI page, there are LinkOut links to MGI, but not to amigo. We'd like to add these.

For more info:
https://www.ncbi.nlm.nih.gov/projects/linkout/

cc @thomaspd

**Comment by cmungall** [comment]
Current status:

We have done this as a one-off export for NCBI. If everything checks out, we will 

 - [ ] write a script that pulls all referenced PMIDs from the database
 - [ ] create a jenkins job that executes this as part of release and deposits it where NCI can slurp it

**Comment by thomaspd** [comment]
Correction: we will upload the file to NCBI by FTP (it will be a push from us, not a pull from them).

**Comment by kltm** [comment]
As well, @cmungall and myself have discussed a little about the best way to support external parties being able to hotlink to our official logo.

**Comment by kltm** [comment]
Awesome, thanks @thomaspd !
