### ISSUE TITLE
Number of human protein-coding genes still too high

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#393]
![screen shot 2016-10-10 at 5 33 13 pm](https://cloud.githubusercontent.com/assets/50745/19255144/a4e9bc88-8f0f-11e6-9c83-5d7c4b939989.png)

Should be 19158

(number of distinct entities in goa_human and goa_human_isoform)

**Comment by cmungall** [comment]
This seems fine:

https://github.com/geneontology/amigo/blob/master/conf/examples/amigo.yaml.production#L137-L139


is this definitely what is used on production?

**Comment by cmungall** [comment]
This also looks fine http://amigo.geneontology.org/amigo/load_details

mysterious...

**Comment by cmungall** [comment]
@kltm found it

coming from

	gene_association.goa_uniprot_noiea.gz

in theory this should have homo sapiens removed...

**Comment by kltm** [comment]
Current count is 19624, so apparently fixed along the way somewhere...
