### ISSUE TITLE
In some cases, there appears to be an issue with the topology or transitivity graph payloads in GOlr

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#394]
This issue was generated from http://jira.geneontology.org/browse/GO-1366

It appears that in some cases in the graph, the number of children generated exceeds the number that would be expected. Using GO:0006915 "apoptotic process" as an example.

Note the number of children in the "Inferred Tree View":
http://amigo.geneontology.org/amigo/term/GO:0006915#display-lineage-tab

Now note the number of children in the "Neighborhood":
http://amigo.geneontology.org/amigo/term/GO:0006915#display-sentences-tab
(And, for that matter, the rather exotic parents in the same tab.)

I would suspect that if there is an issue here, that is is coming from the OWLTools loader mishandling relationship types during graph generation.

Before digging in more, hoping to get some comments from @cmungall .

**Comment by cmungall** [comment]
Dupe of #366?

**Comment by kltm** [comment]
Uhhh...I'm not sure I'd want to call that, but if you think that's the correct determination, I'd be happy to close.
Looking at the two, in this case, it seems like the issue is that there are waaay more children in the inferred tree view than one might expect when compared to the neighborhood view; it seems that the formulation of #366 is the opposite.

**Comment by kltm** [comment]
Given where we're going with #366 , let's call this a dupe.
