### ISSUE TITLE
In some cases, "Thing" appears in facet filters for GO class

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#395]
4th option down?

![thing](https://cloud.githubusercontent.com/assets/7359272/19457815/0aaf6396-94c0-11e6-8a21-d9950e5bcaf1.jpg)

**Comment by kltm** [comment]
@ValWood Could you supply a URL?

**Comment by kltm** [comment]
Currently, at
http://amigo.geneontology.org/amigo/search/annotation
"Thing" appears as the first item in the "GO class" filter.
@cmungall has something changed in the ontology recently?

**Comment by cmungall** [comment]
by definition this can't be a change in the ontology, as owl:Thing is always there.

we *should* be excluding these:

https://github.com/owlcollab/owltools/blob/c12827b29141ba109a7df0d7eadc2e16f2437581/OWLTools-Core/src/main/java/owltools/graph/OWLGraphWrapperEdges.java#L501-L503

**Comment by cmungall** [comment]
what is especially weird is that if Thing (i.e the universal set) is escaping through, it should have equal to or more than the maximum number of genes in it, shouldn't be 4th one down! Investigating...

**Comment by kltm** [comment]
Yes, that's why I was guessing ontology change and not a new "all"...

**Comment by cmungall** [comment]
I can't replicate Val's example, Thing is always top for me, which is consistent with this being a filtering error, e.g. http://amigo.geneontology.org/amigo/term/GO:0005575

**Comment by kltm** [comment]
http://amigo.geneontology.org/amigo/search/annotation?q=*:*&fq=-regulates_closure_label:%22biological_process%22&sfq=document_category:%22annotation%22

**Comment by ValWood** [comment]
I can't remember how I got this, I took a screenshot when I saw it but it was on Sunday I think...even the list isn't reminding me what I was doing....

**Comment by kltm** [comment]
@ValWood I got an example of it at https://github.com/geneontology/amigo/issues/395#issuecomment-254360243 .

**Comment by cmungall** [comment]
so definitely a problem with population of the closures, and seems to permeate document types, even if not exposed:

 * [ontology download](http://golr.geneontology.org/select?defType=edismax&qt=standard&indent=on&wt=csv&rows=100000&start=0&fl=annotation_class,annotation_class_label,isa_partof_closure&facet=true&facet.mincount=1&facet.sort=count&json.nl=arrarr&facet.limit=25&hl=true&hl.simple.pre=%3Cem%20class=%22hilite%22%3E&csv.encapsulator=&csv.separator=%09&csv.header=false&csv.mv.separator=%7C&fq=document_category:%22ontology_class%22&fq=idspace:%22GO%22&fq=is_obsolete:%22false%22&facet.field=source&facet.field=idspace&facet.field=subset&facet.field=is_obsolete&q=neuron*&qf=annotation_class%5E3&qf=annotation_class_label_searchable%5E5.5&qf=description_searchable%5E1&qf=synonym_searchable%5E1&qf=alternate_id%5E1)
 * [entity download](http://golr.geneontology.org/select?defType=edismax&qt=standard&indent=on&wt=csv&rows=100000&start=0&fl=bioentity,bioentity_label,isa_partof_closure&facet=true&facet.mincount=1&facet.sort=count&json.nl=arrarr&facet.limit=25&hl=true&hl.simple.pre=%3Cem%20class=%22hilite%22%3E&csv.encapsulator=&csv.separator=%09&csv.header=false&csv.mv.separator=%7C&fq=document_category:%22bioentity%22&facet.field=source&facet.field=taxon_subset_closure_label&facet.field=type&facet.field=panther_family_label&facet.field=annotation_class_list_label&facet.field=regulates_closure_label&q=Shh1*&qf=bioentity%5E2&qf=bioentity_label_searchable%5E2&qf=bioentity_name_searchable%5E1&qf=bioentity_internal_id%5E1&qf=synonym%5E1&qf=isa_partof_closure_label_searchable%5E1&qf=regulates_closure%5E1&qf=regulates_closure_label_searchable%5E1&qf=panther_family_searchable%5E1&qf=panther_family_label_searchable%5E1&qf=taxon_label_searchable%5E1)

**Comment by cmungall** [comment]
code here: https://github.com/owlcollab/owltools/blob/41e1f585d7a8135081c3f2e56c4aa6590901227b/OWLTools-Core/src/main/java/owltools/graph/OWLGraphWrapperEdgesAdvanced.java#L682-L714

Just need to add a filter for owl:Thing here

Note we recently switched from graph walking to the proper inference method here, but the ad-hoc filter was not moved across

**Comment by kltm** [comment]
Action now on this end to recompile and pull in new owltools jar.
Probably want to get this on current production as well...

**Comment by ValWood** [comment]
did this get fixed? I didn't notice it recently.

**Comment by kltm** [comment]
Hm...
Apparently?
