### ISSUE TITLE
searching in AmiGO

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#396]
I wonder if gene names, or exact mathces to gene names could be given higher priority when searching if they match the gene names field. I noticed this issue with Noctua too.

For example searching for Skp1 I see
![searching exact match](https://cloud.githubusercontent.com/assets/7359272/19457920/c096b678-94c0-11e6-9b0a-a5822c127647.jpg)

which makes me think that pombe skp1 is missing, or why wouldn't it be higher.

Then if I hit the space (which i often forget, so I don't know if all users would know this), I do see
skp1:

![untitled 2](https://cloud.githubusercontent.com/assets/7359272/19457945/e4e0c6b8-94c0-11e6-9409-9dfd29176070.jpg)

maybe its not possible to weight differently....

**Comment by ValWood** [comment]
So, things which mention skp1 in the description (i.e because they are in the same complex or whatever) get ranked higher.  Perhaps a higher score for exactly matching the entire string?

**Comment by kltm** [comment]
This is currently addressed in a large number of other issues and will be fixed in the next release.

**Comment by ValWood** [comment]
Ooh fab !

**Comment by kltm** [comment]
(We're stoked--we've not had a lot of time to tackle it on the GO side, but because we've managed to share this stack with other projects and they've been able to pick up the slack and have made some great improvements there (thanks @jnguyenx !).)
