### ISSUE TITLE
Human annotations have disappeared from AmiGO annotations

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#400]
The current contents of goa_human.gaf.gz in SVN contains no data, only a header. Unfortunately, AmiGO has automatically loaded this, so there are currently no human annotations in in the production AmiGO.

@cmungall suggests bringing AmiGO down in the interim.

@stuartmiyasato I would suggest using an "error" type system message (e.g. http://wiki.geneontology.org/index.php/AmiGO_2_Manual:_Administration#System_messages_and_global-message.pl ) until the new data is loaded.

```
AmiGO is undergoing an unexpected and necessary data reload.
Our apologies for the inconvenience. During this process, please feel free to use the <a href="http://amigo2.berkeleybop.org"><backup site/a>.
```

**Comment by kltm** [comment]
@cmungall will let us know when upstream has a fix.

**Comment by kltm** [comment]
See:
https://github.com/geneontology/go-site/issues/248
http://jira.geneontology.org/browse/GO-1388
http://jira.geneontology.org/browse/GO-1393

**Comment by kltm** [comment]
As well, we could take a CNAME redirect temporarily instead.

**Comment by kltm** [comment]
Although a root redirect would be fine too.

**Comment by stuartmiyasato** [comment]
I'll try the root direct method.  I'll probably take the easy way out and redirect /* to http://amigo2.berkeleybop.org and not try to be smart about the path.

**Comment by kltm** [comment]
Anything is good. Since we have no sessions, and the same layout, you should be able to pass the whole thing as-is without problem...?

**Comment by cmungall** [comment]
We need to also revert in svn, may people download directly

**Comment by stuartmiyasato** [comment]
That's going to require more testing than I really have time for at the moment.  I'm just redirecting any path back to the home page at http://amigo2.berkeleybop.org/ right now.  But that functionality is now in place.  (I'm still dealing with Dirty COW on other servers so I don't want to spend much time on this.)

**Comment by kltm** [comment]
Cheers! Redirect works as intended.

**Comment by kltm** [comment]
Mike (no github id?) has put in a fix for the filtering script, so the data should be good again. Then plan is then, after a reload and check, revert the redirect.

**Comment by stuartmiyasato** [comment]
I'm manually starting a load now to save about 7 hours of waiting time.  Will let you know when it's ready for testing.  (I'm not sure that we can test without removing the redirect, so we'll probably just have to do a check on the live site.)

**Comment by kltm** [comment]
Sorry about your Saturday :(
With the redirect to dev, we're safe as far as data goes (I turned off the reload a couple of days ago), so don't stress if you end up doing other things.
As long as there is no redirect on your golr, I can check the data from my laptop by just aiming at your addressable backend.
As well, can't we hit amigo2a, etc., directly?

**Comment by stuartmiyasato** [comment]
I'm working today regardless to deal with remaining Dirty COW patches, so it's no big deal.  :)  Been patching for the past four hours already...

The redirect for AmiGO is being done at the Apache level on individual servers, so hitting amigo2a directly will still give you the redirect.  But GOlr is running off nginx,so you can still hit that directly at golr.geneontology.org.

**Comment by kltm** [comment]
Okay, great. When you're ready, we can go that way--I've already got my localhost aimed at the production golr backend.

**Comment by kltm** [comment]
@stuartmiyasato I now have humans again locally!

**Comment by stuartmiyasato** [comment]
@kltm Great!  amigo2b is being refreshed at the moment.  I'll remove the redirects when it's finished.

**Comment by stuartmiyasato** [comment]
Sorry, been dealing with some rather major disk corruption issues on some other servers tonight.  amigo2a and amigo2b are back up and running, and I've removed the redirects.  Please feel free to check production and make sure the data looks okay.  Thanks.

**Comment by kltm** [comment]
It looks great to me--thank you!
