### ISSUE TITLE
Have help linkouts in pages contain relevant contextual information

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#401]
http://jira.geneontology.org/browse/GO-1396?jql=project%20%3D%20%22GO%22

**Comment by kltm** [comment]
From @ValWood 's initial issue: "Make helpdesck tickets sent from PMID include the PMID".

**Comment by kltm** [comment]
Related to general backend decided for geneontology/go-site#250.

**Comment by kltm** [comment]
Well, there doesn't seem to be a way of doing pre-population with GitHub right now, so I'm going to close for now due to impossibility. It may be revisited if geneontology/go-site#250 moves forward.
