### ISSUE TITLE
Dictyostelium discoideum missing from Organism facet, apparently no dicty annotations

### ISSUE THREAD

**Issue by pfey03** [geneontology/amigo#402]
Hi Seth,
I'm always annoyed that all kind of fungus and stuff is in the list right away, but always had to search for Dicty. Now even that search returns nothing. what happened?

Thanks,
Petra

**Comment by kltm** [comment]
Is this still happening? Does the following link work for you?
http://amigo.geneontology.org/amigo/search/annotation?q=dicty*&fq=taxon_subset_closure_label:%22Dictyostelium%20discoideum%22&sfq=document_category:%22annotation%22

**Comment by kltm** [comment]
I would swear that I was able to duplicate this about twenty minutes ago, then, when checking again to write the ticket (and possibly connect it to #400 ), I things worked cirrectly and I could find the annotations.

My guesses at this point are along the lines that somehow a page got cached from during a load when dicty was not yet in the index, and we managed to get it; the page/cache is not refreshed.

**Comment by pfey03** [comment]
Ah, sorry, yes, the link works. After some trying, I noticed that I used a child term of the term Dicty has annotations to. Only, if there are no annotations to the term, a message to that affect could help? I was first convinced we must have annotations and saw blank screen, no message in the pop up where you start typing your organism name. 

Also, is the ready list when you open the Organism tab by usage? Now Dicty is in the list right away and wondered why I always need to search. Maybe don't do it often enough

**Comment by kltm** [comment]
Dicty, at this point, is cut off as the list is ordered by number of annotations. You can bookmark various searches to start with, so you can jump right to the relevant data for your organism. For example:

annotations: http://amigo.geneontology.org/amigo/search/annotation?q=*:*&fq=taxon_subset_closure_label:%22Dictyostelium%20discoideum%22&sfq=document_category:%22annotation%22

gps: http://amigo.geneontology.org/amigo/search/bioentity?q=*:*&fq=taxon_subset_closure_label:%22Dictyostelium%20discoideum%22&sfq=document_category:%22bioentity%22

I do, however, think something was going wrong there temporarily at production--I would swear that I found no dicty annotations for a short period.
