### ISSUE TITLE
Index PTN IDs

### ISSUE THREAD

**Issue by pgaudet** [geneontology/amigo#403]
Hello, 

It would be very useful if PTN IDs were searchable in AmiGO. 

:) 

Thanks, Pascale

**Comment by kltm** [comment]
I'm fold this as an addition to #79.

**Comment by selewis** [comment]
They should already be searchable. I'll retest this today to see. You
should be able to type just about anything into the gene search box.

**Comment by cmungall** [comment]
This would be great, but would presumably be of limited use without 
including a way to hop from the PTN to the extant child nodes (and 
possibly up to ancestors, but I think we can do a good job without 
implementing a full blown tree view)

Shall we sketch out some requirements here and then prioritize?

**Comment by selewis** [comment]
Yes let's do that Chris
