### ISSUE TITLE
Update AmiGO when new db-xrefs.yaml data is available

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#404]
This isn't an AmiGO issue, but it causes one so for now I am putting it here.
Whilst I was accessing some annotation intersections at the GO meeting, I noticed that some of the with field dbxrefs give an error (they will not match an entry in the GO-dbxrefs file, or its replacement)

See
![swiss-prot link](https://cloud.githubusercontent.com/assets/7359272/20233878/6b6bcbf6-a86c-11e6-8ede-87f149e3d1f7.jpg)

and

![matrix](https://cloud.githubusercontent.com/assets/7359272/20233900/9ebc0c78-a86c-11e6-81c5-f3e96b517d26.jpg)

**Comment by ValWood** [comment]
So, Swiss-Prot should not be allowed in the "with" field. These should all be  changed to UniProtKB? Then these links will work.

Second,  The Pfam links still go to https://pfam.sanger.ac.uk/family
These should now go to http://xfam.org/

**Comment by kltm** [comment]
It sounds like this is a request for 1) an upstream filter or data change for whoever is supplying the Swiss-Prot data and 2) an update for the db-xrefs.yaml for Pfam?

**Comment by kltm** [comment]
@ValWood would you agree with the statement https://github.com/geneontology/amigo/issues/404#issuecomment-260085556 ?

**Comment by ValWood** [comment]
Yes,  that is correct, but I don't know where to report it. It shouldn't be here should it?

**Comment by kltm** [comment]
I'll put them over on go-site. The rule is generally that an issue belongs in the repository when the fix will take place. The only fix that is available here is to update the production AmiGO instances once the data is updated. 

This issue is now waiting on geneontology/go-site#262 and geneontology/go-site#263.

**Comment by ValWood** [comment]
might be done?

**Comment by kltm** [comment]
If you say so. No harm in closing as swissprot no longer seems to be there and we are now updating monthly at least anyways.
