### ISSUE TITLE
Download count unnecessary text on gene product download pages

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#405]
One the gene specific page the link says

to all direct and indirect annotations download (limited to first 10,000) for cdc24.

do we really need to say (limited to first 10,000) here?
as an individual gene product will never have 10,000 annotations (we hope)

Maybe
view  annotations to cdc24
download annotations to cdc24

is sufficient 

(although the first link is also confusing from this page, because this list is already shown by default, so I'm not sure why this link is here?)

**Comment by kltm** [comment]
As there is a limit and there is no probing of the store to check what the number would be without a limit, it seems better to announce the limit upfront rather than have the users try it and not get all of their annotations.

**Comment by ValWood** [comment]
but an individual gene product will never have 10,000 annotations so it seems odd to announce something that will never occurr?

**Comment by kltm** [comment]
Example: http://amigo.geneontology.org/amigo/gene_product/UniProtKB:H2Q415
