### ISSUE TITLE
Some information missing on some PubMed/reference pages

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#409]
In some cases, due to the messiness of the data coming back across from the pubmed webservice, some information is missing from some pages. 

Looking into this more, the only consistent example that I can find seems to be date:

https://www.ncbi.nlm.nih.gov/pubmed/2682257

Missing date:

http://amigo.geneontology.org/amigo/reference/PMID:2682257

But this one has abstract and date:

http://localhost:9999/amigo/reference/PMID:21098516

OTOH, it is there a lot too. While irritating, I don't particularly want to write a scrubber right now. Unless there is more complaint, I'll close with "wontfix", with a reopen on complaint.

**Comment by ValWood** [comment]
Most I have looked at are missing date and abstract.....

**Comment by kltm** [comment]
The production code is behind the development code, where that is mostly fixed.
