### ISSUE TITLE
 search behaviour

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#410]
Currently when you search on  "protein kinase" in Amigo

GO:0004672 Name	protein kinase activity

is not one of the term suggestions

is the best way to improve this to add "protein kinase"  as an exact synonym, or is these a  better way?

**Comment by ValWood** [comment]
Furthermore, it isn't even the top hit if I type the whole term  name (protein kinase activity), which is a tad bizarre???

**Comment by kltm** [comment]
The is already captured in a lot of other tickets, including #102.
