### ISSUE TITLE
extension filter

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#412]
I was trying to  contruct a query to answer a PomBase user question.
Retrieve all kinases (or phosphatases)  with  known target/substrate annotations

I don't understand the extension filter:

![extension filter](https://cloud.githubusercontent.com/assets/7359272/20959488/2922b66a-bc53-11e6-9a20-353d22ef1557.jpg)

It presents lots of GO term filter options, but:
 
i) GO terms are not the only thing in extensions (the  majority or our extensions are probably gene products)
ii) extensions are only meaningful when they  include the context provided by the relation. Without this information it isn't meaningful to provide a filter on anything else.... For example even 'process" can be part of, happens during.
iii) because of the way the filters are presented (by > annotation) the terms which are presented aren't particularly useful (even if you knew how to use them)

For example, I could not figure out why we had 	so many extensions 
"regulation of nitrogen compound metabolic process"

It turns out they are from  substrate/part_of process connections to transcription
has_direct_input PomBase:SPBC19F8.07
part of regulation of transcription from RNA polymerase II promoter

Maybe there is a better way to present this filter to be useful to the general biological user?

**Comment by kltm** [comment]
I think this is probably best added onto #200 or #201.

**Comment by cmungall** [comment]
201 is a non-trivial ticket.

We can consider some stopgaps. For example, using a slim for the extension filter (as we do for taxon). @kltm if you think this is a good idea make a new ticket.
