### ISSUE TITLE
Downloading annotation extensions should use the standard syntax

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#413]
Is the output meant to look like this?

PomBase:SPBC216.07c	serine/threonine protein kinase Tor2		GO:0004672	"{""relationship"": {""relation"": [{""id"": ""GOREL:0000752"", ""label"": ""has_direct_input""}], ""id"": ""PomBase:SPAC1B9.02c"", ""label"": ""PomBase:SPAC1B9.02c""}}"	PomBase	NCBITaxon:4896	IDA				PMID:22976295	20151027
PomBase:SPBC216.07c	serine/threonine protein kinase Tor2		GO:0004672	"{""relationship"": {""relation"": [{""id"": ""GOREL:0000752"", ""label"": ""has_direct_input""}], ""id"": ""PomBase:SPAC22E12.14c"", ""label"": ""PomBase:SPAC22E12.14c""}}"	PomBase	NCBITaxon:4896	IDA				PMID:22976295	20151027

**Comment by ValWood** [comment]
1. column headers would be helpful 
2. I'd rather see extensions formatted in the same way that we construct them...there is a lot of duplication in theis output. And too many """"":[{]

**Comment by ValWood** [comment]
I now see this is jsn format? would people ewant this in a standard tab delimited file.

I tried a different option (annotation extesnion class labal)

This gives me:

PomBase:SPBC14F5.08	mediator complex subunit Med7		GO:0030295	PomBase	NCBITaxon:4896	IDA				PMID:10625684	20160908	regulation of transcription from RNA polymerase II promoter
PomBase:SPAC2F3.15	P-TEFb-associated cyclin-dependent protein kinase Lsk1		GO:0004693	PomBase	NCBITaxon:4896	IMP				PMID:17502918	20151109	

1. No extension if the extension is a gene product
2. No extension relation

**Comment by ValWood** [comment]
next option gives me some craziness:

PomBase:SPBC14F5.08	mediator complex subunit Med7		GO:0030295	PomBase	NCBITaxon:4896	IDA				biological regulation|biological_process|regulation of RNA biosynthetic process|regulation of nucleobase-containing compound metabolic process|regulation of macromolecule metabolic process|regulation of transcription, DNA-templated|regulation of nitrogen compound metabolic process|regulation of nucleic acid-templated transcription|regulation of biosynthetic process|regulation of transcription from RNA polymerase II promoter|regulation of cellular process|regulation of RNA metabolic process|regulation of gene expression|regulation of macromolecule biosynthetic process|regulation of metabolic process|regulation of cellular macromolecule biosynthetic process|regulation of biological process|regulation of cellular biosynthetic process|regulation of primary metabolic process|regulation of cellular metabolic process	PMID:10625684	20160908

Is there an option which gives me the annotated extension?
i.e.
has_direct_input PomBase:SPBC19F8.07,part of regulation of transcription from RNA polymerase II promoter

**Comment by kltm** [comment]
I'm afraid this is also an extension of the issues around #201 .

**Comment by cmungall** [comment]
201 is about how to better query using information in the extension.

I think @ValWood just wants an extension column that is identical to the source GAF. This should be straightforward but plumbing at a few different places:

 - [ ] Extend association schema to include a field `annotation extension (source)`
 - [ ] Extend owltools-solr to populate this with the exact string, prior to parsing
 - [ ] Remove json from list of defaults

Some additional side-issues

 - [ ] Show column headers
 - [ ] Remove unused fields (e.g. geo)
 - [ ] General user-friendliness stuff

**Comment by ValWood** [comment]
Spot on!  Thanks.

**Comment by kltm** [comment]
Dupe #94 then.
For the additional issues, one of the reason that we agreed to the "pseudo-gaf" is so we do not have to pipe the solr output through a proxy to add decorations.
