### ISSUE TITLE
PMID  search and NCBi linking

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#415]
I search on a PubMED ID and can get to annotations now, which is great!

The landing page is this one. DO you plan to add a document type for  publication here to get straight to the annotations from a specific publication?
http://amigo.geneontology.org/amigo/medial_search?q=PMID%3A12477395

**Comment by ValWood** [comment]
This would be useful, because most have the results have nothing to do with the PMID
(although I can locate the publication page from the annotation top hits)

**Comment by ValWood** [comment]
Also, there are 2 prominent links  which I initially followed to get to the NCBI.

Do these even need to be on this page?  SGD includes  reciprocal links  and do not seem to include this.
If it is necessary, can it be tiny boiler plate at the bottom of the page (nobody needs to see this on a regular basis)

**Comment by cmungall** [comment]
The publication pages look like this:

http://amigo.geneontology.org/amigo/reference/PMID:9769173

To get to these from within AmiGO, you have to click on a PMID on an annotation row (or a term definition xref too). You can also endup here from NCBI linkout.

It's quite hard for a user to end up on this page if their start query is a PMID, as you point out.

Ideally pubs would be a bona fide doc type. For now we don't index the publications, we populate this dynamically, so you can't query on pubs directly, just annotations/terms by pubs. I think ultimately we will want to index the full pub but it's not top of our priorities.

In the interim, perhaps we could do two things:

 - autocomplete recognizes a PMID and takes you straight to the page
 - medial search recognizes it's a PMID and provides a direct link

A bit hacky. Maybe we just need to bite the bullet and have PMIDs as full documents

**Comment by ValWood** [comment]
Yeah it's not critical.

The only reason I was trying to find out how to get there  was because I was trying figure how to point our users to the publication view  as an additional  "community curation participation" carrot. Not that we need one right now....they are curating more than we are....

**Comment by kltm** [comment]
Dupe #397 .

**Comment by ValWood** [comment]
Those links though, can you move them? they are really annoying.

![necessary](https://cloud.githubusercontent.com/assets/7359272/21066705/e9a38344-be5e-11e6-89de-b3d226bb1c51.jpg)

**Comment by ValWood** [comment]
Am I annoying ?
