### ISSUE TITLE
synonym collapsing not consistent

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#418]
1. 
Some  gene products with long lists of synonyms don't have them collapsed...
![synonyms](https://cloud.githubusercontent.com/assets/7359272/21811104/4756bbbe-d746-11e6-9533-0dfba8b45a6f.jpg)

2. Would a simple hyperlink "more.." be a bit more pleasing than a big button?

**Comment by ValWood** [comment]
And the MGI annotations appear as a long comma separated list (might be a GAF issue?) @ukemi ?

**Comment by ukemi** [comment]
@hdrabkin can you look into this please?

**Comment by hdrabkin** [comment]
Nothing has changed as far as I know. Synonyms are suppose to be pipe separated according to GAF2; I see in the GAF however, that they are comma separated. I will put in a work order for Lori to fix. It may take a while.

**Comment by kltm** [comment]
@ValWood As commented by @ukemi and @hdrabkin , the comma/list thing is almost certainly a data issue, which we can push to the appropriate place when we (they) figure out the source.

For the button, besides an aesthetics argument (I think it's fine anyways), it is: 1) meant to be eye-catching and 2) part of the standard uniform UI that we're trying for with the Bootstrap framework. A hyperlink would imply opening up a new page and/or navigating away, where what we want to indicate is an in-page function.

**Comment by cmungall** [comment]
what page is this?

**Comment by kltm** [comment]
Paging through, or expanding returned results, is enought to get something similar:
http://amigo.geneontology.org/amigo/search/bioentity?q=clasp*&sfq=document_category:%22bioentity%22

**Comment by kltm** [comment]
@hdrabkin Thank you for the update!
