### ISSUE TITLE
search weights PATO terms higher than GO terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#420]
I'm not sure why when I search amigo I am seeing PATO terms, this might be confusing for users ...there a quite a lot of PATO terms, which are not going to give any results.

The top hit for "phosphorylation" in AmiGO is PATO PATO:0002262

**Comment by kltm** [comment]
This will fall under the general search overhaul we need to do, such as https://github.com/geneontology/amigo/issues/102 and company.
