### ISSUE TITLE
Add "regulates" toggle to term matrix

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#423]
In historical versions of term matrix  anntotations by regultes.
Now they are not, which is fine for first pass.

However, I sometime use term matrix in other ways (and there are potential misannotations  moved down at the "regulates" level which should also be assessed.

Could you add a toggle so that "regulates" can be included or excluded?

Thanks

val

**Comment by kltm** [comment]
@ValWood 
I've put something together, but a little hacky (although you may not notice at your end).
I can't get this into production right away, but it's already available on the dev site:

http://tomodachi.berkeleybop.org/matrix

Let me know if that works for you.

**Comment by ValWood** [comment]
Yep, just tested, this is great, thanks...
