### ISSUE TITLE
Uniprot derived FB annotation not getting into AmiGO?

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#424]
I noticed this is in QuickGO, but not in AmiGO.
Is that a known issue (its one I queried,  so hopefully it will disappear but might be a general issue)?

![missing](https://cloud.githubusercontent.com/assets/7359272/23757649/556bfcd4-04df-11e7-8ff3-da0cf01d6048.jpg)

@cmungall 
@hattrill

**Comment by hattrill** [comment]
There's still an open dispute that's not been resolved by SwissProt. We've removed our offending annotation and the one we had imported from UniProt from our db a couple of releases back. I assume that the absence in AmiGO is that we hold the trump set when it comes to D.mel.

**Comment by kltm** [comment]
@hattrill we do indeed only have the fb gaf for 7227.
