### ISSUE TITLE
Base statistics currently does not report full numbers for some species

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#425]
Reported by Mike.

Production AmiGO is currently reporting incorrect numbers for some species in the statistics section: http://amigo.geneontology.org/amigo/base_statistics#experimental-annotations-by-species

![newplot 5](https://cloud.githubusercontent.com/assets/2687900/23885846/657662c0-0833-11e7-9e9d-423bdf87f1ae.png)

Compare to the same release of AmiGO in dev:

![newplot 4](https://cloud.githubusercontent.com/assets/2687900/23885852/746d98b6-0833-11e7-82be-bedd0389761b.png)

A cursory inspection seems to indicate that the data is otherwise the same.

I suspect that the cache was built while the GOlr was either rebuilding, fluttering, or pointed at the wrong load balancer terminal machine (or some combination). @stuartmiyasato Would it be possible to rerun the cache command on the production machines?

**Comment by stuartmiyasato** [comment]
@kltm I'm not sure what the source of "dev" is above (your servers?), but I can't get the production graphs to match yours which tells me the issue is somehow with our data load.  (I haven't seen any load error reports though...)  The "gulp cache" command is run as the last step with each load, and I just ran it by hand on each production AmiGO server but there's been no change to the graph.  Also for comparison, amigo2-test.stanford.edu has a similar looking graph to production and that load was from last November.

Not sure what you want to do about this...  Of course, my question is going to be how long until production AmiGO moves to Berkeley? (Or AWS or whatever non-Stanford site?)  :)

**Comment by kltm** [comment]
The "dev" one is indeed the production branch run over here.
As an experiment, I just ran `gulp cache` script over here against the production server with:
```
node ./scripts/amigo-create-base-stats-cache.js --server http://golr.geneontology.org/
```
and it generates the good image (when I had nothing before, as I generally don't load annotation locally).
The script should create a file "amigo/perl/bin/amigo-base-statistics-cache.json"; could you check that it is being created and updated properly on the clients? I could imagine a scenario where a user with a different permission created them as a one off and now the automated script is having trouble.

As far as the switch to Berkeley goes, I am the time limiting step, and I don't have as much time as I'd hoped for. These days, I've mostly been sinking my time into helping figure out the new pipeline.

**Comment by ValWood** [comment]
duplicate of
https://github.com/geneontology/go-site/issues/293

which reports a series of other  (possibly related) issues and was closed as a dupe of 
https://github.com/geneontology/amigo/issues/364

v

(maybe should check  when this issue is closed that all in 293 are fixed)

**Comment by kltm** [comment]
Ugh, sorry--I missed the functional issue you had in with the visual issues (which I tried to part out into geneontology/go-site#364 ). I'm having trouble imagining the issue, but I'm now thinking that there was once a bad load and now that data is frozen in production (user perms on the file?).

**Comment by kltm** [comment]
From @ValWood other ticket (from embarrassingly long ago):

 - [ ]  first graph EXP by species has no cerevisiae?
- [ ]  Annotations by aspect/species by evidence is missing cerevisiae
- [ ] I think the numbers in EXP annotations by publication are incorrect. For pombe  you have 21,000 but we have curated <3000 publications, the number for SGD (91,000) exceeds the number of GO annotations. Flybase has 2 entries (FlyBase/FLYBASE)

The last one may be something different, but the first two are likely related to this issue.

**Comment by kltm** [comment]
Ugh, okay. I've caught up on all these threads again: this issue is a dupe of #364 , which never got closed out. While I like the pictures here, there is more context over there.
