### ISSUE TITLE
Ontology seems to contain problematic terms: Nothing (owl:Nothing)

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#428]
Looking at the children of

 http://amigo.geneontology.org/amigo/term/GO:0004340#display-lineage-tab

One of the children is: `Nothing (owl:Nothing)`. I'm going to assume that "Nothing is a glucokinase activity" is not a correct statement. This is very likely an ontology issoe and not an AmiGO issue.

Initially caught by @ukemi
Looking for intial feedback from @cmungall

**Comment by cmungall** [comment]
It is a correct statement (the empty set, or ⟂ in OWL, is the subset of all sets).

However, it's obviously not *useful* in the context of AmiGO. We filter owl:Thing, but not Nothing.

**Comment by kltm** [comment]
Well, relieved that it's the empty set and not Fantastica's "The Nothing".
On the AmiGO side of things, we do not have a resolvable amigo.geneontology.org/amigo/term/owl:Nothing , but it's not useful to worry about that too much.
Also, why just there, as opposed to all leaves? Just a local hiccup?

**Comment by cmungall** [comment]
Companion to #395

**Comment by cmungall** [comment]
I think it is on all leaves (not immediately obvious in the tree view as there is no visual indication for leaf node AFAICT)

**Comment by kltm** [comment]
Yep, right you are: http://amigo.geneontology.org/amigo/term/GO:0033133#display-lineage-tab

**Comment by kltm** [comment]
Okay, this is more insidious than we first thought, and it has gotten into production (hello, @stuartmiyasato).

Essentially, in some cases, as owl:Nothing is a subclass of everything, there can be some exceptionally large graphs for it. This isn't a problem a lot of the time, but if a user stumbles onto a case where (for example) `topology_graph_json` is returned from a search that matches `owl:Nothing` (as is the case for geneontology/noctua#415 where dictyBase:DDB_G0280043 and owl:Nothing are the only matches), there can be like 67MB of graph over the wire and then parsing on the client.

This is probably not great for the server (@stuartmiysato, this may be related to the issues that you're suddenly having) and very bad for the client (which will likely choke on such a return).

This ticket will coordinate the clean-up effort.

**Comment by kltm** [comment]
@stuartmiyasato An update now that I've recovered my computer with oven mitts as it tried to burn through my desk--while it may not be the primary cause of your jetty issues (re: /visualize), this is certainly not helping and I could see how this would be very nasty on its own.

**Comment by kltm** [comment]
Have started test loads at Berkeley using the above owltools fixes.

**Comment by kltm** [comment]
Our "production" and NEO mirrors (http://amigo2.berkeleybop.org) seems to now be cleared of the problem.

@stuartmiyasato if the issue with the (possible) "/visualize" has not cleared up via other methods, it may be related to this. Either way, an update to the 2.4.x branch has been push that corrects the problem via `./java/lib/owltools-runner-all.jar`. All that should be required is a `git pull` on the loader machine before the next load.

**Comment by stuartmiyasato** [comment]
@kltm The load begins at 4pm local time and will push the new load out to the production AmiGO servers around 9pm.  I'm reluctant to do this update on a Friday and have to watch over it late on a Friday night/Saturday morning.  :)  I'll look into making this change on Monday, or possibly Sunday if my schedule permits.

FYI, jetty died on both production AmiGO servers again early this morning, but that was the only time since we started discussing this problem.

**Comment by kltm** [comment]
Thank you. If anything goes seriously wrong, don't hesitate to flip the CNAME onto us.

**Comment by stuartmiyasato** [comment]
I updated the loading server yesterday (4/30) and the data was pushed to the production AmiGO servers last night.  So far so good, but will keep an eye on it...

**Comment by kltm** [comment]
Terrific--thank you for you help!

**Comment by kltm** [comment]
Searching for `nothing` now turns up nothing--likely fixed.

**Comment by kshefchek** [comment]
This likely doesn't belong here, but go-plus.owl contains the axiom:

    Class: owl:Nothing SubClassOf: owl:Nothing

Could this be causing problems?
