### ISSUE TITLE
Add ability to filter redundant annotations

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#43]
- [x] Add a flag to the golr schema for annotation documents to state when an annotation is redundant
 - [ ] Populate this in the golr loading code
 - [ ] Add a test case 
 - [ ] Add a 'include redundant' toggle facet view; default is off (i.e. we remove redundant by default)

TBD:
do we want a globally redundant flag? Or make this relative to evidence code?

See also:
See also: http://jira.geneontology.org/browse/GO-144

Priority: post-Bar Harbor

**Comment by cmungall** [comment]
copying comments from @ValWood:

+1
At PomBase we do this with IEAs NAS and TAS,. We only use these to *supplement* manual annotation and discard anything which is less specific than any manual annotation. Nobody misses them and we remove 87% of our IEAs in this way (all but ~4000 currently). 

This has lots of other advantages as well making the annotation easier for our users to consume, the bad IEA annotations are now easy to spot.
https://github.com/geneontology/go-annotation/issues

http://www.slideshare.net/ValerieWood/pombase-internal-rules-for-curation-using-ontologies
slides 23 -28

**Comment by pgaudet** [comment]
Redundant with https://github.com/geneontology/go-site/issues/943
