### ISSUE TITLE
AmiGO down?

### ISSUE THREAD

**Issue by tberardini** [geneontology/amigo#431]
Not getting a response from 

http://amigo.geneontology.org/amigo

**Comment by kltm** [comment]
There has been a bit of fluttering today. Possibly a temporary outage--it seems to be on for me now.

**Comment by tberardini** [comment]
Yes, back again.  Thanks, @kltm .

**Comment by stuartmiyasato** [comment]
Just for the record, yes the service was definitely fluttering as it has been more regularly of late.  I restarted the servers and the service came back online.

**Comment by kltm** [comment]
@stuartmiyasato Thank you for your time on that--I was hoping that you wouldn't need to get involved.
(On a side note, one of our machines has been delivered, another has gotten lost somewhere within shipping...)
