### ISSUE TITLE
Evidence groupings have disappeared from amigo

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#433]
In #308 we added evidence groupings via a go_grouping subset, and populated a separate closure.

The groupings have vanished from amigo. Need to check if

 - axioms went missing from ontology (seems not; http://amigo.geneontology.org/amigo/term/ECO:0000006#display-lineage-tab)
 - something changed in owltools in the population of the subset closure

**Comment by kltm** [comment]
OWLTools is doubtful as we are version locked within AmiGO and there have been no updates (unless this is a very old problem that we initially missed).

**Comment by cmungall** [comment]
Definitely not being populated in golr: http://golr.geneontology.org/solr/select/?q=%2A%3A%2A&wt=json&fq=bioentity%3A%22ZFIN%3AZDB-GENE-050417-357%22&fq=document_category%3A%22annotation%22&fl=evidence_subset_closure_label%2Cevidence_label%2Cid%2Cassigned_by%2Csource%2Cbioentity%2Cbioentity_label%2Cbioentity%2Ctaxon%2Ctaxon_label%2Crelation%2Crelation_label%2Cannotation_class%2Cannotation_class_label%2Cevidence_object%2Cevidence_graph

**Comment by kltm** [comment]
q=*:*&fq=taxon_subset_closure_label:%22Mus%20musculus%22&fq=evidence_closure:%22ECO:0000006%22&sfq=document_category:%22annotation%22

vs

http://amigo.geneontology.org/amigo/search/annotation?q=*:*&fq=taxon_subset_closure_label:%22Mus%20musculus%22&fq=evidence_subset_closure:%22ECO:0000006%22&sfq=document_category:%22annotation%22

evidence_subset_closure vs evidence_subset.

the latter seems correct (thankfully), the former is...off?

**Comment by cmungall** [comment]
Yes, consistent with the golr query, the evidence_subset_closure does not have the groupings. Recall that the algorithm for populate subset_closures is always to include the direct term, plus the any ancestors that are in the subset

**Comment by kltm** [comment]
@ukemi thinks he might have first noticed something odd as well on Monday.

**Comment by kltm** [comment]
I'm trying to find an older index somewhere to compare to.

**Comment by cmungall** [comment]
The quickest fix would be to change the config

https://github.com/geneontology/amigo/search?utf8=%E2%9C%93&q=%22eco.owl%22&type=

to load this PURL for eco
http://purl.obolibrary.org/obo/eco/releases/2017-07-10/eco.owl

**Comment by cmungall** [comment]
The loader code was written with resiliency in mind:

https://github.com/owlcollab/owltools/blob/41e1f585d7a8135081c3f2e56c4aa6590901227b/OWLTools-Solr/src/main/java/owltools/solrj/GafSolrDocumentLoader.java#L690

But the substring approach doesn't work here, for obo2owl reasons the new subset URL compacts to "go:groupings"

**Comment by kltm** [comment]
(@cmungall has gotten me to breathe into a paper bag, degrading severity)

**Comment by kltm** [comment]
@cmungall I'm a little surprised that this hasn't cleared yet. This should be already corrected upstream and have gotten caught in the loads.

**Comment by ValWood** [comment]
Can we get these back soon. Its really difficult to locate EXP annotation sets to check pending obsoletions and ontology changes without it.
Cheers,

**Comment by kltm** [comment]
@cmungall Any ideas about why this has not been picked up yet?
https://github.com/geneontology/amigo/issues/433#issuecomment-325212016

**Comment by cmungall** [comment]
https://github.com/evidenceontology/evidenceontology/issues/149#issuecomment-331252784

**Comment by kltm** [comment]
@ValWood okay, it looks like we'll get this back on the next reload now. Thank you for your patience.

**Comment by ValWood** [comment]
I see it is out of your control ;)

**Comment by mchibucos** [comment]
Yeah, sorry @ValWood, sorry @kltm ! At ECO we had some miscommunication (https://github.com/evidenceontology/evidenceontology/issues/149) - thought this had been fixed. 👎 After speaking to @cmungall I believe that we can now implement better checks moving forward so that our release process doesn't cause this type of thing again. Thank you all for your patience. -Marcus

**Comment by ValWood** [comment]
No worries Marcus. Thanks all.

**Comment by kltm** [comment]
I believe that this has cleared now? Thank you @mchibucos
