### ISSUE TITLE
SGD IDs missing from GO database / submitted GAF

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#434]
I can't find these SGD ~ORDs~  ORFs in AmiGO.
The aren't new or recently annotated....

 YBL048W YBR144C YBR209W YBR292C YDR010C YDR215C YER188W YFL019C YGR164W YHR093W YIL012W YIL071C YIL086C YJL146W YLR111W YLR112W YLR236C YLR255C YLR296W YMR212C YMR254C YOL118C YOL160W YOR072W YOR235W YOR314W YOR343C YPL062W YPL080C YPR014C YPR195C

http://www.yeastgenome.org/locus/S000001333/overview#go

**Comment by ValWood** [comment]
Although oddly when I try to get to theis entry in QuickGO I get
http://www.ebi.ac.uk/QuickGO/404?ac=P40512

the page does not exist.

So maybe UniProt GOA "lost" some entries and they aren't getting through to GO database.....
But  these are all in SGD.....

**Comment by ValWood** [comment]
@srengel

**Comment by cmungall** [comment]
You mean ORF not ORD?

These are not in the GAF submitted by SGD (either with Sxxxx IDs or systematic synonyms).

Hunch: they are filtering out genes that only have ND or high throughput evidence?

**Comment by ValWood** [comment]
I don't think so. Some of these are annotated in SGD see  S000001333 above.

**Comment by ValWood** [comment]
...and its not all of the NDs, that  would be many....
I can't see anything common about this subset...

**Comment by cmungall** [comment]
YIL071C is in there: http://amigo.geneontology.org/amigo/gene_product/SGD:S000001333

**Comment by srengel** [comment]
Yikes.  I'll have to take a look at this but I can't get to it until tomorrow...will look then.

**Comment by kltm** [comment]
YMR212C and YJL146W also found; the rest seem to not be in the index
http://amigo.geneontology.org/amigo/bulk_search/bioentity

**Comment by ValWood** [comment]
For the record, I came across this using the Princeton slimmer

Your input list contains 5915 genes.

These 31 identifiers were found to be unannotated: YBL048W YBR144C YBR209W YBR292C YDR010C YDR215C YER188W YFL019C YGR164W YHR093W YIL012W YIL071C YIL086C YJL146W YLR111W YLR112W YLR236C YLR255C YLR296W YMR212C YMR254C YOL118C YOL160W YOR072W YOR235W YOR314W YOR343C YPL062W YPL080C YPR014C YPR195C

The list came out of yeastmine yesterday.
So it seems that somehow  entries are appearing and disappearing, if 3 of these are now there...

**Comment by ValWood** [comment]
OK< similar issue with pombe and  everything was there last week.
We haven' t updated the  GAF at GO recently.....

These 1 identifiers were found to be unannotated: SPCC10H11.02


So, it  does appear to be a GO issue.

@mah11  can you confirm?

**Comment by ValWood** [comment]
@mah11, no need to check, it is in the GAF

grep SPCC10H11.02 gene_association.pombase 
PomBase	SPCC10H11.02	cwf23		GO:0005730	PMID:16823372	IDA	DNAJ domain protein Cwf23	SPCP31B10.01	protein	taxon:4896	2009111PomBase		
PomBase	SPCC10H11.02	cwf23		GO:0005681	GO_REF:0000037	IEA	UniProtKB-KW:KW-0747	C	DNAJ domain protein Cwf23	SPCP31B10.01	protein	taxon:4896	20170114	UniProt		
PomBase	SPCC10H11.02	cwf23		GO:0005634	PMID:16823372	IDA	DNAJ domain protein Cwf23	SPCP31B10.01	protein	taxon:4896	2009111PomBase		
PomBase	SPCC10H11.02	cwf23		GO:0030544	GO_REF:0000050	ISM	Pfam:PF00226	F	DNAJ domain protein Cwf23	SPCP31B10.01	proteintaxon:4896	20040413	PomBase	

So, some entries in the GAFs are not in the GO database.
I have been using  the GO term mapper regularly recently, and  everything has been present. I think this must have occurred some time over the past couple of weeks.....

**Comment by ValWood** [comment]
Actually there *is* something odd about  SPCC10H11.02
there is nothing in the aspect column for 2 rows. How did that get through the submission checks?

And if I grep on column 9 on our downloaded GAF:

val$ cut -f 9 gene_association.pombase |sort | uniq -c
   9 !
17130 C
12448 F
11671 P

 @mah can you trouble-shoot this at our end? Can't figure that out...

**Comment by mah11** [comment]
> Actually there is something odd about SPCC10H11.02 there is nothing in the aspect column for 2 rows.

This is not true in the actual GAFs (I looked at the latest in the GO repository and the one from the latest build).

> How did that get through the submission checks?

All the columns are actually there, and the aspect isn't missing from any of them.

I also don't see anything wrong with your cut -f9 numbers - they add up to the number of non-header lines in the file.

**Comment by ValWood** [comment]
Ah OK. That's weird. I still can't see the aspect in the 	GO:0005730 and the GO:0005634 GAF lines. Its like that meme where you are given a sentence and asked to count the number of F's...I'm still looking....

**Comment by mah11** [comment]
They are missing from what you pasted above. That is beyond weird - I can't explain it - but I definitely do see them when I grep or look at the GAF in an editor (which is a thing only for the mad ...).

**Comment by ValWood** [comment]
Yep, its odd .....odd

**Comment by ValWood** [comment]
Bizarre...I reunzipped the file, and there they are:


Val-Woods-MacBook-Pro:Downloads val$ grep SPCC10H11.02 gene_association.pombase
PomBase	SPCC10H11.02	cwf23		GO:0005730	PMID:16823372	IDA		C	DNAJ domain protein Cwf23	SPCP31B10.01	protein	taxon:4896	20091111	PomBase		
PomBase	SPCC10H11.02	cwf23		GO:0005681	GO_REF:0000037	IEA	UniProtKB-KW:KW-0747	C	DNAJ domain protein Cwf23	SPCP31B10.01	protein	taxon:4896	20170114	UniProt		
PomBase	SPCC10H11.02	cwf23		GO:0005634	PMID:16823372	IDA		C	DNAJ domain protein Cwf23	SPCP31B10.01	protein	taxon:4896	20091111	PomBase		
PomBase	SPCC10H11.02	cwf23		GO:0030544	GO_REF:0000050	ISM	Pfam:PF00226	F	DNAJ domain protein Cwf23	SPCP31B10.01	protein	taxon:4896	20040413	PomBase	


baffled....

and they aren't in the earlier file even in an editor.....


Val-Woods-MacBook-Pro:Downloads val$ grep SPCC10H11.02 gene_association.pombase_2 
PomBase	SPCC10H11.02	cwf23		GO:0005730	PMID:16823372	IDA	DNAJ domain protein Cwf23	SPCP31B10.01	protein	taxon:4896	2009111PomBase		
PomBase	SPCC10H11.02	cwf23		GO:0005681	GO_REF:0000037	IEA	UniProtKB-KW:KW-0747	C	DNAJ domain protein Cwf23	SPCP31B10.01	protein	taxon:4896	20170114	UniProt		
PomBase	SPCC10H11.02	cwf23		GO:0005634	PMID:16823372	IDA	DNAJ domain protein Cwf23	SPCP31B10.01	protein	taxon:4896	2009111PomBase		
PomBase	SPCC10H11.02	cwf23		GO:0030544	GO_REF:0000050	ISM	Pfam:PF00226	F	DNAJ domain protein Cwf23	SPCP31B10.01	proteintaxon:4896	20040413	PomBase

**Comment by cmungall** [comment]
To summarize, is there any issue other than the one about SGD not submitting all NDs or high throughputs to their GAF (which is not necessarily a problem, just something requiring clarification)?

**Comment by ValWood** [comment]
I think there is a problem.

At least one pombe protein is in the GAF, but is not in AmiGO SPCC10H11.02
The same appears to be tru of most of the SGD IDs above too. Stacia would need to confirm if they are in the SGD GAF.

Also, of the 3  SGDs which are present now, they were not present in a recent GO database (the one  used by GO term mapper yesterday).

I think there is a problem, that some genes in the GAF are not getting into the database for some reason.

**Comment by srengel** [comment]
i checked one ORF YIL071C so far.  it's in the SGD GAF dated 01/14/2017 (that's our most recent).

9 rows in the GAF for this ORF, 7 in AmiGO.  The two IMP rows are not in AmiGO.

GAF rows:
SGD	S000001333	PCI8		GO:0005634	SGD_REF:S000148669	IEA	UniProtKB-KW:KW-0539	C	Possible shared subunit of Cop9 signalosome (CSN) and eIF3	YIL071C|CSN11|YIH1|YIL071W	gene	taxon:559292	20170107	UniProt		
SGD	S000001333	PCI8		GO:0005634	SGD_REF:S000148671	IEA	UniProtKB-SubCell:SL-0191	C	Possible shared subunit of Cop9 signalosome (CSN) and eIF3	YIL071C|CSN11|YIH1|YIL071W	gene	taxon:559292	20170107	UniProt		
SGD	S000001333	PCI8		GO:0005737	SGD_REF:S000148669	IEA	UniProtKB-KW:KW-0963	C	Possible shared subunit of Cop9 signalosome (CSN) and eIF3	YIL071C|CSN11|YIH1|YIL071W	gene	taxon:559292	20170107	UniProt		
SGD	S000001333	PCI8		GO:0005737	SGD_REF:S000148671	IEA	UniProtKB-SubCell:SL-0086	C	Possible shared subunit of Cop9 signalosome (CSN) and eIF3	YIL071C|CSN11|YIH1|YIL071W	gene	taxon:559292	20170107	UniProt		
SGD	S000001333	PCI8		GO:0003674	SGD_REF:S000069584	ND		F	Possible shared subunit of Cop9 signalosome (CSN) and eIF3	YIL071C|CSN11|YIH1|YIL071W	gene	taxon:559292	20030325	SGD		
SGD	S000001333	PCI8		GO:0008180	SGD_REF:S000148669	IEA	UniProtKB-KW:KW-0736	C	Possible shared subunit of Cop9 signalosome (CSN) and eIF3	YIL071C|CSN11|YIH1|YIL071W	gene	taxon:559292	20170107	UniProt		
SGD	S000001333	PCI8		GO:0010388	SGD_REF:S000071980|PMID:12446563	IMP		P	Possible shared subunit of Cop9 signalosome (CSN) and eIF3	YIL071C|CSN11|YIH1|YIL071W	gene	taxon:559292	20100115	SGD		
SGD	S000001333	PCI8		GO:0008180	SGD_REF:S000071980|PMID:12446563	IDA		C	Possible shared subunit of Cop9 signalosome (CSN) and eIF3	YIL071C|CSN11|YIH1|YIL071W	gene	taxon:559292	20030325	SGD		
SGD	S000001333	PCI8		GO:0010388	SGD_REF:S000071602|PMID:12186635	IMP		P	Possible shared subunit of Cop9 signalosome (CSN) and eIF3	YIL071C|CSN11|YIH1|YIL071W	gene	taxon:559292	20100115	SGD

**Comment by ValWood** [comment]
So today as expected GO term mapper matched current GO...

Your input list contains 5915 genes.

These 28 identifiers were found to be unannotated: YBL048W YBR144C YBR209W YBR292C YDR010C YDR215C YER188W YFL019C YGR164W YHR093W YIL012W YIL086C YLR111W YLR112W YLR236C YLR255C YLR296W YMR254C YOL118C YOL160W YOR072W YOR235W YOR314W YOR343C YPL062W YPL080C YPR014C YPR195C


@cmungall any ideas what is happening here?

**Comment by ValWood** [comment]
We submitted a new GAF a few days ago. This is now showing in AmiGO and is the current dataset used by the GO term mapper.

Now it is even worse. 27 IDs which are in our GAF are missing from the GO database. Is anyone following up on this? It's quite important.  The label "blocked/upstream" makes it seem as though you are waiting for a fix from elsewhere?

Val

These 27 identifiers were not annotated in the slim, but they had non-root annotations that were not in the slim: SPBC1539.06 SPAC2F7.10 SPAC607.04 SPAC17G6.04c SPBC2G2.09c SPAC2E1P5.04c SPAPB1A10.04c SPCC794.08 SPBC3H7.09 SPAC3F10.07c SPCC1919.12c SPCC4B3.10c SPCC970.08 SPAC144.14 SPBC216.04c SPBC119.09c SPAC869.08 SPBP4G3.02 SPBC20F10.10 SPBC1347.11 SPBC13G1.07 SPCC1795.09 SPAC1002.07c SPAC11E3.14 SPBC21H7.03c SPBC83.16c SPBP4H10.17c

**Comment by ValWood** [comment]
Even  *more* bizarrely, I just noticed that when you search on htese IDs they actually appear in the autocomplete. So something thinks they are there.

I search on SPCC4B3.10c 
and I see
ipk1 (PomBase:SPCC4B3.10c )

but I get
Nothing found for  SPCC4B3.10c. Please try again.

**Comment by ValWood** [comment]
I tried again and I did get the page.
Then I did the same  for  SPCC794.08
Nothing found for SPCC794.08. Please try again.

It's clear that its something more fundamental then AmiGO if the dataset picket up by Princeton is missing these entries. But it is also intermittent. I hope this helps.

**Comment by ValWood** [comment]
I hit return I get
http://amigo.geneontology.org/amigo/medial_search?q=SPCC4B3.10c
Nothing found for SPCC4B3.10c. Please try again.

I select from the drop down and I get
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPCC4B3.10c

**Comment by cmungall** [comment]
Hi @ValWood - this ticket was originally about things not appearing in the SGD GAF. We still haven't resolved it but it's more of an annotation issue. We could potentially move the ticket.

Can we start a new ticket for everything starting from https://github.com/geneontology/amigo/issues/434#issuecomment-323087324 as this most likely unconnected

**Comment by ValWood** [comment]
Hi Chris,
I opened a new ticket for the AmiGO behavior, which may have confused this issue.

There is however a problem.

Some gene products are in our GAFs  but they do not appear in the GO term mapper.

The issue reported by Stacia above is still current.

These IMP annotations are in the GAF but not in AmiGO
SGD	S000001333	PCI8	GO:0010388	SGD_REF:S000071980|PMID:12446563	IMP	P	Possible shared subunit of Cop9 signalosome (CSN) and eIF3	YIL071C|CSN11|YIH1|YIL071W	gene	taxon:559292 20100115	SGD

SGD	S000001333	PCI8	GO:0010388	SGD_REF:S000071602|PMID:12186635	IMP	P	Possible shared subunit of Cop9 signalosome (CSN) and eIF3	YIL071C|CSN11|YIH1|YIL071W	gene	taxon:559292 20100115	SGD

**Comment by ValWood** [comment]
YER188W  is in the GAF but not in AmiGO?

**Comment by cmungall** [comment]
I believe I have successfully diagnosed the SGD issue, I made a ticket for @srengel on the annotations tracker: https://github.com/geneontology/amigo/issues/434

Now on to the PomBase issue... (@srengel, you can ignore this ticket from here on if you like)

**Comment by ValWood** [comment]
There is no PomBase issue. That was a PICNIC caused by
https://github.com/geneontology/amigo/issues/435
(and all the pombe genes are now in GO term mapper. Here I was looking at the unmapped list, not the unannotated list. I am not used to it being such a short list.....)

All good!

**Comment by cmungall** [comment]
OK, I have properly diagnosed the second SGD issue, the disappearance of the IMP annotations of S000001333 to GO:0010388. This GO term has been merged. @srengel you or someone at SGD should be getting emails telling you of this (note: we'll soon switch to jenkins for these notifications, and it will be easier for us to collectively debug, cc @kltm @dougli1sqrd - also when we switch to jenkins we will be more generous in repairing on the fly).

Feel free to make a new go-annotation ticket for this.

To summarize where we are with SGD:

 1. some IDs are in SGD but not in the GAF because the GAF is old, noted here https://github.com/geneontology/go-annotation/issues/1619, @srengel confirms this is a known issue and will be resolved soon
 2. some of the GO IDs in the SGD GAF are to merged or obsoleted classes (as expected, as a GAF ages the more 'bitrot' we see). This will be fixed either by a new SGD GAF or by switching to the jenkins pipeline (where we are generous with repairs).

Neither of the above are relevant to AmiGO. However, admittedly we could do a better job of displaying metadata about what processing was done on the GAF. I made a ticket for this: #436 but don't consider this a high priority one.

OK, now onto the PomBase issue...

**Comment by srengel** [comment]
just one quick follow-up re GO:0010388 and @cmungall 's comment above that SGD should have been notified via email re that term being merged...

this ID isn't actually being used for annotation at SGD.  it is just lingering in our 1/17/17 gaf because our database is frozen, and so our gaf no longer matches our set in P2GO.  just letting you guys know that it's a freeze issue on our end, not a communication/notification issue.  so all is fine there.  thank you.
