### ISSUE TITLE
Amigo Search behaviour upon <return>

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#435]
If search on SPCC4B3.10c
and I see
ipk1 (PomBase:SPCC4B3.10c ) in the dropdown

But If I hit return

I get
Nothing found for SPCC4B3.10c. Please try again.

I'm not sure if this was causing us not to find the genes missing from AmiGO here or not

**Comment by kltm** [comment]
Dupe on #120 (and #269 previously).
