### ISSUE TITLE
Annotations: Improve View of Organisms Facet 

### ISSUE THREAD

**Issue by tberardini** [geneontology/amigo#437]
Suggest a view that is not a straight list with more general classes at top but structured as a hierarchy instead.  Can determine distribution of organisms with annotations, also figure out where specific species with not immediately identifiable names fall.

**Comment by kltm** [comment]
We need to port these tickets over some time, but this is a good place to hang them.
Duplicated in:
berkeleybop/bbop-js#30
berkeleybop/bbop-js#8
#84
