### ISSUE TITLE
AmiGO not displaying part_of extensions

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#439]
AmiGO isn't  showing part_of BP extensions 
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPBC11B10.09

you can see some the missing extensions here:
http://preview.pombase.org/gene/SPBC11B10.09

**Comment by cmungall** [comment]
I checked one at random

in a recent GAF:

```
PomBase SPBC11B10.09    cdc2            GO:0004674      PMID:22065639   IDA             F       cyclin-dependent protein kinase Cdk1/Cdc2
        swo2|cdk1|tws1|wee2     protein taxon:4896      20130905        PomBase happens_during(GO:0000089),has_direct_input(PomBase:SPAC3G9.01),part_of(GO:1902424)      
```

but I don't see this in amigo at all, so perhaps nothung to do with extensions, instead annotation lag or this is getting filtered somehow...?

**Comment by ValWood** [comment]
We are pretty up  to date now with our gaf, and we shouldn't have any errors...
I'll have a look.

**Comment by ValWood** [comment]
I see it in AmiGO
![amigo](https://user-images.githubusercontent.com/7359272/30223112-67c05cf0-94c1-11e7-9334-4fd64447142e.jpg)

**Comment by cmungall** [comment]
I see the part-of here:

![image](https://user-images.githubusercontent.com/50745/30226427-cd1aa100-948a-11e7-9f82-143d6a6f7cf8.png)

**Comment by cmungall** [comment]
OK, what seems to be happening is that some annotations are in there more than once. In this case, once without the part_of, once with.

**Comment by cmungall** [comment]
```
$ curl -L http://www.geneontology.org/gene-associations/submission/gene_association.pombase.gz | gzip -dc | grep SPBC11B10.09 | grep SPAC3G9.01
PomBase SPBC11B10.09    cdc2            GO:0004693      PMID:27984725   EXP             F       cyclin-dependent protein kinase Cdk1/Cdc2
        cdk1    protein taxon:4896      20170706        PomBase happens_during(GO:0000087),has_direct_input(PomBase:SPAC3G9.01) 
PomBase SPBC11B10.09    cdc2            GO:0004693      PMID:22065639   IDA             F       cyclin-dependent protein kinase Cdk1/Cdc2
        cdk1    protein taxon:4896      20130905        PomBase happens_during(GO:0000089),has_direct_input(PomBase:SPAC3G9.01),part_of(GO:1902424)      
```

amigo is faithfully showing what is in your gaf...

**Comment by cmungall** [comment]
Huh, I didn't realize you did EXP annotations but I see 500 of them.

I think there is a case to be made for a display summarizing these 288 annotations for this gene in a more compact way, sure we have a ticket for this...

**Comment by ValWood** [comment]
> OK, what seems to be happening is that some annotations are in there more than once. In this case, once without the part_of, once with.

whoops sorry, I looked through a lot and I couldn't see anyMF part_of BP but that is probably  just by chance because there are a lot of annotations, I didn't look enough...

> Huh, I didn't realize you did EXP annotations but I see 500 of them.

Yep we use EXP sometimes if  the annotation is by  a combination of different experiment types. 


>I think there is a case to be made for a display summarizing these 288 annotations for this gene in a more compact way, sure we have a ticket for this...

This looks crazy I admit, and cdc2 is an extreme example because it integrates all of the signals for:
"I am ready to replicate my DNA"  (cell size,  nutrient  etc)
then
 "I am ready to divide", (cell size, DNA replicated properly)  
After these checkpoints are satisfied, it is also the major controller  (both positive and negative, via different  direct targets)  of all of the downstream processes, in each case e.g. : DNA replication in S-phase
various aspects  of spindle assembly, chromosome segregation, cytokinesis in M-phase.  
This is the tip of the iceberg, it also integrates metabolism with cell growth.   It is also pretty universal. 75% of pombe genes have human orthologs and most of the targets will be conserved too.

We are beginning to establish the bigger picture, but please don't ask me to build a Noctua model  of this. Life is too short we are modelling an entire cell :).

More follow up later...

**Comment by ValWood** [comment]
> sure we have a ticket for this...

Is that 
you are sure we have a ticket for this
or
make sure I open a ticket for this?
