### ISSUE TITLE
Compact gene specific display

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#440]
Follow on from 

https://github.com/geneontology/amigo/issues/439#issuecomment-328185847

Many genes have a huge amount of information.
AmiGO probably needs more compact ways to show data on a gene by gene basis.

In PomBase cdc2 MF looks like this:

![mf](https://user-images.githubusercontent.com/7359272/30580461-7dd7e8d6-9d14-11e7-9676-2c02ef99ee57.jpg)

Eventually we will link all of these substrates to the processes that cdc2 is regulating, and the specific cell cycle phase they are operational.

These are some of the things we do to compact the display:

1. We do not consume TAS,NAS,IC,IEA annotations if they are covered by EXP annotations
(this removes >40,000 annotations,  bit more than 50% will check the exact number)
These do not come through to GO either for fission yeast, but for other species the number of annotations will be compounded by this additional redundancy.

2.  For display purposes we are  interested in the biology rather than the evidence or source so we hide the evidence and publication by default. This allows us to group multiple identical annotations.

3. We only display the most specific annotation.
The list of terms is filtered, using the ontology structure, so that it shows only the most specific terms used to annotate a genotype, and each unique combination of gene, GO term, and extension(s) is shown once:

Note that 2. and 3 are available  using “show details” so would can see all less specific annotation, evidence and sources contributing to the “unique, specific annotation” in the summary view.

Note that in the GAF, and AMiGO this is 288 annotation lines
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPBC11B10.09

**Comment by kltm** [comment]
Note #295

**Comment by pgaudet** [comment]
This ticket encompasses all the points here: https://github.com/geneontology/go-site/issues/943
