### ISSUE TITLE
amigo search weighting for exact matches

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#447]
Amigo does not seem to be weighted very well for exact matches. I noticed this quite a lot recently.

For example if I search on "transport" Ii do not find it in the top hits even though it is an exact match of a primary term name.

In these cases I have been going to QuickGO, doing the search to find the ID, and then coming back using the ID. It happens quite a lot and it's really annoying.....

**Comment by kltm** [comment]
Duplicate on https://github.com/geneontology/amigo/issues/102
