### ISSUE TITLE
AmiGO load date / last load date out of sync

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#448]
ON the AmiGO pages, it says
Last file loaded on 2017-07-05,

that seems odd?

**Comment by kltm** [comment]
@ValWood This wrong, due to some metadata files not getting updated on the production servers. This will be fixed as part of the process of bringing the production site into Berkeley.

**Comment by kltm** [comment]
Apologies, this is a "known" problem from a little back. I'm unable to find the related issues, so leaving this up until closed.

**Comment by cmungall** [comment]
I believe this is fixed
