### ISSUE TITLE
Add a filter for "assigned by" option to the matrix (like taxon)

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#455]
Hi @kltm ,

How easy is it to add a filter for "assigned by "   option to the matrix tool (like taxon).

We would like to be able to assess their quality globally using annotation intersections.

Cheers

Val

CC
@pgaudet

**Comment by kltm** [comment]
To clarify from here: http://amigo.geneontology.org/amigo/search/bioentity
Could what you want be covered "source", or is "assigned_by" what's needed? The former is (I believe) trivial, the latter harder as we do not currently load "assigned_by" for `bioentity` documents.

**Comment by ValWood** [comment]
gaf column15 "assigned by"
so we can distinguish between different groups curating via UniProt/protein2go

**Comment by kltm** [comment]
This will unfortunately take longer then to get into production (or dev) as we'll have to do new releases of owltools, update the scheme, reload, etc., etc.

**Comment by ValWood** [comment]
OK  it was just a thought. I see you don't have "assigned by" in AmiGO either.
Don't worry if it's tricky. There are probably other ways of dealing with them.

**Comment by kltm** [comment]
Sadly, not particularly tricky, just a lot of things that need to be moved forward at once. We may be able to filter the annotations after the fact, but the `assigned_by` is just not currently available in `bioentity` docs.
