### ISSUE TITLE
db-xrefs.yaml  breaking  python3 yaml parser

### ISSUE THREAD

**Issue by TomConlin** [geneontology/amigo#457]
minimal example 
```
import requests
import yaml
response = requests.get('http://current.geneontology.org/metadata/db-xrefs.yaml')
result = yaml.load(response.text)
```
yields :  

```
    ...  snip cruft

ParserError: while parsing a block mapping
  in "<unicode string>", line 1424, column 7:
        - type_name: gene
          ^
expected <block end>, but found '['
  in "<unicode string>", line 1426, column 23:
          id_syntax: [A-Z][A-Za-z0-9_]+(\.[0-9])?
```

Maybe a goose chase but   
I do notice variation  enclosing the ```id_syntax``` regular expressions in single quotes     
but this one on line 1424 is the second instance  of adjacent character classes 
 ```...][...```
without enclosing tics not the first.

**Comment by kltm** [comment]
This issue was moved to geneontology/go-site#464
