### ISSUE TITLE
AmiGO download - please add column labels

### ISSUE THREAD

**Issue by pgaudet** [geneontology/amigo#461]
Hello, 
When you download annotations from AmiGO the columns are not labeled; can this please be added? 

Thanks, Pascale

**Comment by ValWood** [comment]
See also
https://github.com/geneontology/amigo/issues/194

**Comment by kltm** [comment]
@pgaudet 
This is actually a limitation of grabbing the downloads directly from Solr, and solr does not supply column headers in this version. To implement this, we'd have to pass the results through another server to inject them; I am doubtful this would scale well for larger results sets and would be another component to fail within the system.
We may want to revisit this later on once the backend has switched to something that would support this more cleanly.
