### ISSUE TITLE
Runtime errors today

### ISSUE THREAD

**Issue by ukemi** [geneontology/amigo#466]
We are getting a lot of runtime errors today when searching AmiGO2.

**Comment by kltm** [comment]
It looks like production has been fluttering as bit. Hopefully it has stabilized; it seems to work now anyways. We're trying to get things ticking over here so we can move the systems over.

**Comment by kltm** [comment]
Well...it may be that we are production at the moment.

@stuartmiyasato Just to check here, it looks like amigo.geneontology.org is now resolving to nakama at Berkeley. Is this a temporary measure for the fluttering or should we be treating it as something more permanent?

**Comment by stuartmiyasato** [comment]
@kltm I would *like* it to be more permanent, but you know...  :)  When it does this, it basically means the production web servers need to be restarted.  I'm doing that now.  But as you're noticing, I'm spending a lot less time monitoring these systems now -- I have my hands full with other tasks and unfortunately GO is dropping near the bottom of that list now...

**Comment by stuartmiyasato** [comment]
More relevant to the production behavior...  Back a year or two ago when Stanford had a data-center wide power shutdown, we set up DNS for amigo.geneontology.org to have a failover entry.  When a healthcheck to the Stanford load balanced address failed, DNS dynamically changed to point amigo.geneontology.org to nakama.  After the power maintenance was completed, I just kept that DNS configuration in place in case the Stanford servers ever stopped responding, like what happened earlier today.

**Comment by kltm** [comment]
Ooo, nice! I hadn't realized it was an automatic failover. That's good to know in case something like this happens again in the next few weeks. We had a bit of a scramble earlier when we realized we were "live" over here, trying to figure out if this was our world now :)

**Comment by kltm** [comment]
Remainder from a different world.
