### ISSUE TITLE
Clicking Advanced button on Term Enrichment service goes to pantherdb.org page with error

### ISSUE THREAD

**Issue by mugitty** [geneontology/amigo#467]
Scenario:
1.  Open http://amigo.geneontology.org/amigo
2.  Enter some genes under Term Enrichment service
3.  Click on Advanced button
4.  System forwards to pantherdb.org with error about invalid input

**Comment by kltm** [comment]
I don't think it was ever specced to pass input when clicking the "Advanced" button, just take people to the form without attempting a run.

**Comment by kltm** [comment]
Confirming that "Advanced" is just a link.

**Comment by kltm** [comment]
This might mean that the PANTHER link we use might need to be setup to allow a no-input starting point.
