### ISSUE TITLE
Data appears to be out of date

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#472]
it seems that AmiGO is not reporting current Protein2GO data?

see
https://github.com/geneontology/go-annotation/issues/1700#issuecomment-368788009

**Comment by pgaudet** [comment]
I know we now do monthly releases - @cmungall are the releases on a specific day? Or can you announce them ?

**Comment by ValWood** [comment]
> Or can you announce them

that would be nice...

**Comment by kltm** [comment]
Announcement requests are now captured in other tickets (e.g. https://github.com/geneontology/pipeline/issues/53 https://github.com/geneontology/go-site/issues/771).
AmiGO footer information should now be correct.
