### ISSUE TITLE
Human gene products inflated

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#477]
17510 from UniProt (which seems to be all annotated human gene products)
8591 as HGNC (PANther annotation), which are exact duplicates form PAnther

so for example MRPL39
http://amigo2.berkeleybop.org/amigo/search/bioentity?q=MRPL39

Please, please can this be fixed. We can't use human annotation for any analysis whilst this issue persists.

**Comment by cmungall** [comment]
See my comment here https://github.com/geneontology/helpdesk/issues/99#issuecomment-371574707 for an explanation of why this is persists

**Comment by kltm** [comment]
Dupe of: https://github.com/geneontology/helpdesk/issues/99
