### ISSUE TITLE
AmiGO footer information out of date

### ISSUE THREAD

**Issue by pgaudet** [geneontology/amigo#481]
Hello, 

The copyright an the data load information needs to be updated: 

<img width="1329" alt="image" src="https://user-images.githubusercontent.com/4782928/37592752-f623f3e0-2b6f-11e8-8b90-8fd4d8c652ef.png">

For the data: it would be nice to have the information : 
- ontology load date
- annotation load date

Thanks, Pascale

**Comment by kltm** [comment]
While the data is fine, metadata parts of the pipeline need work and have been failing. All of this will be fixed as we flip to Berkeley production.
Dupe of #472
