### ISSUE TITLE
Pulling in BP (biological process) regulation terms for molecular function annotation

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#483]
Whilst looking at
https://github.com/geneontology/go-ontology/issues/14138

I spotted lots of annotations to the term
ryanodine-sensitive calcium-release channel activity
http://amigo.geneontology.org/amigo/term/GO:0005219
which do not appear to be transporters?

In fact none are transporters.

I thought the default for Molecular function terms was to exclude regulates ?
(these aren't even "MF regulator terms" they are biological process regulation so they really should not be annotated to the MF teem at all?)

**Comment by kltm** [comment]
@vanaukenk @ukemi
I'm trying to find the right spot for this item; would it possibly in the go-ontology tracker?

**Comment by vanaukenk** [comment]
@kltm 
Possibly both AmiGO as well as annotation issues here?
If @ValWood can confirm, we can split out the annotation part to go-annotation.

**Comment by ValWood** [comment]
Yes this is covered by the existing ticket.
