### ISSUE TITLE
linker library fails to properly handle PAINT links

### ISSUE THREAD

**Issue by nathandunn** [geneontology/amigo#485]
Using this library from here:

https://www.npmjs.com/package/amigo2-instance-data

https://github.com/geneontology/amigo/blob/master/javascript/npm/amigo2-instance-data/lib/linker.js

To see example:
http://amigo.geneontology.org/amigo/gene_product/FB:FBgn0051352

link to:

PAINT_REF:24213

resolves to:

http://www.geneontology.org/gene-associations/submission/paint/24213/24213.txt

which resolves to:

```
Object not found!
The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error.

If you think this is a server error, please contact the webmaster.

Error 404
www-legacy.geneontology.org
Thu Apr 12 14:51:35 2018
Apache
```

Not sure if it just means the data is out of sync, or its just old.  

ping @kltm

**Comment by kltm** [comment]
@nathandunn It could be either. Check to see if what you want is in: https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml

**Comment by kltm** [comment]
Fair enough. I'll try and push a release ASAP.

**Comment by kltm** [comment]
While we now have:
amigo2-instance-data@2.5.11
I think this is actually the PANTHER problem we talked about last week.

**Comment by nathandunn** [comment]
2.5.11 fixed the reactome link .    There are still some problems with the paint / panther associations. 

http://www.pantree.org/node/annotationNode.jsp?id=PTN000689893

and paint ref doesn't resolve:

http://www.geneontology.org/gene-associations/submission/paint/24372/24372.txt

but I agree that it is likely the previous problem as well.

**Comment by kltm** [comment]
That reactome thing is weird, as it worked on the command line. Solved is solved though.

The PANTHER stuff would seem to be the fact that they change their IDs on each release and have no mapping. Or the upstream db-xrefs.yaml is wrong. Either way, not in this package. If there is an upstream fix that requires code or a re-release, we can reopen.
