### ISSUE TITLE
duplicate entry for pombe

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#488]
These 1 identifiers were found to be ambiguous: SPAC750.08c
http://amigo.geneontology.org/amigo/gene_product/UniProtKB:Q9P3E3

It seems this UniProt entry should not be in GO? not sure how this one gets in so not sure who to ask?

The correct PomBase entry is
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPAC750.08c

**Comment by cmungall** [comment]
This is coming from PANTHER. I filed a ticket here: https://github.com/geneontology/go-site/issues/621
