### ISSUE TITLE
term name sometimes does not appear

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#495]
see
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPCC162.08c

GO:0005487

![obsolete](https://user-images.githubusercontent.com/7359272/39529615-04da42d2-4e1f-11e8-9667-173e10b45893.jpg)

maybe it is obsolete? but in that case  it isn't very clear when you click on it....
http://amigo.geneontology.org/amigo/term/GO:0005487

**Comment by pgaudet** [comment]
It is the secondary ID of GO:0017056. 
The mapping should happen automatically...?

**Comment by kltm** [comment]
It looks like it was replaced by GO:0017056; this smacks of an upstream data problem--I had thought that there was automatic replacement in the pipeline in these cases. @dougli1sqrd , do you know if this actually occurs, or is it just in my head?

**Comment by pgaudet** [comment]
@kltm @cmungall @dougli1sqrd 

if it occurs- where would that be documented ? 
According to this, the rule exists: 
https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000020.md

but it says it's a 'soft check'; is this correct ? shouldn't it be a 'replace' script?


**TO DO**: It would be nice if each rule page pointed to the error report. 

Thanks, Pascale

**Comment by kltm** [comment]
@dougli1sqrd Can you confirm this one way or another, so we know where the upstream issue is and can move this out of the AmiGO tracker?

@pgaudet if you have a TODO, it should be opened in the proper tracker.

**Comment by kltm** [comment]
At least in this case, this has been cleared. This is/was likely an upstream data issue.

**Comment by kltm** [comment]
Found another instance with:
http://amigo.geneontology.org/amigo/search/annotation?q=GO:0001105&sfq=document_category:%22annotation%22

**Comment by pgaudet** [comment]
AFAIK this is the case for many merged terms.

**Comment by kltm** [comment]
@dougli1sqrd Is there currently not an upgrade step running in the GAF processing pipeline?

**Comment by pgaudet** [comment]
Fixed, thanks !!!!!!
