### ISSUE TITLE
PANTHER families not getting loaded into Solr index

### ISSUE THREAD

**Issue by pgaudet** [geneontology/amigo#498]
Hello, 

see for example http://amigo.geneontology.org/amigo/term/GO:0006171

There are many families annotated to this term, but when I click on the Panther families filter, there is a message "Nothing to filter.". 

Can you please look into this ?

Thanks, Pascale

**Comment by kltm** [comment]
Looking into PANTHER loading of GOlr index.

**Comment by kltm** [comment]
New loader image should cover this. Waiting for release run later this week.

**Comment by kltm** [comment]
New loader image should cover this. Waiting for release run later this week.

**Comment by pgaudet** [comment]
Hi @kltm 
This protein (PTHR12302) still doesn't have its family information show up in AmiGO.

Can you please check ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@kltm any update on this ? 
Some families are still missing. (go to: http://amigo.geneontology.org/amigo/term/GO:0006171 and filter for evidence code = IBA)

Thanks, Pascale

**Comment by kltm** [comment]
@pgaudet Check with the upstream data provider--the original issue, that there are no families has been fixed. That said, somebody will need to audit the data to see what's missing where. I'd start at the source.

**Comment by pgaudet** [comment]
Well I can certainly go back to the source. However you message "New loader image should cover this." made me thing that the problem was NOT at the source. 

Please next time if you could write a comment I am more likely to understand that'd be much appreciated. I wouldn't have waited 3 months to look into that again. 

Thanks, Pascale

**Comment by kltm** [comment]
@pgaudet The problem for the original ticket (no panther families) was not the source, it was the loader image, as described. 

What you're seeing is a new unrelated issue, that may well have its origin in the source.

**Comment by kltm** [comment]
As this ticket was for the code and replacement image, as tagged above, if there is also an issue with the data, we should make a new ticket.
