### ISSUE TITLE
Getting run time errors in AmiGO and failure to retrieve annotations for GO terms

### ISSUE THREAD

**Issue by addiehl** [geneontology/amigo#500]
Happening since the morning today, 5/14/18.

Just says pending... for the annotations tab; never resolves

Thanks

**Comment by kltm** [comment]
@addiehl 
While possibly a local network (or some other) issue, it may be useful to first try out some of the possibilities here: https://github.com/geneontology/helpdesk/issues/128

**Comment by addiehl** [comment]
Okay, on main machine, connected by wifi, happens in Firefox and Safari, even after programs are quit and restarted.  Does not happen in Chrome, which I was not previously using today.

On another machine, connected by ethernet, AmiGO works fine in all browsers.

So seemingly my bad, but this is an issue I have not seen before.

**Comment by ValWood** [comment]
I'm getting the same errors

**Comment by kltm** [comment]
I seem to have cleared it for @ValWood . The "hard" refreshes seem to be the most effective so far. We have not experimented with restarts, which may be ineffective unless they are purging the browser cache.

**Comment by addiehl** [comment]
The hard refreshes cleared the errors for me in Safari and Firefox.

**Comment by kltm** [comment]
@addiehl Thank you for your patience with this. It seems that some browsers are "sticky" with the DNS information that they hold beyond what we would expect. We will keep an eye on this issue and try to further isolate it.
