### ISSUE TITLE
Errors in searching genes/ontologies

### ISSUE THREAD

**Issue by lihaone** [geneontology/amigo#501]
I was trying to search the known ontologies for genes in AmiGO, it gave me this error: "Nothing found for tp53. Please try again." 

![image](https://user-images.githubusercontent.com/12952765/40115324-57e56d2a-5910-11e8-814c-8a1541390dab.png)

It also gave me errors when I was searching pathway terms through AmiGO or through Google. 
![image](https://user-images.githubusercontent.com/12952765/40115495-e8db8d6e-5910-11e8-8dd9-98faa0c01412.png)

**Comment by kltm** [comment]
@lihaone 
First, our apologies for the disruptions.

I suspect that you are no longer running into these issues? There was an outage earlier today and we made a few mitigation adjustments. I could not duplicate what you have above and am assuming that these are products of either the outages or the later mitigations. Please reopen if you have these issues again and we will explore some more.
