### ISSUE TITLE
Links to TAIR locus pages are wrong in AmiGO

### ISSUE THREAD

**Issue by tberardini** [geneontology/amigo#503]
Example:

http://amigo.geneontology.org/amigo/gene_product/TAIR:locus:2007651

The link URL to TAIR generated by AmiGO for locus:2007651 is

http://arabidopsis.org/servlets/TairObject?type=communication&id=locus:2007651

But should be:

https://www.arabidopsis.org/servlets/TairObject?accession=locus:2007651

Please fix.  Thank you.

**Comment by kltm** [comment]
This issue was moved to geneontology/go-site#659
