### ISSUE TITLE
PAINT annotations - merged terms not correctly handled

### ISSUE THREAD

**Issue by pgaudet** [geneontology/amigo#505]
Hello, 

I though that for merged terms some script was ran to fix the annotations to the new primary ID - evidently that's not the case. 
I suppose this is a ticket for @huaiyumi ? 

![image](https://user-images.githubusercontent.com/4782928/40479995-764267da-5f4d-11e8-97a6-4206e6e29ebe.png)

**Comment by cmungall** [comment]
Sorry, can you state what the problem is?

**Comment by pgaudet** [comment]
Hi @cmungall 
That ID (GO:0001187) has been merged into GO:0001164, which is why the ID shows in AmiGO and not the term label. 

Is this clearer ?

Thanks, Pascale

**Comment by huaiyumi** [comment]
The current gaf generated at the beginning of May already replaced the ID (GO:0001187) with the new one (GO:0001164). I think AmiGO has not incorporate our update yet.

**Comment by pgaudet** [comment]
@kltm what is the process to get the annotation in? Since there's been a release yesterday - how can we be sure not to miss the train next time ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@cmungall I thought we had agreed to filter on the evidence code, not the reference ?
