### ISSUE TITLE
IBA annotations with source = GOC

### ISSUE THREAD

**Issue by pgaudet** [geneontology/amigo#506]
Hello, 

I thought we shouldn't have any IBAs with source = GOC. 

Any idea where these come from ? And I suppose they need to be filtered out. 

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/4782928/40528524-90d26376-5ff1-11e8-9f78-bdd86f5c68cf.png">

@cmungall @huaiyumi @dougli1sqrd 

Thanks, Pascale

**Comment by pgaudet** [comment]
Correction : They seem to be coming from TAIR. I suppose that's covered in another ticket ?

**Comment by huaiyumi** [comment]
That is how the redundant annotations come from. I think we decided at the New York meeting to only use the IBAs from the paint gaf from now on.

**Comment by ValWood** [comment]
Oh yes I remember now. Will they disappear completely, or will only the redundant ones be filtered though?
@cmungall

**Comment by cmungall** [comment]
Closing as redundant with https://github.com/geneontology/go-site/issues/587

> Will they disappear completely, or will only the redundant ones be filtered though?

They will disappear completely, otherwise there would be no way of purging old entries. PAINT will be the only source of IBAs
