### ISSUE TITLE
Is GOOSE still being updated? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/amigo#509]
Hello, 

When I run this query in GOOSE (corresponding to GORULE:0000008): 
SELECT gene_product.symbol,
             CONCAT(gpx.xref_dbname, ':', gpx.xref_key) AS gpxref,
             IF(association.is_not=1,"NOT","") AS 'not',
             term.acc,
             term.name,
             term.term_type,
             evidence.code,
             db.name AS assigned_by
      FROM   association
             INNER JOIN gene_product
               ON association.gene_product_id = gene_product.id
             INNER JOIN dbxref AS gpx
               ON gene_product.dbxref_id = gpx.id
             INNER JOIN term
               ON association.term_id = term.id
             INNER JOIN evidence
               ON association.id = evidence.association_id
             INNER JOIN db
               ON association.source_db_id=db.id
      WHERE  evidence.code = 'IEP'
             AND term.term_type != 'biological_process'

I get 0 results in GOOSE, but there are 47 annotations according to AmiGO. 

Any idea why there is a discrepancy ? 

Thanks, Pascale

**Comment by kltm** [comment]
No rules should use the SQL--it is no longer supported.
https://github.com/geneontology/helpdesk/issues/4
It may be sporadically updated, but may no longer fit many use cases.

**Comment by pgaudet** [comment]
This wasn't really about the rules - it was about the fact that if the SQL is not supported, it shouldn't be available at all - or is there a reason to keep it, if the data returned are incorrect ?

**Comment by kltm** [comment]
There are plans to remove it from service, but we are in the transition period now and premature removal would likely cause more issues for users.
