### ISSUE TITLE
Implement a generalized version AmiGO1.x's term tree with annotation counts

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#51]
This has been requested by a couple of groups, and was apparently a loved feature of AmiGO 1.x.

There are likely two approaches to this. One is to add graph structure (as an option or when available) to accordion filters, by either having a browsable tree or a compact inferred view. This would likely be no small task and involve a more complicated configuration setup, in addition to solving the problems of getting it to work and display in such a small space.

Another approach would be create an entirely new widget/app that combines the accordion (see kltm/bbop-js#17) with a graph or tree view. While skirting some of the issues of the first approach, most of the ways of doing this off the top of my head either run into GET size issues, require solr 4.x (see kltm/bbop-js#16), and/or hammering the GOlr server with requests order the size of the current tree.

Any solution would need to have the base resolved in kltm/bbop-js before moving forward.

**Comment by kltm** [comment]
This has now been bumped to 2.3, with the expectation of getting it as part of the transition to Solr 5.x in berkeleybop/bbop-js#16.

**Comment by cmungall** [comment]
I think this is doable without solr 5.x if we restrict this to a drill down browser. Start with root node. Every expansion on a node N does a single facet count query constrained by `R_closure=N` which should provide counts for the majority of the child nodes (at times the tree will be imbalanced, can do subsequent queries OR we could simply have a direct_parent facet and query on that)

**Comment by kltm** [comment]
@cmungall This would no longer be a general solution, but rather a new widget built off of a drill-down (and a different ticket), which is fine.

This is different from above (https://github.com/geneontology/amigo/issues/51#issuecomment-25937164), but I'm not sure it would be performant either. Taking the example of locking onto CC and looking at the full facet counts for inferred annotation gave me a response in 15 seconds of full out wire and parsing. That bit is important since it will freeze the interface, and likely the browser, until completed. On slower connections this can be an issue: #62, and can lead to "JS not responding" errors.

If you're getting into the territory of having new fields to support this, I think that it would be easier to spend that time on the general solution (5.x), which would also open up a lot of new possibilities and fixes. Again, this ~~can~~ totally be done with what we have out there now, but I feel the hacks and workarounds necessary to make a nice fast widget for GO end users would be better spent on clearing a task that we need to do anyways to advance what we have.

**Comment by kltm** [comment]
We're finishing up a performant widget over in #163; I'm not even sure why this is marked as a separate item...
