### ISSUE TITLE
wormbase annotations use WormBase and WB

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#510]
I thought this was fixed before, but  when looking at EXP colocalizes_with:

![colocalizes_with](https://user-images.githubusercontent.com/7359272/41399776-1c2b6956-6fb3-11e8-834b-e08d61a882d1.jpg)

**Comment by ValWood** [comment]
@vanaukenk  just so you know

**Comment by vanaukenk** [comment]
@ValWood 
What term are you looking at?
We only have WB in our source file, so I'm wondering if these are annotations from WB that were made to other species?

**Comment by ValWood** [comment]
I did  cellular_component, filtered on qualifier contributes_to, filtered on experimental evidence codes.

v

**Comment by kltm** [comment]
This issue was moved to geneontology/go-site#685
