### ISSUE TITLE
redundancy from RNA central

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#511]
Having almost sorted out redundancy in proteins,  we now have multiple copies of the same RNA from RNA central (at least 5 copies of telomerase RNA here)
 Who should I tag?

http://amigo.geneontology.org/amigo/search/bioentity?q=*:*&fq=regulates_closure:%22GO:0005697%22&sfq=document_category:%22bioentity%22

**Comment by ValWood** [comment]
Who would look into this? I'm not sure...

**Comment by ValWood** [comment]
@cmungall @kltm ?

**Comment by kltm** [comment]
Let's start this out on the annotation tracker.

**Comment by kltm** [comment]
This issue was moved to geneontology/go-annotation#2023
