### ISSUE TITLE
C. elegans data missing from AmiGO

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/amigo#516]
_From @ValWood on July 13, 2018 16:50_

I can't see any C. elegans data in AmiGO?

@vanaukenk  any ideas?

I can't see anything when I filter on process?

_Copied from original issue: geneontology/helpdesk#145_

**Comment by vanaukenk** [comment]
I can find annotations to individual genes by searching on the gene name, but Caenorhabditis elegans is not available in the Organism filter list when I search on a GO term.

**Comment by vanaukenk** [comment]
@ValWood
I can see 'Caenorhabditis elegans' in the Organism filter list now for various terms; not sure what is/was happening.

**Comment by kltm** [comment]
Now worried there might be a relation to: https://github.com/geneontology/amigo/issues/69#issuecomment-404896239

**Comment by kltm** [comment]
Yes...I've been unable to duplicate.
This doesn't make a lot of sense, as there are not multiple servers that can be out-of-sync anymore.
