### ISSUE TITLE
Possible filtering oddity

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#519]
I think I mentioned this before.

Search on, for example "regulation of cellular process"

Filter on "direct annotations" 
this is what I see:

![amigo ticket gps does not make sense regulation of cellular process](https://user-images.githubusercontent.com/7359272/43196723-d10d7b80-9000-11e8-8268-b3404c39a8c5.jpg)

nucleus and cytoplasm can't be direct annotations for  "regulation of cellular process"

This is the GP view, the annotation view is fine.

It is showing all direct annotations for the  the gene products annotated to "regulation of cellular process", but this isn't the question I asked. It isn't intuitive (or useful?). If I wanted to see ALL direct annotations for a GP I would go to the GP page.....

**Comment by kltm** [comment]
@ValWood 
To clarify, on this page:
http://amigo.geneontology.org/amigo/search/bioentity?q=*:*&fq=regulates_closure:%22GO:0050794%22&sfq=document_category:%22bioentity%22
Where we are searching over gps and have pinned ourselves to GO:0050794, you believe that "nucleus" and "cytoplasm" should not appear in the direct annotations?

As a concrete example, http://amigo.geneontology.org/amigo/gene_product/GR_protein:Q9AVD0 should not be annotated to "nucleus" and http://amigo.geneontology.org/amigo/gene_product/JCVI_CMR:PFL_0418 should not be annotated to "cytoplasm"?

**Comment by ValWood** [comment]
No, I'm not saying that.
I just think the behaviour is odd, @pgaudet  don't you think so too? I think we discussed this before?

If you are searching on a term, filtering by  gene products annotated would you not expect to see only direct annotations to the branch that you searched on, not every single direct annotation for the  gene product.

I can't figure out how you can use this information in this way?

**Comment by ValWood** [comment]
OK this is an exact duplicate of
https://github.com/geneontology/amigo/issues/443
@cmungall  mentioned some  solution, but not implemented yet.....
Is this in the pipeline?

**Comment by kltm** [comment]
He mentioned some cosmetic fixes, but I'm not quite sure what he had in mind in this case. We can follow-up on the original ticket.
