### ISSUE TITLE
AmiGO timing out

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#524]
7:56 7:57 BST

can load page
http://amigo.geneontology.org/amigo/gene_product/SGD:S000001952

**Comment by ValWood** [comment]
I can go to Amigo and perform a search , reports 7 gene products, but I can't get any further.

**Comment by ValWood** [comment]
still hanging at  8:59 , and when I tried in between

**Comment by kltm** [comment]
@ValWood Hm...works for me instantly, and there have been no reports of outages by my various robots. I'll leave this open for a bit to see if we can repeat.

**Comment by selewis** [comment]
I did experience a brief flash of this earlier today. When I first clicked I got the error, but when I retried there was no problem. Different call though (it was for a term)

**Comment by kltm** [comment]
No apparent repeats or duplication.
