### ISSUE TITLE
Human entries missing (e.g. Q6P6B7 and ANKRD16)

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/amigo#526]
_From @ValWood on August 2, 2018 21:52_

The canonical (UniProt) entry for Q6P6B7/ANKRD16** doesn't appear to be in AmiGO.
Can we find out why? It's quite inportant that we have all human gene products.

@Antonialock  please tag the Nature paper on this ticket:

_Copied from original issue: geneontology/helpdesk#152_

**Comment by suzialeksander** [comment]
_From @ValWood on August 2, 2018 21:52_

AmiGO only has mouse and D. rerio
http://amigo.geneontology.org/amigo/search/bioentity?q=ANKRD16

Seems very odd?

**Comment by suzialeksander** [comment]
_From @Antonialock on August 2, 2018 21:53_

https://www.nature.com/articles/s41586-018-0137-8.pdf

**Comment by suzialeksander** [comment]
_From @Antonialock on August 2, 2018 21:54_

https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=Q6P6B7

**Comment by suzialeksander** [comment]
_From @ValWood on August 2, 2018 21:55_

Is annotated in QuickGO by ISS.

**Comment by suzialeksander** [comment]
_From @ValWood on August 2, 2018 23:17_

Another Q5VXU9 c9orf84/SHOC1 is also not in AMiGO

**Comment by suzialeksander** [comment]
_From @ValWood on August 3, 2018 6:36_

I really think we should have a sanity check that all of the human proteins are in  the GO database (once only!).  We have been trying to do this work since February ......

**Comment by suzialeksander** [comment]
_From @ValWood on August 3, 2018 10:54_

CUSTOS UniProtKB:Q96C57

![custos](https://user-images.githubusercontent.com/7359272/43639361-ed44d04a-9713-11e8-81f3-e6a165c15b48.jpg)

**Comment by selewis** [comment]
It ought to be there, simply because it's in the human Q4O reference proteome set (HGNC:23471), so it would come in from the PANTHER families as well.

**Comment by pgaudet** [comment]
What I noticed (for a long time) in AmiGO is that if you enter a gene ID and click enter immediately it doesn't find it. 
However if you enter a space and let it autofill then it works. I can find Q96C57 doing that:

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/4782928/43667283-982ca9d4-9777-11e8-8a06-af1c889add82.png">


HOWEVER it has 2 annotations, while QuickGO has 5 (note that QuickGO is missing the IBA, but that's a separate issue). **I thought we had all human IEAs in AmiGO; don't we ?** 
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/4782928/43667345-d051d974-9777-11e8-9ca5-70bcbfc90593.png">



Pascale

**Comment by kltm** [comment]
Given that AmiGO is a fairly transparent layer over the data, where do we want to dig to see why this wanted data is not appearing?

**Comment by cmungall** [comment]
The reason you don't see them is that these were made two weeks ago. Changes in upstream providers are not reflected immediately in AmiGO. You will see these in the GO Central August release on Monday.

We can check this. July release files:

```
$ curl -L -s http://release.geneontology.org/2018-07-02/annotations/goa_human.gaf.gz | gzip -dc | egrep '^UniProtKB\tQ96C57'
UniProtKB       Q96C57  C12orf43                GO:0005515      PMID:21044950   IPI     UniProtKB:P54274        F       Uncharacterized protein C12orf43        C12orf43|C12orf43       protein    taxon:9606      20180618        IntAct  
UniProtKB       Q96C57  C12orf43                GO:0005515      PMID:21873635   IBA     PANTHER:PTN001025407|UniProtKB:Q96C57   F       Uncharacterized protein C12orf43        C12orf43|C12orf43  protein NCBITaxon:      20180510        GO_Central 
```

snapshot preview, note the dates:

```
$ curl -L -s http://snapshot.geneontology.org/annotations/goa_human.gaf.gz | gzip -dc | egrep '^UniProtKB\tQ96C57'
UniProtKB       Q96C57  CUSTOS          GO:0005515      PMID:21044950   IPI     UniProtKB:P54274        F       Protein CUSTOS  CUSTOS|C12orf43 protein taxon:9606      20180716        IntAct     
UniProtKB       Q96C57  CUSTOS          GO:0005635      GO_REF:0000039  IEA     UniProtKB-SubCell:SL-0178       C       Protein CUSTOS  CUSTOS|C12orf43 protein taxon:9606      20180714  UniProt  
UniProtKB       Q96C57  CUSTOS          GO:0007275      GO_REF:0000037  IEA     UniProtKB-KW:KW-0217    P       Protein CUSTOS  CUSTOS|C12orf43 protein taxon:9606      20180714        UniProt    
UniProtKB       Q96C57  CUSTOS          GO:0016055      GO_REF:0000037  IEA     UniProtKB-KW:KW-0879    P       Protein CUSTOS  CUSTOS|C12orf43 protein taxon:9606      20180714        UniProt    
UniProtKB       Q96C57  CUSTOS          GO:0005515      PMID:21873635   IBA     PANTHER:PTN001025407|UniProtKB:Q96C57   F       Protein CUSTOS  CUSTOS|C12orf43 protein taxon:9606      20180510   GO_Central      
```

It looks like QuickGO doesn't show the creation date, but you can see this if you download the GPAD:

![image](https://user-images.githubusercontent.com/50745/43670314-3abe3638-973f-11e8-9296-458ea8831cae.png)

**Comment by cmungall** [comment]
No longer relevant, but FWIW:

@selewis 
> It ought to be there, simply because it's in the human Q4O reference proteome set (HGNC:23471), so it would come in from the PANTHER families as well.

That's a different gene:
https://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=23471

this is CUSTOS:

https://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=HGNC:25719

**Comment by selewis** [comment]
Ah, well that info should go back to UniProt because (if I scanned
correctly) they have Q6P6B7 mapped to HGNC:23471

https://www.uniprot.org/uniprot/Q6P6B7

**Comment by ValWood** [comment]
OK Q96C57 is present (albeit  without the new annotation, which will appear shortly), so that one if fine. I fell foul of the  funny behaviuor when you hit return.

However note that  I still don't find an entry for Q6P6B7 or Q5VXU9 even when I do hit return.

All of the comments  refer to CUSTOS which is a non-issue.

**Comment by ValWood** [comment]
I'm unable to reopen.....

**Comment by pgaudet** [comment]
Q6P6B7 doesn't have annotations, it seems OK that it's not found in AmiGO, isn't it ?

**Comment by ValWood** [comment]
Yes agreed. It has no annotation yet.

**Comment by ValWood** [comment]
@Antonialock  ANKRD16 isn't annotated  yet  with GO terms so it won't be in AmiGO. You can include this in your "annotatable" list

It seems to be a
GO:0002161
Name aminoacyl-tRNA editing activity
Ontology molecular_function
Synonyms amino acid proofreading activity, aminoacyl-tRNA hydrolysis activity
None
Definition
The hydrolysis of an incorrectly aminoacylated tRNA. Source: PMID:16087889, GOC:hjd, PMID:14663147

and 

GO:1990145    Jmaintenance of translational fidelity
Suppression of the occurrence of translational errors, such as codon-anticodon mis-paring,

**Comment by Antonialock** [comment]
yes I had aminoacyl-tRNA metabolism involved in translational fidelity
can add activity too cheers
