### ISSUE TITLE
Duplicate 'with' from PAINT annotations

### ISSUE THREAD

**Issue by pgaudet** [geneontology/amigo#539]
Hi @kltm 
Any idea where these duplicate 'with' are coming from ? see P9WQJ9
<img width="928" alt="image" src="https://user-images.githubusercontent.com/4782928/45960592-d6ca4e80-c01c-11e8-92d0-1d08a64a8730.png">

Thanks, Pascale

**Comment by kltm** [comment]
URL to duplicate:
http://amigo.geneontology.org/amigo/search/annotation?q=irtA*&fq=evidence_subset_closure_label:%22biological%20aspect%20of%20ancestor%20evidence%20used%20in%20manual%20assertion%22&fq=annotation_class_label:%22ferric%20iron%20import%22&sfq=document_category:%22annotation%22

**Comment by kltm** [comment]
I'm not seeing any duplication.

**Comment by pgaudet** [comment]
You dont see twice the ID in the 'with' field ? 

(towards the right)

**Comment by kltm** [comment]
Which ID are you referring to?

**Comment by kltm** [comment]
Are you not talking about *7* and *9* being different?

**Comment by pgaudet** [comment]
Oh ! Yes  - oups! sorry about that.
