### ISSUE TITLE
 Add taxon constraints to display

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#56]
From Chris: See quickgo for examples.

**Comment by cmungall** [comment]
Note: closing this one as a dupe: https://www.ebi.ac.uk/panda/jira/browse/GO-219

**Comment by paolaroncaglia** [comment]
Hi,

Is there any update on this please? I.e. displaying taxon constraints in AmiGO term pages. At present, they seem to be completely invisible. GO survey says ~36% of our users refer to AmiGO, so that's a shame if we can't convey that information to such a large portion of users...

I was looking into this as part of the taxonomy update paper, but it's really a broader issue.

Thanks! 
Paola

**Comment by kltm** [comment]
Assuming the above works (and that's a big "if"), it will initially only be exposed for terms. We'll have to make a slightly more invasive change at the owltools loader level to get it exposed for annotations as well. Next load is likely for the weekend, but I may trigger sooner as I'd probably like to freeze before the meeting.

**Comment by cmungall** [comment]
Happy for this ticket to just be about terms, and to be able to display the taxon constrs on the term info page. Can open a new ticket for adding these into annotation documents but there isn't really a use case as the actual taxon in the association will be more specific than the constraint.

**Comment by kltm** [comment]
We'll be reverting here:
```
Yuuup--that's us. This was actually following up on Paola's request
yesterday. It should have been a gimme, but we had not tested it before
and were waiting for the weekend reload to see (an immediate failure was
a possibility, and we'd just restart after reverting if we had
problems). I then pushed it out of my mind, waiting for the Jenkins
report. Justin--thank you, you got very (un)lucky on this upstream grab.

Practically, this would probably mean then that the expected output for
those functions is not actually what the flexloader wants. I'll revert
here and wait until we have time to dig into owltools. 
```
@elserj

**Comment by kltm** [comment]
@hdietze I believe that the issue here is that getOnlyInTaxonLabels (returning a set) should be getOnlyInTaxonLabel (returning a string). I'd bet that the parser chokes on the fact that a cardinality-of-one function is returning a set instead of a string.

**Comment by kltm** [comment]
@elserj, I believe that this should be sufficient if you want to test, or you can keep what you have.

**Comment by kltm** [comment]
Okay, I've completely backed out for now--this cannot be done without a schema change: the id/label fields can have a cardinality of multi, so we need to add the map to the schema and populate it as well. This will take a little more work, so we're going to kick it for a bit.

We should have reverted everything now to the older "good" state. Older, but wiser.

Actions:

* change schema to make get getOnlyInTaxon and getOnlyInTaxonLabels multi
* add mapping fields, and use new @hdietze function above to populate it
* roll out new schema with changes

@elserj you should monitor this ticket as it will require a schema upgrade at your end as well when we make the jump.

**Comment by paolaroncaglia** [comment]
Hi all and thanks for trying anyway...

Just to have an idea (I don't mean to bug you, but I'd like to quote this plan in a publication on taxonomy representation in GO), what do you think a reasonable timeframe for this task would be, given resources? And would it be ok if I reminded you after the holidays? :-)

Thanks,
Paola

**Comment by kltm** [comment]
After the holidays is fine. It probably would not take that much effort to sit down and coordinate the code and schema upgrade, but there are a lot of low and medium effort tasks floating around that currently have priority. :disappointed: If there is a deadline or other goal to hit, that can help us order what needs to be done.

**Comment by paolaroncaglia** [comment]
Thanks Seth. Let's update after the holidays, and we can set a time plan then.

**Comment by cmungall** [comment]
Note that this ticket may be subsumed in the fix for 
https://github.com/Planteome/planteome-ontology-browsers/issues/20

**Comment by cmungall** [comment]
Discussed on 2023-11-16 call

Now we are including the precomputed TCs in the released ontology (https://github.com/geneontology/go-ontology/issues/19759) we can do this easily with a simple lookup on the json graph.

Note we can also easily add this to closures

https://github.com/geneontology/amigo/blob/c6a484027d1074bb9dc6bdc10ff40aab0ccbf8c4/metadata/ont-config.yaml#L233-L245

Change the dummy method to `getRelationIDClosure(RO:0002162)`

It would be nice to do this before the 10th birthday of this issue :-)

**Comment by kltm** [comment]
Okay, talking to @cmungall , when the next GO release goes live, I'll take a look to see if this data has propagated into the json graph and, if so, do some template render tweaks to expose it in the interface. V/easy. 
If not there for some reason, I'll try and see what changes would be necessary.

**Comment by kltm** [comment]
Alas, due to issues with an API change at Zenodo, we are likely to miss the birthday :(

**Comment by kltm** [comment]
https://github.com/geneontology/pipeline/issues/345

**Comment by kltm** [comment]
A bit of a hash in there, but there is information that can be extracted.
https://golr-staging.geneontology.io/solr/select?defType=edismax&qt=standard&indent=on&wt=json&rows=10&start=0&fl=*,score&facet=true&facet.mincount=1&facet.sort=count&json.nl=arrarr&facet.limit=25&hl=true&hl.simple.pre=%3Cem%20class=%22hilite%22%3E&hl.snippets=1000&fq=document_category:%22ontology_class%22&q=id:%22GO:0000165%22
Probably easiest crutch is to use the `NCBITaxon` namespace.
Noting that we don't have relation labels available there, but
```
sjcarbon@moiraine:~/local/src/git/go-ontology/src/ontology[master]$:) grep -oh -P "RO_[0-9]{7}" imports/go_taxon_constraints.owl | sort | uniq -c
    872 RO_0002160
    590 RO_0002161
   2564 RO_0002162
```
(Also noting that the icons have really rotted away and need fixing. Bleh.)

**Comment by kltm** [comment]
Not exposed a little in https://amigo.geneontology.org/amigo/term/GO:0000165

**Comment by pgaudet** [comment]
Great ! This is super useful. 

However I wonder about the taxonomy page - when I click through 'Eukaryotes,' I get to this page, with 12 annotations - that seems surprising? 

<img width="1240" alt="image" src="https://github.com/geneontology/amigo/assets/4782928/5822d8fe-f619-4950-a2ee-9564dac183ae">

**Comment by kltm** [comment]
@pgaudet Yeah, I don't think that's "technically" wrong, as it's answering the question of "what annotations have the term NCBITaxon:2759 in their is-a/part-of closure". The answer seems to be a complete circle with [CA3 pyramidal cell dendrite](https://amigo.geneontology.org/amigo/term/GO:0097442), so there is probably something to be explored on the ontology side with that (tagging @balhoff), but not necessarily a direct AmiGO question. 
That said, on the AmiGO side, if this is confusing to users, there's no reason not to explore suppressing this (for now anyways) by either linking to the external NCBITaxon page (easy), removing the linkout (easy), or suppressing annotations searches in non-GO terms pages (doable, but spider sense says that that might not be what we want).

**Comment by pgaudet** [comment]
I think it would be much more appropriate to link to NCBI taxonomy. 

> suppressing annotation searches in non-GO terms pages

OK, I see now that following an extension to Uberon leads to the OLS  page (for example, C1 field of hippocampus) here
https://amigo.geneontology.org/amigo/gene_product/UniProtKB:P05067, I didn't know this had been changed, but I propose we link out for external ontologies.

Thanks, Pascale

**Comment by kltm** [comment]
Not sure why our link generation is different here. I'll update.

**Comment by kltm** [comment]
The link is now in line with all other taxon links in AmiGO.
