### ISSUE TITLE
PTHR families showing up strangly in AmiGO 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/amigo#561]
Hello, 

Why does the  PTHR families showing a long path? 

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/4782928/54424823-19d7c580-4714-11e9-8063-89baabef7e97.png">

Thanks, Pascale

**Comment by ValWood** [comment]
That is the family name for this family, it just looks like a path ;)
http://www.pantherdb.org/panther/family.do?clsAccession=PTHR19143

**Comment by pgaudet** [comment]
Ah ! It's the name of the family. This one is odd because it has a bunch of slashes. 

I didn't know we wanted to add that information - I guess that's useful. 

It may be clearer if the case was respected - Panther has everything upper case. 
@thomaspd @huaiyumi What do you recommend ? 

Thanks, Pascale
