### ISSUE TITLE
UniProtKB IDs are showing up as source RNA central

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#567]
RNA central should never be of type protein:

![image](https://user-images.githubusercontent.com/50745/58049763-826f6400-7b02-11e9-817a-e0abc0af4e5f.png)

E.g.

![image](https://user-images.githubusercontent.com/50745/58049750-7388b180-7b02-11e9-9c55-dbbce13846dd.png)

Clicking SALL3 here, we actually have the type correct here:

http://amigo.geneontology.org/amigo/gene_product/UniProtKB:Q9BXA9

**Comment by cmungall** [comment]
I'm perplexed as to how this is happening

the code here looks sound:

https://github.com/owlcollab/owltools/blob/452b4aa12665c79b94629d2e76b6b643a88e4537/OWLTools-Solr/src/main/java/owltools/solrj/GafSolrDocumentLoader.java#L240-L255

**Comment by pgaudet** [comment]
Sometimes AmiGO is a little erratic. I redid what I think you did and it seems OK 

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/4782928/58051112-9db59000-7b51-11e9-9c3a-7936f6563add.png">

**Comment by pgaudet** [comment]
Hum no our queries are not the same.

**Comment by cmungall** [comment]
odd, I can't reproduce...

**Comment by cmungall** [comment]
odd, I can't reproduce...
