### ISSUE TITLE
KEGG links missing

### ISSUE THREAD

**Issue by pgaudet** [geneontology/amigo#568]
At least from GO:0008948

http://amigo.geneontology.org/amigo/term/GO:0008948

There is no link to the KEGG reaction. 

Should be https://www.genome.jp/dbget-bin/www_bget?rn:R00217

Thanks, Pascale

**Comment by kltm** [comment]
This is an upstream issue with db-xrefs.yaml in go-site/: there is no linkable KEGG information for AmiGO to use.

**Comment by ValWood** [comment]
this is where we got to when we looked into this
https://github.com/pombase/website/issues/763

so there is a file MF-> KEGG
http://current.geneontology.org/ontology/external2go/kegg2go

**Comment by pgaudet** [comment]
@kltm 

Who added this ? 

- database: KEGG_REACTION
  name: KEGG Reaction Database
  generic_urls:
    - http://www.genome.jp/kegg/reaction/
  entity_types:
    - type_name: entity
      type_id: BET:0000000
      id_syntax: R\d+
      url_syntax: http://www.genome.jp/dbget-bin/www_bget?rn:[example_id]
      example_id: KEGG:R02328
      example_url: http://www.genome.jp/dbget-bin/www_bget?rn:R02328


Isn't this what you need ? 

Thanks, Pascale

**Comment by kltm** [comment]
@pgaudet No, this is the wrong namespace--we need something for `KEGG`.

**Comment by pgaudet** [comment]
I figure it out - this is an ontology problem, the prefix was wrong. I opened a new ticket. https://github.com/geneontology/go-ontology/issues/17506

**Comment by pgaudet** [comment]
Links now working !
