### ISSUE TITLE
Direct annotations filter does not appear to be working

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#580]
Here I  am looking at annotations to GO:0051809

and I wanted to filter direct annotations.
Amigo says there aren't any, but I can see them (antigenic variation?)

This used to work, did something change?

![amigo bug](https://user-images.githubusercontent.com/7359272/65621601-f98a9c80-dfbb-11e9-85d8-1ad06cbf91fd.jpg)

**Comment by pgaudet** [comment]
For me the behavior is a little erratic. Usually I start from scratch or
change the order in which I apply filters and it works.

Pascale

Le mer. 25 sept. 2019 à 12:44 PM, Val Wood <notifications@github.com> a
écrit :

**Comment by kltm** [comment]
Location: http://amigo.geneontology.org/amigo/term/GO:0051809#display-associations-tab

Poking around, it would seem that there may be no direct annotations to GO:0051809 (passive evasion of immune response of other organism involved in symbiotic interaction), only to the children; we should probably double check that first.

**Comment by pgaudet** [comment]
Good point @kltm There are no direct annotations. 

Pascale
