### ISSUE TITLE
Update Copyright 1999-2018 in AmiGO

### ISSUE THREAD

**Issue by pgaudet** [geneontology/amigo#586]
Need to update the date to 2020 @kltm 

Thanks, Pascale

**Comment by kltm** [comment]
@pgaudet Make a separate ticket for that on the website tracker and edit it out here.

**Comment by kltm** [comment]
Edited.

**Comment by lpalbou** [comment]
Should be good: https://github.com/geneontology/amigo/pull/587

**Comment by lpalbou** [comment]
Also updated the date for gocam site: https://github.com/geneontology/web-gocam/commit/65523a10fcdd23f9b53065e7e575c2a2e6f80ac3
