### ISSUE TITLE
Amigo broken?

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#589]
Amigo appears to be broken again.

I can't search on genes right now.

getting a 404 error for link outs from PomBase
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPBPB2B2.09c
AmiGO 2 was unable to find the gene product PomBase:SPBPB2B2.09c through normal channels--it may not be in our data set or it may go under a different identifier. Please try your gene product (PomBase:SPBPB2B2.09c) through the landing page general search interface using synonyms or alternate identifiers.

If you feel that you have reached this message in error, please contact GO Helpdesk.

and  an nothing found  if i try to search for "PAN5" from the AmiGO front page

**Comment by ValWood** [comment]
...and it's back. I had the same issue last week?

**Comment by pgaudet** [comment]
There are regular hiccups. 
@kltm Do you know what could be done about this ?

**Comment by kltm** [comment]
Our external monitors (https://status.geneontology.org/) are not reporting any issues here, short an apparent hiccup on the 19th.
