### ISSUE TITLE
Can no longer search with UniPRot accession numbers

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#590]
Until recently, I could search amigo with Uniprot accession numbers.

e.g. O94244 for  S. pombe MIs16 , and this Acc appeared in teh gene product information.
This was quite useful. Any particular reason why it went away?

**Comment by pgaudet** [comment]
I thought you could only search the ID space for a given source - ie pombe would be pombase IDs, human -> Uniprot IDs, etc. 

@kltm Is this right ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I think I imagined it. Closing!
