### ISSUE TITLE
Matrix tool results not avaiable

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#591]
The search runs but when I try to access the results  I get

No results found.
No results given your input and search fields. Please refine and try again.

for everything

**Comment by ValWood** [comment]
TypeError: Cannot read property 'response' of undefined
with
GO:0006351 
GO:0006390 
GO:0005736 
GO:0005665 
GO:0005666 
GO:0030014
GO:0000347 
GO:0001181 
GO:0016251 
GO:0000995  
GO:0001181 
GO:0003711 
GO:0003700 
GO:0003714 
GO:0003713 
GO:0006353 
GO:0031048 
GO:0006334 
GO:0070603
GO:0016514
GO:0016586 
GO:0031011 
GO:0000812 
GO:0016593 
GO:0033193 
GO:0000123 
GO:0035097  
GO:0000118 
GO:0004402 
GO:0004407 
GO:0035064 
GO:0032452 
GO:0042054 
GO:0019787 
GO:0034396
GO:0023052

**Comment by ValWood** [comment]
It just bails out. Yesterday it was running but I could nit access results

**Comment by kltm** [comment]
@ValWood As of this moment, the above set works for me, the 600 odd queries finishing in about tens seconds. Are there any filters or flags that you're using?

**Comment by ValWood** [comment]
I forgot to report back, this issue went away ?
