### ISSUE TITLE
Protein Ontology links are not resolving

### ISSUE THREAD

**Issue by ukemi** [geneontology/amigo#594]
I just noticed that PR: identifier links are not resolving in Amigo. It looks like they need the PR: to get to the right place.
See the annotations for mouse Slc12a1 for examples.

**Comment by kltm** [comment]
Looking at http://amigo.geneontology.org/amigo/gene_product/MGI:MGI:103150 

For annotation line
Slc12a1 | solute carrier family 12, member 1 |   | protein binding |   | MGI | Mus musculus | IPI 

PR:000044370
PR:G1JLS7
PR:Q9Z1W9-1

resolve with https://proconsortium.org/app/entry/

giving us:

https://proconsortium.org/app/entry/000044370
https://proconsortium.org/app/entry/G1JLS7
https://proconsortium.org/app/entry/Q9Z1W9-1

Which is correct given the mapping found: https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml#L1978

**Comment by kltm** [comment]
This was changed by @pgaudet on https://github.com/geneontology/go-site/commit/199dd0277b6e4c2dbebc360cd6851ebbbb943e1a .

**Comment by kltm** [comment]
Now seems to have proper mapping:

https://proconsortium.org/app/entry/PR_000044370/
https://proconsortium.org/app/entry/PR_G1JLS7/
https://proconsortium.org/app/entry/PR_Q9Z1W9-1/
