### ISSUE TITLE
AmiGO stats page has no data

### ISSUE THREAD

**Issue by hattrill** [geneontology/amigo#598]
AmiGO stats page http://amigo.geneontology.org/amigo/base_statistics
not displaying stats correctly/at all

![newplot](https://user-images.githubusercontent.com/11865746/82411195-359dd080-9a69-11ea-8582-a8e2a2279df0.png)

Firefox & Safari browsers tested.

**Comment by lpalbou** [comment]
Probably those amigo stats should be deprecated in favor of the go stats page ?

**Comment by pgaudet** [comment]
can we redirect the page ?

**Comment by kltm** [comment]
First I'd like to figure out the data error.
After that, we can look at deprecating and/or forwarding.

A note to @hattrill that there is an other (GO, non-AmiGO) stats page available at http://geneontology.org/stats

**Comment by kltm** [comment]
@hattrill For whatever reason, the stats refresh did not seem to trigger on the last update. This should now be giving numbers.

**Comment by hattrill** [comment]
Thanks @kltm! All is well.

**Comment by pgaudet** [comment]
@kltm The numbers are different for the two stats pages - for eg human has 226 k EXP in the AmiGO page and 216 k on the geneontology.org page. 

Can you make a redirect to the geneontology.org page ? 

Thanks, Pascale
