### ISSUE TITLE
Some relations are only shown by their IDs

### ISSUE THREAD

**Issue by pgaudet** [geneontology/amigo#600]
Hello, 

Is it possible to add the relation labels here: 

![image](https://user-images.githubusercontent.com/4782928/84634752-91396d80-aef2-11ea-9cb9-45e332d31059.png)

Thanks, Pascale

**Comment by pgaudet** [comment]
RO:0002211 = regulates

**Comment by kltm** [comment]
I believe this is a dupe of https://github.com/geneontology/amigo/issues/545
