### ISSUE TITLE
Filters are not applied to searches even if they appear in the URL

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#609]
When I try to get to a gene product list for a term

from
http://amigo.geneontology.org/amigo/term/GO:0005635

Related
 "to all genes and gene products annotated to nuclear envelope"

I get ALL annotations???
.

**Comment by kltm** [comment]
Looking into this. Seems to be a recent change, which means it might be an effect of the recent XSS security issues.

**Comment by kltm** [comment]
Testing should be easy:

A filter should show up for:

- [ ] http://amigo.geneontology.org/amigo/search/bioentity?q=*:*&fq=regulates_closure:%22GO:0005635%22&sfq=document_category:%22bioentity%22

It should be resistant to these regressions:
- [ ] https://github.com/geneontology/amigo/issues/575
- [ ] https://github.com/geneontology/amigo/issues/576
- [ ] https://github.com/geneontology/amigo/issues/606
- [ ] https://github.com/geneontology/amigo/issues/608

**Comment by kltm** [comment]
live search filters and live search pins do not seem to be coming through as javascript variables--it seems likely this is an issue more on the server side of things.

**Comment by kltm** [comment]
Localized issue, fix in progress.

**Comment by kltm** [comment]
@ValWood I think that the last patch might take care of that? Let me know if it works for you. (And thank you for reporting.)
