### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by nathanweeks** [geneontology/amigo#610]
It would be convenient if this repo included a Dockerfile that formalized the software environment and build procedure for AmiGO, as well as a docker-compose.yml that on "docker-compose up" does something like start web server + Apache Solr services, bind mount a directory on the host containing configuration & obo files, and execute the "gulp" commands to do a load from an entrypoint script.

**Comment by lpalbou** [comment]
There is a docker image for a standalone amigo/golr instance.

Since you also use AWS, I also have an AMI preconfigured, where you can launch any of the DOI release with just something like `launch <doi>`. If you are interested, send me your amazon id and I can share the image with you.

**Comment by nathanweeks** [comment]
> There is a docker image for a standalone amigo/golr instance.

Great! Where could I find the Dockerfile & image repository?

**Comment by kltm** [comment]
@nathanweeks 

We'll get more exposure for what we're doing soon (as well as sorting things into the right repo), but for the moment we have the best I can probably offer is:

```
mkdir -p /tmp/srv-solr-data/index
cd /tmp/srv-solr-data/index
wget http://current.geneontology.org/products/solr/golr-index-contents.tgz
tar -zxvf golr-index-contents.tgz
docker run -p 8080:8080 -p 9999:9999 -v /tmp/srv-solr-data:/srv/solr/data -t geneontology/amigo-standalone
```

For the Dockerfile, I've pulled this out: https://github.com/kltm/go-sid-operations/tree/main/docker/amigo-standalone , which should help get you started.

We have docker-compose for AmiGO already mostly developed (for a slightly different use case), so we'll be publicizing that more in the very near future.

**Comment by kltm** [comment]
Cheers to @lpalbou for following up.

**Comment by nathanweeks** [comment]
Thanks @kltm , that looks promising. Docker Compose would be preferable; I'll be interested to see it when available.
