### ISSUE TITLE
Change default closure to isa_partof from regulates

### ISSUE THREAD

**Issue by cmungall** [geneontology/amigo#620]
Ideally this would be one parameter but I think there are about 6 or 7 places in the .js to change:
https://github.com/geneontology/amigo/search?q=regulates_closure

This would make AmiGO consistent with Panther.

Estimated time: small

Note: I think we still need to do some investigation as to the implications of including/excluding BP-regulates-BP, but the immediate priority is consistency

**Comment by kltm** [comment]
Probably not? IIRC, it's certainly been changed before without too much mechanical fuss.
There are few things that I think would be good to consider/get ready for:

1) track down the persons/reason for the initial change to regulates--I think that was probably done some time ago and outside the tracker. Related tickets may be: https://github.com/geneontology/amigo/issues/210, https://github.com/geneontology/amigo/issues/602
2) What else might we want to change; e.g. what does the ribbon do?
2) how to communicate this change

**Comment by kltm** [comment]
Poking around in the code a little just to get an idea, it would seem that it is mostly wired on the surface on a client-by-client basis. That means there would be a bunch of changes, but I suspect mostly replacement. A little more work would need to be done to get it "centralized" in the config. A little more irritating, there are also fields in GOlr, like `regulates_transitivity_graph_json`, which seem to have been created after the switch from isa_part_of in the first place that have no isa_part_of analog. The schema would have to be extended and those would need to be added to the loader. These seem to be a bit more embedded where they're used in clients and might require a little fiddling to clean up.

**Comment by cmungall** [comment]
1. it started out this way, going back to when all the regulates relations were part-ofs. And yes this solves those two issues (those issues are about blocking propagation solely in MF)
2. good q. ribbon uses http://api.geneontology.org/api

![image](https://user-images.githubusercontent.com/50745/133540331-d50bda6c-4a2e-4613-bcba-ac0655697211.png)

so the default gp2term relationship is involved-in, i.e. use the isa-partof-closure

3. good point. Shall we make the PR and then bring this up next managers call?

**Comment by pgaudet** [comment]
Can this be configurable by the user with some checkbox? Depending on what you are looking at, it may be interesting to get a wider or narrow range of terms.

**Comment by pgaudet** [comment]
Added to next week's managers call.

**Comment by cmungall** [comment]
We have other tickets for making it easy to switch between the views (will link later, sorry). I suggest scoping this ticket to *just* changing the default behavior.

**Comment by kltm** [comment]
While there will be a bunch of changes to AmiGO code, that's mostly "surface" (if possibly fiddly). Most of the work and time on this will actually be pipeline and deployment, so I'd be fine treating it as a pipeline maintenance/bugfix (for data), rather than an AmiGO issue per se.

**Comment by ukemi** [comment]
We should also keep in mind that the GPAD files generated from Noctua models will create an 'acts_upstream_of' X annotation for any annotation to a regulation of X term. Although closure is a good thing to address, the issue is more complex (isn't it always?).

**Comment by kltm** [comment]
Setup work spaces:
https://github.com/geneontology/amigo/tree/issue-620-change-default-closure
https://github.com/geneontology/pipeline/tree/issue-amigo-620-change-default-closure
https://build.geneontology.org/job/geneontology/job/pipeline/job/issue-amigo-620-change-default-closure/

**Comment by kltm** [comment]
Should now have GOlr Solr index building image with geneontology/golr-autoindex:f815e3e9004f96493f29a80a73526c91c2a4c25d_2021-10-01T162208_issue-620-change-default-closure
Will test after release.

**Comment by kltm** [comment]
@cmungall Noting here that "generate_val_statistics.js" uses `regulates_closure_label`. Leaving this as is for now.

**Comment by kltm** [comment]
After discussion with @cmungall , we'll keep the topology load as-is for the moment. Now rebuilding with full load for more testing.

**Comment by kltm** [comment]
@cmungall Full load (delta recent IEA issues) now available on amigo-exp.

**Comment by kltm** [comment]
Notes from conversation with Chris:
1) limit state toggle to the term page (only);<br /> may be possible to implement by gaming the bookmarks
2) add filters to annotation search

**Comment by cmungall** [comment]
https://docs.google.com/presentation/d/15NOq1x27t43K6TDMoPnnVQzWFbcgRfix96ng4j8YNNs/edit#slide=id.g107a668700d_0_8

**Comment by kltm** [comment]
This (contents and UI) has passed review and can start filtering to production.

**Comment by cmungall** [comment]
It would be good to document what we have done here

These slides. are from before the last GO meeting:
https://docs.google.com/presentation/d/19UoPyCUBIOW5hrLG27ARJMNsjyOJ_c0Qv-Iz2x-CS14/edit#slide=id.p

these could be cloned and updated with new figures

**Comment by kltm** [comment]
When complete, reminder for @kltm to update link in doc: https://docs.google.com/document/d/1906vUn0DD160zofo_CLT414_X2uqh0aoA7XmHKyIaR8/edit#heading=h.jglmdvcq6xxp
Noting this it is unlikely to be this release cycle (a lot of ongoing problems), so probably the next. Otherwise, the experimental link can be more-or-less stably used as this is will be the new standard.

**Comment by kltm** [comment]
Remaining TODO:
- [ ] get new docker image from `master` branch put out
- [ ] put this docker image into main series (master/snapshot/release)
- [ ] run to success
- [ ] get new indexes onto machines with correct fields
- [ ] update software to take advantage (production will need to be timed more tightly)
  - [ ] amigo-exp
  - [ ] amigo-staging
  - [ ] amigo (prod)

**Comment by kltm** [comment]
In production. Anything further is a bug.
