### ISSUE TITLE
Refresh interface for term pages to allow switching relation closures

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#634]
This is for /only/ the term pages. See initial description for refresh:

https://docs.google.com/presentation/d/15NOq1x27t43K6TDMoPnnVQzWFbcgRfix96ng4j8YNNs/edit#slide=id.p

Also, from that conversation, clarifications:

1) limit state toggle to the term page (only);<br /> may be possible to implement by gaming the bookmarks<br /> fine to change the URL parameter to do this to something more general
2) add filters to annotation search

For #620 ; do work on https://github.com/geneontology/amigo/tree/issue-620-change-default-closure

**Comment by kltm** [comment]
A little more digging into the code here: the bookmark mechanism, while functional on this page, does not actually have any hooks available from the interface. As well, the bookmarks assume pretty deeply that there is *some* kind of default relation at play, so I'm a little leery of trying to use it to modify said relation.

I think the easiest would be to lean into the default relation, basically making the current `default_closure_relation_set` variable optionally set from the outside world with a global.

**Comment by kltm** [comment]
A possible working toggle mechanism is now in place. Still need to:
- [ ] test with the correct index (all links, dowmloads, etc.
- [ ] add additional text, as in slides three and four
- [ ] split closure filter, as in slide 6

**Comment by kltm** [comment]
Using the ontology relation documentation for linking for the moment: http://geneontology.org/docs/ontology-relations/

**Comment by kltm** [comment]
Looking at slide "6", making consistent with other views by using "class" (instead of "term") and assuming the second "including" is a typo and should be "excluding".

**Comment by cmungall** [comment]
We need to rewrite that documentation to make it more useful to users, but that can be considered a separate piece of work from this ticket

**Comment by cmungall** [comment]
> assuming the second "including" is a typo and should be "excluding".

Fixed it!

**Comment by kltm** [comment]
Okay, I believe most of the mechanical bits are in place as defined. Now what is needed is to make sure the right index is on the test server and then work through some testing.

**Comment by kltm** [comment]
I think the index is the correct one for testing now. Starting to poke around a little.

**Comment by kltm** [comment]
Okay, as a test, I'll go back through some of Val's tickets (and dupe them to here if fixed).

**Comment by kltm** [comment]
Check:
- [ ] two closures
- [ ] toggle
- [ ] links
- [ ] downloads
- [ ] filters

(Now that there are two closures, I think there might be some fun tricks that could be done, like finding terms that are in one closure but not another.)

**Comment by kltm** [comment]
@cmungall Okay, I've done some quick testing and I believe that this is ready for you to take a look at. I believe that your spec is now mostly fulfilled. For (a not very good example) see: http://amigo-exp.geneontology.io/amigo/term/GO:0031204

**Comment by kltm** [comment]
@cmungall This has passed a review.
