### ISSUE TITLE
AmiGO browse not showing number of annotations anymore

### ISSUE THREAD

**Issue by pgaudet** [geneontology/amigo#639]
Hi, 

The AmiGO 'Browse' function is not showing the number of annotations since the last release yesterday (see screenshot)

Could this be some confusion in the count because if the change in the regulates closure? Or just a coincidence? 

<img width="592" alt="image" src="https://user-images.githubusercontent.com/4782928/161232070-5fb2775c-0043-4f0c-ac8e-d991fceff5b5.png">

Thanks, Pascale

**Comment by kltm** [comment]
Huh. Yes, after a little poking around this does appear to have been related to the code changes around the switchover (not the data itself). I'll check into this more, but I believe I essentially accidentally made it so the count accumulator could not operate. I seem to have gotten a little copy-pastey and not checked the entire context of what was going on in this case.
https://github.com/geneontology/amigo/commit/a5f4edff83a5c900f8a067a87579cd51d43f45c7#diff-03d9c9a6dc0a12bf0052258c8a0034283f6a2449f4af4cbb27b6992837dec965L226

**Comment by kltm** [comment]
Right. I think I have a fix in.

**Comment by kltm** [comment]
Briefly reopened default relation project to add in.

**Comment by kltm** [comment]
Seems fixed; closing (closed project anyways so will not get further attention).
