### ISSUE TITLE
confusing search results

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#649]
I know I have mentioned this before, but it is very confusing  as a user to search on a term for "glucose coupled receptor" and land on this page.

http://amigo.geneontology.org/amigo/term/PR:000030035

You would think there was no such term in GO

**Comment by kltm** [comment]
@ValWood Could you give me a little more information on how you got there? Playing around a little myself, when I search in the general search for `glucose coupled receptor` that is not one of the results that I get (http://amigo.geneontology.org/amigo/search/ontology?q=glucose%20coupled%20receptor).

**Comment by ValWood** [comment]
probably I searched on
"G-protein coupled receptor" but  if I would a. novice I would wonder why there were no annotation. once I arrived here.
I thought that we previously had a discussion about the usefulness of a landing onto GO related data/pages. especially as the term names are often quite similar.

@pgaudet @cmungall

**Comment by pgaudet** [comment]
IMO there should only be AmiGO pages for GO terms, non-GO terms should only be visible in extensions.

**Comment by ValWood** [comment]
I wan't to do a big list of thumbs up. 

The way it works at the moment it doesn't seem to find annotations associated with extensions anyway?
For instance 
GO:0000080 (A GO term  reserved for annotation extensions). The list retrieved, as far as I can tell, has nothing to do with this term, and does not include genes annotated with this term as an extension.

Some terms used in extensions are not searchable
SO:0001843 

but many terms NOT used in  any extensions are searchable.

It's all very unintuitive for users.

**Comment by cmungall** [comment]
duplicate with duplicate with https://github.com/geneontology/amigo/issues/559
