### ISSUE TITLE
Amigo often supplies non-GO terms (confusing for users)

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#667]
Often when searhcing Amigo I get non GO terms (which obviusly are not annotated).

I'm not sure why AmiGO need to display these terms, but it is very confusing for users

Here is an example, but this happens to me all the time.
<img width="820" alt="Screenshot 2023-01-22 at 10 28 26" src="https://user-images.githubusercontent.com/7359272/214124367-2f89a274-a748-4e9d-861a-b1d1865f6f22.png">

**Comment by kltm** [comment]
Cross-referencing with
https://github.com/geneontology/amigo/issues/649
https://github.com/geneontology/amigo/issues/559
