### ISSUE TITLE
Refresh the build system in AmiGO to better support modern JS/widgetry

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#676]
Following on from https://github.com/geneontology/amigo/issues/650, we want to make sure that AmiGO is able to continue to be developed and support the addition of more modern JS and widgets, short of a complete rewrite and hopefully supprting the current (eco)system.

Tagging @vanaukenk and @ukemi

**Comment by pkalita-lbl** [comment]
My plan is:

- [ ] Migrate from gulp 3 to 4.
- [ ] Ensure we're not using any outdated/abandoned/blacklisted gulp plugins. Replace as needed.
- [ ] Introduce Babel transformation into the JS compile step. This could be hooked into the existing Browserify step, but it's also worth investigating if Babel can wholesale replace Browserify.

**Comment by kltm** [comment]
@pkalita-lbl Noting that Browserify was a solution to a particular problem at a particular point in time. If modules needed to be shaved or fixed to support something more mainstream/better, we could also look into that. Let me know if you need any eyes in that direction.
