### ISSUE TITLE
Add "model" tab to gene product pages

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#677]
Following very closely to what appears in the Alliance pages, the pathway widget would be added as a tab (following the pattern of tabs in AmiGO's term pages).

If no data is available, behavior TBD, but would suggest following the Alliance "no data found" message, with a link to GO-CAM information.

Tagging @vanaukenk and @ukemi

**Comment by kltm** [comment]
Feedback from @vanaukenk and @ukemi from here: https://github.com/geneontology/project-management/issues/66#issuecomment-1518130002

**Comment by kltm** [comment]
@pkalita-lbl From a discussion earlier today, if it's not more overhead or work on your end, there is some interest in getting the pathways widget portion of the project out before the other GO-CAM/models parts if those might take a while. Are there any thoughts on that from your end?

**Comment by pkalita-lbl** [comment]
Sorry for not replying sooner. I don't think the dedicated model page will take a lot of effort. It's mainly a question of when exactly I'm able to carve out time to do it. But it should be a matter of weeks, not months, before I can get it done. That being said I don't think I have a strong opinion on whether to release it piecemeal or not.

**Comment by kltm** [comment]
@pkalita-lbl In that case, let's maybe touch bases next week on how to get the widget portion (or any "safe" subset) into `master` and I can put that out.
