### ISSUE TITLE
Add data download to matrix tool

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#684]
As a suggestion from @ValWood, we'd like to make the raw data for the matrix available so that people can process / cluster it in other tools.

@pgaudet This was trivial and done on a coffee break.

**Comment by kltm** [comment]
Tested by @ValWood on amigo-staging.geneontology.io

**Comment by kltm** [comment]
Now in `master`. Can go out at next code cycle.

**Comment by pgaudet** [comment]
Awesome!!

**Comment by kltm** [comment]
Getting this out to prod held up by https://github.com/geneontology/amigo/issues/686

**Comment by kltm** [comment]
@ValWood Now available (again) in production.
