### ISSUE TITLE
Need redirects from old http to new https pages

### ISSUE THREAD

**Issue by pgaudet** [geneontology/amigo#689]
Hello, 

@sjm41 from Flybase reported that their links to AmiGO are now broken; ie the go to the old http site. 
Can we add a redirect to the https pages?

**Comment by kltm** [comment]
I think we may need a bit more detail for what the reported issue is here. I _believe_ that automatic upgrading should already be in place. At least it has worked for me for my tests.

**Comment by sjm41** [comment]
Hi @kltm

Sorry, might have been as false alarm.

I just did a simple test of clicking on an Amigo link on a FlyBase page (http://flybase.org/cgi-bin/cvreport.pl?id=GO%3A0003682) and I was initially directed here:
http://amigo.geneontology.org/amigo/term/GO:0003682

But I just retested and got directed to the https page!  So maybe just some kind of caching issue after all.

**Comment by sjm41** [comment]
That's ironic....
I'll pass this on to our web developers. Thanks!

**Comment by kltm** [comment]
While we're still tweaking our HTTPS settings here, I believe this is closed at our end?
