### ISSUE TITLE
Add update pathway widget to AmiGO (prod)

### ISSUE THREAD

**Issue by kltm** [geneontology/amigo#694]
As a final step for the merge pathway widget project, we want AmiGO to be using the final version.

**Comment by kltm** [comment]
@pkalita-lbl Would you mind confirming this looks correct to you? https://amigo.geneontology.org/amigo/gene_product/MGI:MGI:97591

**Comment by pkalita-lbl** [comment]
Looks good to me.

**Comment by kltm** [comment]
Thank you for the eyes!
