### ISSUE TITLE
BUG when including "regulates"

### ISSUE THREAD

**Issue by ValWood** [geneontology/amigo#702]
In the AmiGO filtering, 
one option is GO class direct, this works as I expect and gives me all of the terms which are directly annotated (i.e. descendants).

I expected "GO class including regulates" to do exactly the same but include the regulates descendants.
It doesn't do this, it gives me all of the annotated ancestors?

There does not seem to be a way to access the decedent annotations and regulation annotations?

Here is an example:

<img width="286" alt="Screenshot 2023-10-31 at 17 31 53" src="https://github.com/geneontology/amigo/assets/7359272/38028e04-e79e-4054-93ff-48fc7a84715c">

my search term is 
meiotic sister chromatid cohesion, centromeric

**Comment by kltm** [comment]
* go to https://amigo.geneontology.org/amigo/search/annotation; after some playing:
  * direct: https://amigo.geneontology.org/amigo/search/annotation?q=*:*&fq=annotation_class_label:%22meiotic%20sister%20chromatid%20cohesion,%20centromeric%22&sfq=document_category:%22annotation%22 => 296
  * regulates: https://amigo.geneontology.org/amigo/search/annotation?q=*:*&fq=regulates_closure_label:%22meiotic%20sister%20chromatid%20cohesion,%20centromeric%22&sfq=document_category:%22annotation%22 => 343
  * isa_partof: https://amigo.geneontology.org/amigo/search/annotation?q=*:*&fq=isa_partof_closure_label:%22maintenance%20of%20meiotic%20sister%20chromatid%20cohesion,%20centromeric%22&sfq=document_category:%22annotation%22 => 47

Repeating, while trying to remove any textual ambiguity:

* direct: https://amigo.geneontology.org/amigo/search/annotation?q=*:*&fq=annotation_class:%22GO:0051754%22&sfq=document_category:%22annotation%22 => 296
* regulates: https://amigo.geneontology.org/amigo/search/annotation?q=*:*&fq=regulates_closure:%22GO:0051754%22&sfq=document_category:%22annotation%22 => 343
* isa_partof: https://amigo.geneontology.org/amigo/search/annotation?q=*:*&fq=isa_partof_closure:%22GO:0051754%22&sfq=document_category:%22annotation%22 => 343

I'm assuming those are the "correct" answers.

The issue then is the different counts of the isa_partof_label link; i.e. that https://amigo.geneontology.org/amigo/search/annotation?q=*:*&fq=isa_partof_closure_label:%22maintenance%20of%20meiotic%20sister%20chromatid%20cohesion,%20centromeric%22&sfq=document_category:%22annotation%22 gives a large undercount (47 vs 343)?

**Comment by ValWood** [comment]
Yes, I aways forget that "[GO class (including "regulates)" has a different meaning, and that I need to use GO class direct but ensure I am using regulates closure.
