### ISSUE TITLE
Definitions of molecular_function and cellular_component do not match in AmiGO and QuickGO

### ISSUE THREAD

**Issue by addiehl** [geneontology/amigo#705]
Related to #704 

[AmiGO CC](https://amigo.geneontology.org/amigo/term/GO:0005575)
A location, relative to cellular compartments and structures, occupied by a macromolecular machine when it carries out a molecular function. There are two ways in which the gene ontology describes locations of gene products: (1) relative to cellular structures (e.g., cytoplasmic side of plasma membrane) or compartments (e.g., mitochondrion), and (2) the stable macromolecular complexes of which they are parts (e.g., the ribosome).

[QuickGO CC](https://www.ebi.ac.uk/QuickGO/term/GO:0005575)
A location, relative to cellular compartments and structures, occupied by a macromolecular machine. There are three types of cellular components described in the gene ontology: (1) the cellular anatomical entity where a gene product carries out a molecular function (e.g., plasma membrane, cytoskeleton) or membrane-enclosed compartments (e.g., mitochondrion); (2) virion components, where viral proteins act, and (3) the stable macromolecular complexes of which gene product are parts (e.g., the clathrin complex).

[AmiGO MF](https://amigo.geneontology.org/amigo/term/GO:0003674)
A molecular process that can be carried out by the action of a single macromolecular machine, usually via direct physical interactions with other molecular entities. Function in this sense denotes an action, or activity, that a gene product (or a complex) performs. These actions are described from two distinct but related perspectives: (1) biochemical activity, and (2) role as a component in a larger system/process.

[QuickGO MF](https://www.ebi.ac.uk/QuickGO/term/GO:0003674)
A molecular process that can be carried out by the action of a single macromolecular machine, usually via direct physical interactions with other molecular entities. Function in this sense denotes an action, or activity, that a gene product (or a complex) performs.

I don't know the history of these definition changes, but this is also concerning.
(@giacomodecolle)

**Comment by addiehl** [comment]
I see that QuickGO registered a change to the molecular_function definition on 2023-03-06, so AmiGO is definitely behind on that.

On the other hand, I see that QuickGO registered a change to the cellular_component definition on 2023-10-28, so AmiGO will hopefully catch up on the next load.

**Comment by kltm** [comment]
@addiehl I'm pretty sure that this is related to #704 and likely https://github.com/geneontology/go-ontology/issues/18870 via https://github.com/geneontology/pipeline/issues/162; definitely not a direct AmiGO issue. Would you mind if I close this out to keep the conversation compact?

**Comment by kltm** [comment]
Likely duplicate based on #704; https://github.com/geneontology/go-ontology/issues/18870 via https://github.com/geneontology/pipeline/issues/162

**Comment by addiehl** [comment]
Thanks!
